### ISSUE TITLE
create_parent - error for a certain relation name

### ISSUE THREAD

**Issue by alinaradu** [pgpartman/pg_partman#208]
My table is called myschema.contentinstance_parts_inherited.
When calling the create_parent function, I have an error which I think is linked to the "_p" present in my table's name:
SELECT partman.create_parent('profileiot.contentinstance_parts_inherited', 'creationtime', 'partman', 'daily');

-----------------------------------------------------------------------------------------------------------------
ERROR:  invalid value "arts" for "YYYY"
CONTEXT: PL/pgSQL function show_partitions(text,text) line 52 at RETURN QUERY
PL/pgSQL function create_function_time(text,bigint) line 129 at FOR over SELECT rows
SQL statement "SELECT partman.create_function_time(p_parent_table, v_job_id)"
PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,boolean,text,boolean,boolean) line 621 at PERFORM
DETAIL: Value must be an integer.

I will try to avoid the problem by changing my table's name.

**Comment by keithf4** [comment]
Well that's interesting... I'll see if I can fix that when I get a chance. Thanks for reporting it!

**Comment by keithf4** [comment]
Can you tell me which version of PostgreSQL and which version of pg_partman you are running? Can you also provide the full schema details for your table (running `\d+ profileiot.contentinstance_parts_inherited` in psql should be fine).

The below seems to have worked fine for me in PG10 with the latest pg_partman 3.1.2
```
keith@keith=# create schema profileiot;
CREATE SCHEMA
Time: 12.999 ms
keith@keith=# create table profileiot.contentinstance_parts_inherited(id bigint, creationtime timestamptz not null);
CREATE TABLE
Time: 17.260 ms
keith@keith=# SELECT partman.create_parent('profileiot.contentinstance_parts_inherited', 'creationtime', 'partman', 'daily');
 create_parent 
---------------
 t
(1 row)

Time: 89.655 ms
keith@keith=# \d+ profileiot.contentinstance_parts_inherited
                               Table "profileiot.contentinstance_parts_inherited"
    Column    |           Type           | Collation | Nullable | Default | Storage | Stats target | Description 
--------------+--------------------------+-----------+----------+---------+---------+--------------+-------------
 id           | bigint                   |           |          |         | plain   |              | 
 creationtime | timestamp with time zone |           | not null |         | plain   |              | 
Triggers:
    contentinstance_parts_inherited_part_trig BEFORE INSERT ON profileiot.contentinstance_parts_inherited FOR EACH ROW EXECUTE PROCEDURE profileiot.contentinstance_parts_inherited_part_trig_func()
Child tables: profileiot.contentinstance_parts_inherited_p2018_02_23,
              profileiot.contentinstance_parts_inherited_p2018_02_24,
              profileiot.contentinstance_parts_inherited_p2018_02_25,
              profileiot.contentinstance_parts_inherited_p2018_02_26,
              profileiot.contentinstance_parts_inherited_p2018_02_27,
              profileiot.contentinstance_parts_inherited_p2018_02_28,
              profileiot.contentinstance_parts_inherited_p2018_03_01,
              profileiot.contentinstance_parts_inherited_p2018_03_02,
              profileiot.contentinstance_parts_inherited_p2018_03_03
```

**Comment by keithf4** [comment]
Please let me know if this is still an issue for you. Otherwise I will close this issue in the near future.

**Comment by alinaradu** [comment]
Hi, 

Sorry, I haven't had the time to investigate further. I will try and do it today and get back to you.
Sorry again.

**Comment by alinaradu** [comment]
Hello,

I finally had the time to investigate the issue. With PostgreSQL 9.6.8  and  pg_partman 3.1.3, I cannot reproduce the problem. 
I was running EDB before but I don't have access to that machine any more.
So I am closing the issue.
Thank you!
