### ISSUE TITLE
pg_partman child table not taking table space from template table when native partition

### ISSUE THREAD

**Issue by ajeykumar** [pgpartman/pg_partman#212]
Hi,

I'm using using partman with native partition,  i have template table with table space, when partitions are created table space of the template table are not inherited. i have checked the same with following query. 
select * from pg_tables where tablename='XXXXX'.
Can you please help me with this.

**Comment by keithf4** [comment]
Will check this out. Thanks for reporting!

**Comment by keithf4** [comment]
The tablespace should be getting inherited from the parent table, not the template table. pg_partman does not currently support the parent being in a separate tablespace fom the children and I don't see a reason for it to do so since the parent takes up next to no space.

**Comment by ajeykumar** [comment]
Hi Keith,

I specified table partitioned table with tablespace, if i check the the child table table space its empty. i created partition table with following script CREATE TABLE XXXX(YYYYYY TIMESTAMP NOT NULL) PARTITION BY RANGE (YYYYYY ) TABLESPACE SSSSS.

**Comment by keithf4** [comment]
Hmm yeah... looks like it just flat out ignores the tablespace designation all together on the parent table of a native set. Doesn't throw an error or anything, just doesn't set it at all. So will have to add that to the template option as well I guess.

**Comment by ajeykumar** [comment]
Ya, i have have add the tablespace both to parent and template, but the child not even taking it from parent or template table, we don't know what is the reason.

**Comment by keithf4** [comment]
Reason for it not inheriting from the parent is because postgres itself is just ignoring it. I've sent an email to the hackers list inquiring about this because it seems very misleading to me.

It doesn't work from the template because I did not program it to do so. I'll see about fixing that.

**Comment by keithf4** [comment]
Believe I got this working for the next release. Going to try and get it out later today. If not, will be first thing next week.

There's currently ongoing discussion on how to handle tablespaces with native partitioning if you're curious. So thanks for reporting this issue and getting that kicked off! 
https://www.postgresql.org/message-id/flat/CAODZiv6EBULTz1dP2KV84XMGgDaG%3DR3TxodK%2BovwHSPWECK8sQ%40mail.gmail.com#CAODZiv6EBULTz1dP2KV84XMGgDaG=R3TxodK+ovwHSPWECK8sQ@mail.gmail.com

````
keith@keith=# \d+ xxxx_template 
                                         Table "public.xxxx_template"
 Column |            Type             | Collation | Nullable | Default | Storage | Stats target | Description 
--------+-----------------------------+-----------+----------+---------+---------+--------------+-------------
 yyyyyy | timestamp without time zone |           | not null |         | plain   |              | 
Tablespace: "mytablespace"

keith@keith=# select partman.create_parent('public.xxxx', 'yyyyyy', 'native', '1 day', p_template_table := 'public.xxxx_template');
 create_parent 
---------------
 t
(1 row)

Time: 171.947 ms
keith@keith=# \d+ xxxx
                                             Table "public.xxxx"
 Column |            Type             | Collation | Nullable | Default | Storage | Stats target | Description 
--------+-----------------------------+-----------+----------+---------+---------+--------------+-------------
 yyyyyy | timestamp without time zone |           | not null |         | plain   |              | 
Partition key: RANGE (yyyyyy)
Partitions: xxxx_p2018_04_09 FOR VALUES FROM ('2018-04-09 00:00:00') TO ('2018-04-10 00:00:00'),
            xxxx_p2018_04_10 FOR VALUES FROM ('2018-04-10 00:00:00') TO ('2018-04-11 00:00:00'),
            xxxx_p2018_04_11 FOR VALUES FROM ('2018-04-11 00:00:00') TO ('2018-04-12 00:00:00'),
            xxxx_p2018_04_12 FOR VALUES FROM ('2018-04-12 00:00:00') TO ('2018-04-13 00:00:00'),
            xxxx_p2018_04_13 FOR VALUES FROM ('2018-04-13 00:00:00') TO ('2018-04-14 00:00:00'),
            xxxx_p2018_04_14 FOR VALUES FROM ('2018-04-14 00:00:00') TO ('2018-04-15 00:00:00'),
            xxxx_p2018_04_15 FOR VALUES FROM ('2018-04-15 00:00:00') TO ('2018-04-16 00:00:00'),
            xxxx_p2018_04_16 FOR VALUES FROM ('2018-04-16 00:00:00') TO ('2018-04-17 00:00:00'),
            xxxx_p2018_04_17 FOR VALUES FROM ('2018-04-17 00:00:00') TO ('2018-04-18 00:00:00')

keith@keith=# \d+ xxxx_p2018_04_09 
                                       Table "public.xxxx_p2018_04_09"
 Column |            Type             | Collation | Nullable | Default | Storage | Stats target | Description 
--------+-----------------------------+-----------+----------+---------+---------+--------------+-------------
 yyyyyy | timestamp without time zone |           | not null |         | plain   |              | 
Partition of: xxxx FOR VALUES FROM ('2018-04-09 00:00:00') TO ('2018-04-10 00:00:00')
Partition constraint: ((yyyyyy IS NOT NULL) AND (yyyyyy >= '2018-04-09 00:00:00'::timestamp without time zone) AND (yyyyyy < '2018-04-10 00:00:00'::timestamp without time zone))
Tablespace: "mytablespace"

**Comment by ajeykumar** [comment]
Thanks kathi,

When we can expect the release, if it is tool late, i need to look for workaround.

**Comment by keithf4** [comment]
Version 3.1.3 has been released with this fix. Let me know if it's working ok for you.

**Comment by ajeykumar** [comment]
Thanks for the update, could please tell me the step to apply this patch, is it seamless update?

**Comment by keithf4** [comment]
You should just be able to upgrade the extension as normal following the top level README

https://github.com/pgpartman/pg_partman#upgrade

However, the tablespaces won't be applied on any existing child tables. You'll have to go back and do that manually. They should get applied on any newly created child tables after the upgrade though.

**Comment by ajeykumar** [comment]
Thanks, its working
