### ISSUE TITLE
duplicate key value violates unique constraint "part_config_parent_table_pkey"

### ISSUE THREAD

**Issue by thanhlv93** [pgpartman/pg_partman#215]
Hello,
I'm creating the partition for my table but I got an error : 

> ERROR:  duplicate key value violates unique constraint "part_config_parent_table_pkey"
CONTEXT: SQL statement "INSERT INTO public.part_config (
        parent_table
        , partition_type
        , partition_interval
        , epoch
        , control
        , premake
        , constraint_cols
        , datetime_string
        , automatic_maintenance
        , inherit_fk
        , jobmon 
        , upsert
        , trigger_return_null
        , template_table)
    VALUES (
        p_parent_table
        , p_type
        , v_time_interval
        , p_epoch
        , p_control
        , p_premake
        , p_constraint_cols
        , v_datetime_string
        , p_automatic_maintenance
        , p_inherit_fk
        , p_jobmon
        , p_upsert
        , p_trigger_return_null
        , v_template_schema||'.'||v_template_tablename)"
PL/pgSQL function create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,boolean,text,boolean,boolean) line 382 at SQL statement
DETAIL: Key (parent_table)=(public.tbl_db_quantity) already exists.
HINT: 

I run query : 

> SELECT create_parent('public.tbl_db_quantity','inserttime','partman','hourly');

And my structure table: 
 id:  integer
 inserttime : timestamp with time zone | not null default now()
 method : text
 value : integer 

I  dont know how to fix this issue, please tell me if you have any suggest.
Thanks a lot.

**Comment by keithf4** [comment]
You're violating the constraint that you can't have more than one configuration for a given parent table. Check the contents of the `part_config` table. 

If you dropped a partitioned table without using one of the `undo_partition` functions, that will leave the old configuration in the above table. I do that myself accidentally as well. If you need to repartition that table, just delete that entry from the config table and try again. In the future try to use the relevant `undo_partition` function first before dropping it. That will remove the configuration information for you as well.

**Comment by thanhlv93** [comment]
Thanks @keithf4 , After remove extension and create again , I can run create_parent.

**Comment by noappleonhead** [comment]
Just deleting the row from part_config works for me
`DELETE FROM partman.part_config
WHERE parent_table = 'public. tbl_db_quantity';`
And you can check it by `select * from partman.part_config;`
