### ISSUE TITLE
partition_data_*, batch count and sub partitions.

### ISSUE THREAD

**Issue by blogh** [pgpartman/pg_partman#217]
Hi,

When I try this scenario, `partition_data_id `will not honor the batch value.
```
CREATE TABLE sc_bybb001_default.facture(id integer NOT NULL, objet text, ts timestamp with time zone NOT NULL DEFAULT current_timestamp);
INSERT INTO sc_bybb001_default.facture (id, objet, ts) SELECT trunc(random() * 50), 'Facture no ' || x, current_timestamp - random() * 2880 * INTERVAL '1 hour' FROM generate_series(1,100000) AS F(x);
SELECT partman.create_parent('sc_bybb001_default.facture', 'id', 'partman', '10');
SELECT partman.create_sub_parent('sc_bybb001_default.facture', 'ts', 'partman', 'monthly');
SELECT partman.check_parent();

SELECT partman.partition_data_id('sc_bybb001_default.facture', 10);
SELECT partman.check_parent();
```

I added a `RAISE NOTICE `after the `GET DIAGNOSTICS` and before the `EXIT `in `partition_data_id`:
```
[local]:5436@bybb001 as postgres =# SELECT partman.partition_data_id('sc_bybb001_default.facture',10);
NOTICE:  p_batch_count: 10, i:1, v_rowcount: 0, v_min_partition_id: 0, v_max_partition_id: 10
NOTICE:  No more rows to move !!
 partition_data_id
-------------------
                 0
(1 row)

[local]:5436@bybb001 as postgres =# SELECT partman.check_parent();
            check_parent
------------------------------------
 (sc_bybb001_default.facture,79993)
(1 row)

[local]:5432@btyb001 as postgres =# SELECT count(*), min(id), max(id) FROM (SELECT * FROM sc_bybb001_default.facture EXCEPT SELECT * FROM ONLY sc_bybb001_default.facture) AS F;
 count | min | max
-------+-----+-----
 20020 |   0 |   9
(1 row)
```

Since the data goes into the sub partitions of the target table, the batching doesn't take place because there are zero rows inserted in the table and when `v_rowcount = ROW_COUNT= 0` we exit the function. 

I am not sure if it's what you mean by this in the documentation ?
> For sub-partitioned sets, you must start partitioning data at the highest level and work your way down each level. All data will not automatically go to the lowest level when run from the top for a sub-partitioned set.

In that case the return value is wrong "0 lignes moved" and misleading because it's suppose to mean : parent table is empty and partitioning is complete.

PG versions: `9.4.17` and `9.5.12`
pg_partman version: `3.1.2`

Thx for the tool !
Benoit.

**Comment by keithf4** [comment]
So the first part of the documentation you quoted is true. You have to partition the data starting with the top level first before you go and run `create_sub_parent()`. So you should do:
```
CREATE TABLE ... 
INSERT INTO ...
SELECT partman.create_parent('sc_bybb001_default.facture', 'id', 'partman', '10');
SELECT partman.partition_data_id('sc_bybb001_default.facture', 10);
```
And then do
```
SELECT partman.create_sub_parent('sc_bybb001_default.facture', 'ts', 'partman', 'monthly');
```
And then run `partition_data_id()` on each of the sub parent tables.

Yes that's a lot more steps, but as you saw, it's hard to track when the data is getting filtered down through several sub-parent tables. 

The second sentence isn't very clear though. It is putting the data down through to the lowest level, but it can't really track it. I'll see if I can clarify it.

**Comment by blogh** [comment]
Thx. It worked great that way.

I was wondering if that:
```
EXECUTE format('WITH partition_data AS (
					DELETE FROM ONLY %I.%I WHERE %I >= %s AND %I < %s RETURNING *)
				INSERT INTO %I.%I SELECT * FROM partition_data'
			, v_parent_schema
			, v_parent_tablename
			, v_control
			, v_min_partition_id
			, v_control
			, v_max_partition_id
			, v_parent_schema
			, v_current_partition_name);

GET DIAGNOSTICS v_rowcount = ROW_COUNT;
v_total_rows := v_total_rows + v_rowcount;
IF v_rowcount = 0 THEN
	EXIT;
END IF;
```
could be replaced by something along those lines :
```
BEGIN
	EXECUTE format('WITH partition_data AS (
						DELETE FROM ONLY %I.%I WHERE %I >= %s AND %I < %s RETURNING *)
					INSERT INTO %I.%I SELECT * FROM partition_data'
				, v_parent_schema
				, v_parent_tablename
				, v_control
				, v_min_partition_id
				, v_control
				, v_max_partition_id
				, v_parent_schema
				, v_current_partition_name);

	GET DIAGNOSTICS v_rowcount = ROW_COUNT;
	v_total_rows := v_total_rows + v_rowcount;

	RAISE NOTICE 'p_batch_count: %, i:%, v_rowcount: %, v_min_partition_id: %, v_max_partition_id: %', p_batch_count, i, v_rowcount, v_min_partition_id, v_max_partition_id;	
	EXCEPTION WHEN OTHERS THEN 
		GET STACKED DIAGNOSTICS v_exception_text = PG_EXCEPTION_DETAIL;
					  
		RAISE EXCEPTION 'partition_data failed to move data from table %.% range [%, %[ into table %.% with exception %'
			, v_parent_schema
			, v_parent_tablename
			, v_min_partition_id
			, v_max_partition_id
			, v_parent_schema
			, v_current_partition_name
			, v_exception_text;
END;
```
That way it's possible to honor the p_batch_count event with subpartitions.
The number of lines is still wrong in the end, but to me it looks better. 
Did I miss something ?

**Comment by keithf4** [comment]
Hmm.... I guess that could work, although I really don't like the lack of progress feedback. When you're dealing with a huge table, it's good to know how far along it is. And sub-partitioning is really only effective on HUGE amounts of data since it all lives in the lowest level anyway.

Also, I believe this isn't an issue with native partitioning either since the GET DIAGNOSTICS stuff just works.

So for now, I think I'm just going to leave things as they are.

**Comment by blogh** [comment]
Ok thank you for the feedback.
