### ISSUE TITLE
sql table postgres 10 partition no native

### ISSUE THREAD

**Issue by LuisBonsembiante** [pgpartman/pg_partman#221]
Hi guys..thanks for the project. Im try to create a partition table in postgres 10..but when I saw the sql... did not use partition by...just the all way.... please tell me if use the inherit or the native partition....thanks

**Comment by keithf4** [comment]
pg_partman supports native partitioning as of version 3.01. See the `create_parent()` function information in the docs/pg_partman.md file for how to tell it to use native.

**Comment by keithf4** [comment]
If you don't have any other questions regarding this, I will be closing the issue tomorrow.

**Comment by LuisBonsembiante** [comment]
Unfortunely partition native in Postgresql doesnt work with any ORMs frames....because dont support FK and PK... is a very bad implementation of PostgreSQL.....

**Comment by keithf4** [comment]
PostgreSQL 11 will have primary key and some foreign key support (foreign keys from the partition space to other tables, but not the other way). PG10 got the basic framework of partitioning in place and future versions are building off of that.
