### ISSUE TITLE
Make install refuses to install claiming out of date postgresql

### ISSUE THREAD

**Issue by l4cr0ss** [pgpartman/pg_partman#224]
I have downloaded `v3.1.3` of `pg_partman`. I am running `Ubuntu 16.04 (xenial)`

My server had both `9.3` and `9.5` installed on it. After doing `apt-get purge postgresql-9.3` I still get the message `"Minimum version of PostgreSQL required is 9.4.0"` when trying to run `make install`.

**Comment by l4cr0ss** [comment]
I found and resolved this issue. Examining the `Makefile` revealed that `pg_config` was being called to supply the version information. `which pg_config` led me to `/usr/bin/pg_config`, which turned out to be a bash script. 

On closer inspection of `/usr/bin/pg_config`, I was able to determine that if the environment variable `"$LATEST_SERVER_DEV` is set it will be returned as the currently installed version, without checking to see if a more recent, non-development version exists.

As it happens, I had the distribution version of postgresql-9.5 (`postgresql-9.5`)installed and the development version of postgresql-9.3 installed (`postgresql-server-dev-9.3`). Installing the former package corrected the problem.

**Comment by keithf4** [comment]
Yeah, was just going to suggest you check that all the old packages were removed. `postgresql-9.3` is only the server component.

Glad you got it solved!

**Comment by keithf4** [comment]
FYI, debian based systems all use the "alternatives" system to manage the default versions of certain types of software that are installed. So that's another way to check what it thinks is the default for something

https://debian-administration.org/article/91/Using_the_Debian_alternatives_system
