### ISSUE TITLE
Native partitioning does not create unique indexes on child/partition tables when in template table

### ISSUE THREAD

**Issue by jnicholls** [pgpartman/pg_partman#225]
I have a template table that has a unique index, but when partitions are created they only have a normal index and not a unique index.  For example:

```
create table tpl_test (
  id bigint,
  ts timestamp
);
create unique index on tpl_test (id);

create table test (like tpl_test)
partition by range(ts);
select partman.create_parent('public.test', 'ts', 'native', 'hourly', p_template_table => 'public.tpl_test');
```

The created child tables only have regularly btree index on `id` and not a `UNIQUE` index.

**Comment by keithf4** [comment]
This issue will be fixed in the next release and is covered by https://github.com/pgpartman/pg_partman/pull/220
