### ISSUE TITLE
Need correlation name for upsert conditional

### ISSUE THREAD

**Issue by snhirsch** [pgpartman/pg_partman#228]
I have a situation where I'd like to specify a p_upsert clause using a WHERE.. qualifier that compares values between EXCLUDED and current columns.  Syntactically, this is only possible by prefixing the target column idenifier with either the full table name or a correlation name defined using 'AS blah'.  Problem is, the generated trigger has no correlation variable and the name of the table will vary by partition!  

My only option seems to be to dump the trigger source, hand-edit it and replace the generated trigger.  Am I missing a simpler workaround?

In any event, would you consider coding an ehancement to add a correlation variable to each upsert statement when generating the trigger?

**Comment by keithf4** [comment]
Upsert support at all was a bit tricky to get in and it's actually pretty limited in the fact that it still can't move data between partitions if necessary and never will be able to for trigger-based partitioning. With UPDATE support for native partitioning coming in PG11, I'm likely not going to be working on any further features for trigger-based partitioning at this time. I don't know if your UPSERT condition will be supported in PG11, but it should be supported in a future version.

**Comment by snhirsch** [comment]
Thanks for getting back so quickly.  I hacked up the function generation SQL to add the correlation variable.  Not elegant, but works fine.  I don't care about moving data between partitions.  I have a very tightly controlled situation where a key conflict can only occur in a single partition by construction - and I'm not trying to update any key components or the partition key.

HOWEVER: I did just discover that 'ON CONFLICT' is not firing in a test case where it absolutely should.  When digging further, I'm unable to find the index that should have been created on the child table.  Since a primary key was defined on the parent, I would have assumed such an index would exist.  Any idea what I'm missing?

**Comment by keithf4** [comment]
So you're saying the primary key was defined on the parent table, but it wasn't created on the child?

Did you add the primary key at a later time than you'd partitioned the table? It will only create indexes automatically on new child tables after that point. There's a python script included in pg_partman that can go back and recreate the indexes on the child table as they exist on the parent.

If it's not creating indexes/primary keys on new child tables, please share your configuration and table schema.

**Comment by snhirsch** [comment]
I was testing and burning at a high rate when that occurred, so I went back to square one to be sure of matters.  Long story short:  False alarm.  It was correctly propagating primary key and/or index (whichever I defined - tried both), but the issue with ON CONFLICT not firing seems related to test data ending up in the parent table.  

When I create the required child tables,  ON CONFLICT fires and works properly.  It does not work when data goes to the  parent table, even though I can see that your trigger is using the correct SQL and the same unique constraint that works for children definitely exists on the parent.  Is this a Postgres limitation or bug?

**Comment by snhirsch** [comment]
I did understand that to be the case, however the conflicting data was also in the parent.  It's not clear why this didn't result in ON CONFLICT firing.

**Comment by keithf4** [comment]
I'm really not sure. If you can possibly provide me a use-case example I can look into it.

**Comment by snhirsch** [comment]
The light just went on.  When a suitable partition cannot be found, your generated trigger simply does 'RETURN NEW' to let Postgres insert the record directly into the parent.  Since the ON CONFLICT clause exists only for statements that target child tables it has no choice but to throw a key violation.  Since i'm already down this path, I'll further hack the code generator to target the parent table explicitly and lock out nested calls.  Can you see a better way to do this?

In any event, I think this behavior is worth a line or two of mention in the 'Unique Constraints & Upsert' section of the docs.

**Comment by keithf4** [comment]
So I really do appreciate you finding the root cause of this, but at this time, I'm currently adding a note to the documentation section you mentioned that UPSERT support will be getting removed for trigger-based partitioning after PG11 has been out for a while. As I've been working on implementing PG11 features in pg_partman, I've realized they have much better UPSERT support than I will ever be able to provide and it is only getting better for future versions.

**Comment by snhirsch** [comment]
Sure, that makes sense.  In other breaking news, my employer is moving to RDS Postgres for production use.  As you know, they don't make pg_partman available nor do they respond to questions as to why it is not.  This is the most bloody innocuous extension that one could imagine, so I have to assume the situation is either laziness or politics at Amazon.  I'm currently fighting with my project manager to let me install pg_partman manually.  If that fails, I'm doomed to reinvent it as part of our application.

**Comment by keithf4** [comment]
Yeah, I keep asking them about it at every conference I see the devs at. Not sure what the holdup is anymore.

I am making it a little more friendly to install to RDS, though, by making sure the @extschema@ macro is used during object creation. So you should be able to do a find-n-replace on the sql file generated by make and just run that. However, after that, updates can be very challenging to manage since you have no way of knowing which version is installed.

**Comment by snhirsch** [comment]
That will be a big help.  Is this change available now from Git?

**Comment by keithf4** [comment]
Not yet. I hope to have v4.0.0 out in the very near future, which will have that change.

**Comment by keithf4** [comment]
Actually, there is still one part of pg_partman that requires security definer with superuser object ownership. The system to inherit the parent's privileges to the children requires access to the pg_authid table. Last I had heard, RDS does not allow this access, even with their special superuser account. That may have changed, though.

I added a feature request to make this privilege inheritance optional. This isn't specifically for RDS compatibility, it's just a general fix to make the only thing left that required superuser optional. Also it will only be in place for native partitioning. Not sure when I will get around to adding this feature, though.

https://github.com/pgpartman/pg_partman/issues/231
