### ISSUE TITLE
Update from 1.8.7 to 3.2.1

### ISSUE THREAD

**Issue by bilby91** [pgpartman/pg_partman#229]
Hello,

I'm working an upgrade process from pg 9.2 to pg 10.5. Currently we are running pg_partman 1.8.7 in the 9.2 instance and we want migrate to the latest version of pg_partman if possible. 

I saw the documentation for the upgrade process and it seems that after getting the binaries for 3.2.1 I just need to run `ALTER EXTENSION pg_partman UPDATE TO '3.2.1';` I'm wondering how the tiggers that are already present in my database are going to be migrated ? I saw in the repository that there are a lot of update scripts but they seem to be only available for subsequent version bumps. Are those scripts going to be run when doing the `ALTER EXTENSION statement` ?

Thanks before hand!

**Comment by keithf4** [comment]
The way extension updates work is that all of them run in sequence, going by the order defined by each update's file name to chain them together, from the one you're at to the target one. I would HIGHLY recommend you reading through the CHANGELOG file very carefully, most especially the section about going from 1.8.x to 2.x and then 2.x to 3.x. There may be some manual steps you want to run. It's a lot to read, but I've always tried to call out any special instructions whenever necessary if anything needs to be done outside of the ALTER EXTENSION statement. There's also a few points were you may run into a specific error that requires you to do the upgrade in stages (Ex 2.6.4 & 3.0.1)

In fact, I might suggest doing the upgrade to 2.x first instead of going straight to 3.x. You can give the update statement target version numbers.

`ALTER EXTENSION pg_partman UPDATE TO '2.0.0'`

If there's any way you can make a copy of your database and test the upgrade first, I would recommend that. This is going to be quite a large upgrade and I'd like to know how this goes for you either way. If there's any issues, I'll try my best to assist to hopefully help anyone else upgrading in the future.

**Comment by bilby91** [comment]
@keithf4 Thanks a lot for the quick reply!

We are going to test the process in a sandbox environment before attempting this in production, I will report back as soon as we get started. 

In order to do the multiphase upgrade you suggest, should I need to maintain all the different versions installed at the same time ? I'm guessing I will need to install the 2.X version as well. 

What did you mean with `This is going to be quite a large upgrade` ? Where you referring in terms of time ? If so, we are running a pretty big db (Multi TB), db size can affect the update process performance ?
 
One other thing we were wondering while reviewing the different extensions that we have is how pg_partman (1.8.7) affects our database schema. We've done successful migrations to pg10 without installing pg_partman. What would happen if we don't install the extension ? Current triggers will still be working but new partitions will never get created ?

**Comment by keithf4** [comment]
By large, I just meant the amount of versions you're upgrading through. Once you review the CHANGELOG, you'll see quite a lot has happened.

You won't be maintaining multiple versions of the extension in the same database. Each "stage" of the upgrade, will change the version that is installed. So for example the first stage would take your current 1.8.7 version and change it to 2.0.0. From there, you could then see about running the manual steps mentioned in the CHANGELOG to force the trigger functions to update. Then from there see about updating to 3.x.  I will say the change from 2.x to 3.x should hopefully be smoother.

Unfortunately, from 2.x forward, the triggers do require the extension to be installed, but only if it hits the code-path where data doesn't fall within the optimized range that just does straight INSERT statements.  Prior to 2.x, the old "static" partitioning method would work fine without the extension being installed, but from 2.x forward, the "static" and "dynamic" triggers were combined. You can see an example of the current trigger functions from one of my presentations below. Specifically it uses the check_name_length() function to ensure it's getting a consistent child table name.

http://slides.keithf4.com/partitioning_thennow/#/6

**Comment by bilby91** [comment]
This makes total sense. Thanks a lot for taking the time to explain details! Will post more information soon!

**Comment by bilby91** [comment]
@keithf4 I've been reading the CHANGELOG and this is what I understood from it.

1) Run `ALTER EXTENSION pg_partman UPDATE TO '2.0.0'` to upgrade to 2.0.0 version
2) Manually run `pg_partman--1.8.7--2.0.0.sql` (Interested in understanding a little better this comment `I cannot make this automatically part of the update because doing so would cause all the new trigger functions that are created to be part of the extension`)
3) Run `ALTER EXTENSION pg_partman UPDATE TO '3.0.0'` to upgrade to 3.0.0 version 
4) Run `ALTER EXTENSION pg_partman UPDATE TO '3.0.1'` to upgrade to 3.0.1 version 
5) Run `ALTER EXTENSION pg_partman UPDATE TO '3.2.1'` to upgrade to 3.2.1 version 

Is that accurate ?

Side question regarding our previous conversation on not having pg_partman installed. Assuming the scenario I explained above (were the extension itself is not installed but the triggers are still part of the schema) I can't run `run_maintenance()` because that depends on the plugin. In consequence, I won't get new partitions created. If that is the case, INSERTs that don't end up in one of the if conditions will go in the parent table ? That is my understanding from the generated triggered.

Is there any problem that you can see if we run version 1.8.7 with postgresql 10.X ? We are exploring the upgrade of pg_partman as a second step in our upgrade process to minimize risk.

Thanks again!

**Comment by keithf4** [comment]
I do not mean to manually run the entire SQL file itself. There are instructions within that file in the comments at the top to manually migrate the trigger functions. My comment is referring to specifically to those steps in the comments, not the entire update itself.

Any objects that are created during an extension installation or update are automatically made part of that extension. If you run `\dx+ pg_partman` you can see all objects that are part of pg_partman. So if I tried to recreate your table's trigger functions as part of the extension update itself, those new trigger functions would then be added to the extension's object library, which you don't want to happen. 

If the extension isn't installed, it won't simply skip to the part where it inserts to the parent. It first runs the dynamic section to see if the proper child table exists that wasn't covered in the INSERT statements above it. That section would just outright fail along with your attempted insert. pg_partman really does need to be installed for things to work properly from 2.x onward

You should be able to run 1.8.7 in PG10. So yes, updating pg_partman after you upgrade postgres itself should work. I believe you will have to install the 1.8.7 files to your PG10 extensions directory, though. Even pg_upgrade just does a dump/restore of the schema and the only part of an extension that is output when a dump is done is the "CREATE EXTENSION ..." statement, not all the individual extension objects. So just make sure you run the "make install" with 1.8.7 and PG10 as the target install first before you upgrade the database. Then after that, run the "make install" for the latest version of pg_partman. You can find all the old tagged releases here: https://github.com/pgpartman/pg_partman/releases

**Comment by bilby91** [comment]
@keithf4 Thanks again!

I spotted the comment piece of the script that I manually need to run :)

My question about the extension not being installed was specifically about 1.8.7. If the version is the latter one, the default would be to insert in parent right ? I saw that the new fallback function is introduced in 2.0.0.

We will definitely make sure that extensions directory in pg10 contains pg_partman code!

One extra thing that we have been experiencing for the last couple of month is some locking situation when calling `run_maintainaince`. Basically, when `autovacuum for wraparound` is running on a partitioned table and `run_maintainaince` is invoked, the DDL statement from pg_partman to disable autovacuum needs to wait until the `autovacuum` is finished. This triggers a cascading of locking because of the DDL statement waiting for the `autovacuum`. Is this scenario improved in later versions ? 

Thanks a lot, I really appreciate all the support you are giving!

**Comment by keithf4** [comment]
Ahh yes, you're right. If all your old partition sets are using the "static" method and are not using a custom time interval, then they should work fine without pg_partman being installed. Still, probably want to double-check that.

And just saying again so be sure... make sure the target PG10 has the 1.8.7 release installed. Otherwise, it will automatically try to install the latest 3.x version during the postgres upgrade.

If you have `autovacuum for wraparound` running, I would try to fix things so that isn't happening on a regular basis. This may mean scheduling manual vacuums. There's really no way to avoid the locking situation happening otherwise. As far as I'm aware, the only code in the latest pg_partman that disables autovac is in the python scripts when you're partitioning/unpartitioning a table. And you can disable that feature with a flag if necessary.

**Comment by bilby91** [comment]
@keithf4 Got it on the upgrade comment. I was thinking that maybe if I had 3.X installed but my internal `pg_partman` tables said I'm running `1.8.7`, the latter was going to be favored. I will only install `1.8.7` and then deal with the upgrade.

Totally agree on trying to fix the `autvacuum`, we are actively working on that. I had the hope that maybe something had changed in pg_partman that would improve it but at the same time I understand the constraints and limitations.

Thank again 🎉

**Comment by keithf4** [comment]
Just curious if you were able to get pg_partman upgraded between such a large gap in the version numbers?

**Comment by keithf4** [comment]
Closing this issue for now. Please feel free to respond or open another issue if you're having any upgrade issues. I would still like to know if this upgrade worked for you.

**Comment by bilby91** [comment]
@keithf4 We didn't end up upgrading `pg_partman` for the moment. We were able to successfully operate our database after the migration with versions 1.8.7. Getting the migration from pg 9.2 to 10 with postgis 1.5 to 2.4 was a really time consuming task for us. We had to move 8TB with minimal downtime. 

Once we get the upgrade for pg_partman done I will let you know!

Thanks again!
