### ISSUE TITLE
run_maintenance does not update trigger function if there are no partitions to drop

### ISSUE THREAD

**Issue by cosgroveb** [pgpartman/pg_partman#233]
I have a pg_partman-managed time-based partition set. Upon creation of this partition-set, I'd like to set a particular value for `optimize_trigger` and see it reflected in the trigger function. To that end, I'm doing the following:

1. Create parent table (let's call it `foo.bar_table`)
2. `SELECT partman.create_parent('foo.bar_table', 'created_at', 'time', 'weekly', p_premake := 12);`
3. `UPDATE part_config SET optimize_trigger = 1 WHERE parent_table='foo.bar_table`;`
4. `SELECT partman.run_maintenance()`

After doing so, I notice that the trigger is not updated. From looking at the source of `run_maintenance` it would appear that it's because there are no partitions yet to drop: https://github.com/pgpartman/pg_partman/blob/v2.6.3/sql/functions/run_maintenance.sql#L308

In order to have my `optimize_trigger` setting take, I'm now calling `partman.create_function_time('foo.bar_table`)`. Is it expected that I should need to do this?

It's possible that everything is behaving as intended but I thought I'd open this issue to be sure.

I'm running pg_partman 2.6.3 with Postgres 9.6 on Debian Stretch, for what it's worth.

**Comment by keithf4** [comment]
`run_maintenance()` will only update the trigger function if a new child table is created or an old one is dropped. If you look in the `create_partition_*()` functions, you'll see the call in there as well. So if you just wait until your next child table is created, it should take care of itself. Or you can call it manually as you did as well, there's no harm in that. There's really no other easy way to detect when a value in the config table like that has changed to kick off `create_function`.

I would highly recommend updating to the latest version of pg_partman. Everything from 2.0.0 onward has been feature enhancements and many, many bugfixes. There's nothing that's backward incompatible anymore, although there may be something manual steps to do with the 3.x upgrade (see the CHANGELOG). I actually should have 4.0.0 out in the very near future as well.

**Comment by cosgroveb** [comment]
Thanks for the explanation @keithf4 around updates to the trigger function. 

We initially did not go to 3.2 right away because there are no Debian packages for the release that we're running. It was simple to backport, so we're on the latest now.
