### ISSUE TITLE
Zabbix foreign key violation

### ISSUE THREAD

**Issue by hugleo** [pgpartman/pg_partman#243]
I've created the partitions:

SELECT partman.create_parent(p_parent_table := 'public.acknowledges', p_control := 'clock',  p_type := 'partman', p_interval := 'monthly', p_epoch := 'seconds');
SELECT partman.create_parent('public.alerts', 'clock', 'partman', 'monthly', p_epoch := 'seconds');
SELECT partman.create_parent('public.auditlog', 'clock', 'partman', 'monthly', p_epoch := 'seconds');
SELECT partman.create_parent('public.events', 'clock', 'partman', 'monthly', p_epoch := 'seconds');
SELECT partman.create_parent('public.service_alarms', 'clock', 'partman', 'monthly', p_epoch := 'seconds');

SELECT partman.create_parent('public.history', 'clock', 'partman', 'monthly', p_epoch := 'seconds');
SELECT partman.create_parent('public.history_log', 'clock', 'partman', 'monthly', p_epoch := 'seconds');
SELECT partman.create_parent('public.history_str', 'clock', 'partman', 'monthly', p_epoch := 'seconds');
SELECT partman.create_parent('public.history_text', 'clock', 'partman', 'monthly', p_epoch := 'seconds');
SELECT partman.create_parent('public.history_uint', 'clock', 'partman', 'monthly', p_epoch := 'seconds');
SELECT partman.create_parent('public.trends', 'clock', 'partman', 'monthly', p_epoch := 'seconds');
SELECT partman.create_parent('public.trends_uint', 'clock', 'partman', 'monthly', p_epoch := 'seconds');

But now ever time that I disable a zabbix item I got the error:

pg_query(): Query failed: ERROR: insert or update on table "auditlog_details" violates foreign key constraint "c_auditlog_details_1"
DETAIL: Key (auditid)=(11223) is not present in table "auditlog". [triggers.php:476 → CApiWrapper->__call() → CFrontendApiWrapper->callMethod() → CApiWrapper->callMethod() → CFrontendApiWrapper->callClientMethod() → CLocalApiClient->callMethod() → CTrigger->update() → CTriggerGeneral->updateReal() → add_audit_ext() → DB::insert() → DBexecute() → pg_query() in include/db.inc.php:487]
Error in query [INSERT INTO auditlog_details (auditid,table_name,field_name,oldvalue,newvalue,auditdetailid) VALUES ('11223','','status','0','1','1436')] [ERROR: insert or update on table "auditlog_details" violates foreign key constraint "c_auditlog_details_1"
DETAIL: Key (auditid)=(11223) is not present in table "auditlog".]
pg_query(): Query failed: ERROR: current transaction is aborted, commands ignored until end of transaction block [triggers.php:476 → CApiWrapper->__call() → CFrontendApiWrapper->callMethod() → CApiWrapper->callMethod() → CFrontendApiWrapper->callClientMethod() → CLocalApiClient->callMethod() → CTrigger->update() → CTriggerGeneral->inherit() → CTemplate->get() → DBselect() → pg_query() in include/db.inc.php:369]
Error in query [SELECT DISTINCT h.hostid FROM hosts h,functions f,items i WHERE h.status=3 AND f.triggerid='14850' AND h.hostid=i.hostid AND f.itemid=i.itemid] [ERROR: current transaction is aborted, commands ignored until end of transaction block]

Zabbix version: 4.0.3
Postgresql version: 11.1
pg_partman version: 4.0

**Comment by hugleo** [comment]
I'm not sure if it's a pg_partman problem yet. I'm debugging further.

**Comment by keithf4** [comment]
Not sure which direction your foreign key is going, but you cannot have foreign keys going from another table into a trigger-based partition set. It is only checking against the parent table which is always empty.

PG11's native partitioning has some support for foreign keys into a partition set. I believe the FK must be included in the partition key, so it is of very limited use.

**Comment by hugleo** [comment]
At least the id key is correctlly returned:

$auditId = DB::insert('auditlog', [$values]);
$auditId = reset($auditId); // checked and $auditId = 11223
...
DB::insert('auditlog_details', $values); // fails here, however I think 11223 exists in middle of the transaction.

**Comment by keithf4** [comment]
A normal query of the table will show the value exists in the partition set because normal queries are following the inheritance tree and just reading from the child tables. Foreign key checks to a partitioned table set do not follow inheritance trees, so they will fail.

**Comment by hugleo** [comment]
hmm. So then I think is better that I remove the public.auditlog partition. Is there a way to revert back?

**Comment by keithf4** [comment]
Look at the undo_partition function/script

https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman.md#destruction-functions
https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman.md#scripts

**Comment by Doctorbal** [comment]
I would recommend using PSQL 11 Native Range Partitioning + pgpartman for Zabbix. I am currently using this and @keithf4 's excellent pgpartman has saved me hours of writing hacked together scripts. Thank you!

Zabbix tables that are worth partitioning (history* and trends* tables) also do not have foreign keys; only primary key constraints for the trends* tables.

If you do consider using PSQL 11 Native Range partitioning together with pgpartman you would need to create a new database and transfer the data; that is the avenue I used. This can be done on the same database or a fresh new system; whatever you please. You can then create the tables separately with the required native partitioning and then implement pgpartman. You could minimize downtime by using PSQL built-in logical replication (or pglogical) for a DB upgrade and use pgbouncer to simple pause connections and revert to the native partitioned database.

Example for history table. Create table on fresh PSQL 11 install.

```
CREATE TABLE public.history
(
    itemid bigint NOT NULL,
    clock integer NOT NULL DEFAULT 0,
    value numeric(20,0) NOT NULL DEFAULT (0)::numeric,
    ns integer NOT NULL DEFAULT 0
) PARTITION BY RANGE (clock);

CREATE INDEX history_1 ON public.history USING btree (itemid, clock);
```
Edit `postgresql.conf` or create a conf file such as `/etc/postgresql/11/main/conf.d/pgpartman.conf`
```
### General
shared_preload_libraries = 'pg_partman_bgw' # (change requires restart)

### Partitioning & pg_partman settings
constraint_exclusion = on
pg_partman_bgw.interval = 3600
pg_partman_bgw.role = 'zabbix'
pg_partman_bgw.dbname = 'zabbix'
pg_partman_bgw.analyze = off
pg_partman_bgw.jobmon = on
```
I used separate schema partman....
```
sudo -su postgres psql -d zabbix
```
Then create the SCHEMA and EXTENSION:
```
CREATE SCHEMA partman;
CREATE EXTENSION pg_partman schema partman;
```
Then you can create partitioned tables easily with...
```
select partman.create_parent('public.history', 'clock', 'native', 'monthly', null, 5, 'on', null, true, 'seconds');
```
Partition mantenance:
```
UPDATE partman.part_config SET retention_keep_table = false, retention = '3 month'
WHERE parent_table = 'public.history';
```
Then you could logically replicate (SQL statements) the tables over and the data from a non-partitioned DB, for e.g., will simply fall into the necessary native partitions. Works well IMO.
