### ISSUE TITLE
How do we configure the time(s) of day the background worker runs?

### ISSUE THREAD

**Issue by renaissanceGeek** [pgpartman/pg_partman#244]
I apologize if this is already documented somewhere but I couldn't find it.  We've scheduled run_maintenance() twice a day, and the client wants to make sure it runs outside of business hours.  Is there a config setting somewhere or some other way to specify what times it runs?

Thank you!

**Comment by keithf4** [comment]
There is currently no way to configure the background worker to run at a specific time. If you need that, I recommend just scheduling a call to the maintenance function with cron.

**Comment by renaissanceGeek** [comment]
Thank you for the prompt reply and for the awesome software!
