### ISSUE TITLE
Getting constraint violation when running run_maintenance

### ISSUE THREAD

**Issue by moray95** [pgpartman/pg_partman#247]
Hello,

I was doing some tests with postgres partitioning and pg_partman and have encountered an error when running `run_maintenance`. I don't exactly know what I did to enter such a state but I do have a dump of the database [here](https://github.com/pgpartman/pg_partman/files/2837417/partman_test.sql.txt) to be able to reproduce the issue. When running `select run_maintenance()` the error is as follows:

```
ERROR:  updated partition constraint for default partition would be violated by some row
CONTEXT: SQL statement "ALTER TABLE public.test_table ATTACH PARTITION public.test_table_p100 FOR VALUES FROM ('100') TO ('105')"
PL/pgSQL function create_partition_id(text,bigint[],boolean,boolean) line 170 at EXECUTE
PL/pgSQL function run_maintenance(text,boolean,boolean,boolean) line 357 at assignment
DETAIL: 
HINT: 
CONTEXT: PL/pgSQL function create_partition_id(text,bigint[],boolean,boolean) line 336 at RAISE
PL/pgSQL function run_maintenance(text,boolean,boolean,boolean) line 357 at assignment
DETAIL: 
HINT: 
CONTEXT:  PL/pgSQL function run_maintenance(text,boolean,boolean,boolean) line 398 at RAISE
```

Thanks in advance.

**Comment by keithf4** [comment]
Do you have a default partition that contains data in it? You cannot create a child partition that contains data that matches any that exists in the default. The way the default partition works in PG11 isn't that it just allows any other data that doesn't have a child. It basically has an ever-changing "anti-constraint" that is the opposite of all other child table constraints combined. So the same cannot exist in both the default and another child table.

**Comment by moray95** [comment]
Yes, there is a default partition with data in it. I understand the way the default partition works. But how can I handle such a situation? Isn't there a mechanism that can move the data from the default partition to a newly created child that matches the constraints on it?

**Comment by keithf4** [comment]
I have plans to add this feature into pg_partman, but I'm still working on it. See the following issue:  https://github.com/pgpartman/pg_partman/issues/230

You basically have to move the data out to an intermediary location, create the child table, then you can insert it back as normal and it should route it to the proper child table.

**Comment by keithf4** [comment]
Closing this issue for now. Please keep an eye on issue https://github.com/pgpartman/pg_partman/issues/230 to be closed for when this feature is added.

**Comment by Woodz** [comment]
> I have plans to add this feature into pg_partman, but I'm still working on it. See the following issue: #230
> 
> You basically have to move the data out to an intermediary location, create the child table, then you can insert it back as normal and it should route it to the proper child table.

It looks like this is now supported by `CALL partman.partition_data_proc(<tbl name>);`
