### ISSUE TITLE
Where is the database "pg_partman_bgw.dbname"

### ISSUE THREAD

**Issue by qibobo** [pgpartman/pg_partman#249]
There should be a database named with the value of "pg_partman_bgw.dbname", right? I do not found where the database locate in my PG server.

**Comment by keithf4** [comment]
No, you set that value equal to the names of one or more databases that you want pg_partman to run in
```
pg_partman_bgw.dbname = 'postgres'
```
or
```
pg_partman_bgw.dbname = 'mydb1,mydb2,mydb3'
```
Same for all the other bgw settings. You set their values if you want them to be different than the default.
