### ISSUE TITLE
ERROR:  case not found - show_partition_info(text,text,text) line 79 at CASE

### ISSUE THREAD

**Issue by aleszeleny** [pgpartman/pg_partman#252]
I have pg_partman installed in schema partman.

Partman background worker wrote following errors into logfile:
`LOG:  pg_partman dynamic background worker (dbname=test_db) dynamic background worker initialized with role postgres on database test_db
ERROR:  case not found
        CONTEXT: PL/pgSQL function show_partition_info(text,text,text) line 79 at CASE
        SQL statement "SELECT child_start_time                                              FROM partman.show_partition_info(v_parent_schema||'.'||v_last_partition, v_row.partition_interval, v_row.parent_table)"
        PL/pgSQL function partman.run_maintenance(text,boolean,boolean,boolean) line 196 at SQL statement
        SQL statement "SELECT "partman".run_maintenance(p_analyze := true, p_jobmon := true)"
        DETAIL:
        HINT: CASE statement is missing ELSE part.
CONTEXT:  PL/pgSQL function partman.run_maintenance(text,boolean,boolean,boolean) line 398 at RAISE
        SQL statement "SELECT "partman".run_maintenance(p_analyze := true, p_jobmon := true)"
LOG:  worker process: pg_partman dynamic background worker (dbname=test_db) (PID 21629) exited with exit code 1`

Looking at the code, the issue is exactly what the hint suggest - in case of 3 month interval partition if quarter is not identified (my datetime_string is YYYY-MM-DD, beause of different partition length for older partitions) .

I've created a pull request [251](https://github.com/pgpartman/pg_partman/pull/251) offering in CASE ELSE clause getting child partition start time using to_timestamp() as fallback.
Switching to interval of 4 months is workaround in the meantime.

**Comment by keithf4** [comment]
Will include this fix in next release. Thanks!

**Comment by keithf4** [comment]
This issue has been fixed in version 4.1.0. Thanks for reporting!

**Comment by aleszeleny** [comment]
Done a testcase, works like a charm, now. See update in https://github.com/pgpartman/pg_partman/pull/251

Thanks a lot for providing fixed version!

**Comment by keithf4** [comment]
Thank you!
