### ISSUE TITLE
LOGIN right needed - what's about pg_hba.conf

### ISSUE THREAD

**Issue by Markus-** [pgpartman/pg_partman#255]
In the manual the role partman is given the LOGIN-right, but it is not mentioned to adjust the pg_hba.conf.

So from my point of view partman can not LOGIN into the DB.
How does it works instead? Does the extension uses other methods to "LOGIN"? If not why the LOGIN right is needed?

Regards
Markus

**Comment by keithf4** [comment]
An hba.conf entry is needed, yes, just as any login user would need. How that entry is made, depends how you run maintenance.

If it's with the background worker, all that's needed is local permissions for the user defined with `pg_partman.bgw.role` (default `postgres`). This is typically trust/peer. May need to adjust this to md5/scram and use a .pgpass file if you're using your own custom user.

If you're running maintenance via cron, you'll need an entry that matches wherever that cron entry is being run from and by who.

If you're having any issues with that partman user, the connection errors in the postgres logs should be pretty clear as to where the connection is coming from by who to guide you in the right direction for the hba entry.

**Comment by Markus-** [comment]
So if I just use the background worker for partition maintenance with default settings (aka postgres) I won't need any additional user and go with peer authentication for the postgres-User, correct?

Regards
Markus

**Comment by keithf4** [comment]
All depends how your installation, or you, set up your current pg_hba.conf. Different distributions create different pg_hba.conf files for the ones their packages manage. And not everyone keeps the "postgres" role around.  So I can't really speculate in general what people may or may not need to configure.

But if you have a "postgres" role in the database and a "postgres" system user, then yes "peer" will work.

**Comment by Markus-** [comment]
Ok. I will try. 

Thanks for the insights.
Markus
