### ISSUE TITLE
how to drop child tables immediately

### ISSUE THREAD

**Issue by Matrix-Zhang** [pgpartman/pg_partman#259]
i know how to drop old ones, but for migration script, i need drop all of them in down.sql

**Comment by keithf4** [comment]
Not sure what you mean by "immediately". It's not possible to have zero child tables with pg_partman, but you could set the retention period to be low enough so that only one is ever kept.

**Comment by Matrix-Zhang** [comment]
with my migration scripts, there are two script, one is up.sql, and another one is down.sql, up is create tables, down is drop tables means rollback, so i want drop the parent table and childs immediately

**Comment by keithf4** [comment]
If you want to undo a partition set, please see the documentation for the undo_partition* set of functions and choose the one appropriate for your situation. That will move all the data from all child tables back to the parent and then remove all the configuration information for that set from pg_partman. After that, you can then drop the old parent table as you see fit.

**Comment by Matrix-Zhang** [comment]
i had use partman.undo_partition('parent_table');
```
 undo_partition 
----------------
 (11,0)
(1 row)
```
and  \dt, the child table still exist

**Comment by keithf4** [comment]
Please read the documentation on the undo_partition options. Without telling it specifically to drop old child tables, it will not due so. It tries to be as safe as possible by default.

**Comment by Matrix-Zhang** [comment]
sorry for my bad english, i see the option finally....

**Comment by keithf4** [comment]
No need to apologize. Glad you got things working!
