### ISSUE TITLE
Dump configuration

### ISSUE THREAD

**Issue by jcoleman** [pgpartman/pg_partman#260]
Are there by any chance plans to include a function that would dump configuration to `SELECT create_parent`/`UPDATE part_config`/etc. calls? Output would be useful for inclusion in a .sql schema dump instead of having pg_dump naively dump each existing partition.

**Comment by keithf4** [comment]
Just for clarification, are you asking for something that will output what the `create_parent()` call should be for all existing partition sets?

**Comment by jcoleman** [comment]
Yep! (And ideally any `UPDATE part_config` queries needed to tweak things that aren't configurable by the `create_parent` call.

**Comment by keithf4** [comment]
Ok. I'll see if I can get something like that my next development round. No ETA on that tho.

**Comment by jcoleman** [comment]
I have a function to do this -- at least for our needs; I'll try to push it up tomorrow (at minimum as a WIP -- might not have docs added yet etc.)

**Comment by keithf4** [comment]
This has been added in the v4.3.0 which was released last week.
