### ISSUE TITLE
Are partition check constraints required?

### ISSUE THREAD

**Issue by ugtar** [pgpartman/pg_partman#264]
This is really a question, but I couldn't find a mailing list anywhere..

I am using partman for a time-series partitioning scheme with partitions based on timestamp.  The data comes in batches of 10s of thousands of rows that I insert directly into the appropriate partition using COPY.  The partition tables have a check constraint that verifies the timestamps are within the appropriate range for that partition.  My question is, is that check constraint required for partman to function properly, or can it be dropped (with the understanding that I am now responsible for ensuring that only appropriate rows will go into the partitions)?

**Comment by keithf4** [comment]
If you're using old, trigger-based partitioning, you could certainly drop it and, as you said, you'd then be responsible for any conflicting data existing across children.

With native partitioning, the constraints are built in, so I don't believe that's possible. 

If your concern is performance issues, and you're still using trigger-based partitioning, I'd highly recommend migrating to native for significantly improved performance if possible. Especially in PG11 and the upcoming 12.

**Comment by ugtar** [comment]
sounds good, thanks!
