### ISSUE TITLE
Windows installtion for background worker

### ISSUE THREAD

**Issue by rajinderbedi** [pgpartman/pg_partman#271]
I've followed the below steps as mentioned in the Windows Installation issue and pg_partman is working fine. But now I want to run background worker. For this, I need to first set up the background worker. I googled and gone through documentation but didnt find any help related to installtion of it on windows. 

Please guide and share the steps to get it installed on windows and configuration settings.

Steps :

Download the zip from of this project, and unzip it.
Open the pg_partman.control file in a text editor. Make note of the default_version value. At the time of writing, it is 1.8.3.
Open up a Windows command prompt. Navigate to the location where you unzipped it. For example:
cd C:\Users\Scott\Downloads\pg_jobmon-master\pg_jobmon-master
Run this command to copy all the sql files into 1 file sql file. Change '1.8.3' to the version noted in the above step.
If using Postgres 9.2 or higher:
copy sql\types\*.sql + sql\tables\*.sql + sql\functions\*.sql + sql\92\tables\*.sql pg_partm

**Comment by keithf4** [comment]
The background worker requires compiling the C code into a binary library. Unfortunately, I do not do any Windows development myself, so I'm not sure how to do that. I would suggest looking into how to compile PostgreSQL itself on Windows and if you can do that, you should then be able to compile the background worker library for pg_partman.

Also, pg_partman is well beyond version 1.8.3 now, so I'd make sure you are using at least the latest version, currently 4.2. Also the minimum required version of PostgreSQL is now 9.5.

**Comment by rajinderbedi** [comment]
Thanks your prompt reply.

As per documentation, pg_partmam background worker is just a scheduler that runs the run_maintenance() function.

So my question is that if I configure postgres agent.and schedule it to call run_maintenance() function then there is no need for background worker and it will serve the same purpose.

Please guide.

**Comment by keithf4** [comment]
That is correct. However, if you're on PG11 or higher, I would recommend looking into the `run_maintenance_proc()` stored procedure instead.

**Comment by rajinderbedi** [comment]
I am working on the automatic creation of partition tables(child tables) using run_maintenance() function. While going through the documentation and source code, I've come across some terms like time-static, time-dynamic and found the below description in the documentation.

_**Every run checks all tables listed in the part_config table with the types time-static, time-dynamic, or time-custom to pre-make child tables**_

But I idn't find **_TYPE_**column in the part_config table and also didn't find any values like time-static, time-dynamic in the part_config table.

Please also let me know how run_maintenance() function performs the automtic creation of child tables. For example, my use case is that a new partition table gets created every month then how run_maintenance achieves this? 

Please guide.

**Comment by keithf4** [comment]
What version of pg_partman are you running? 

Those types were deprecated back in version 2.0.0. If you can point out any places in the current documentation or source code where that is still mentioned, I'd appreciate it and I will update that ASAP to be less confusing.

If you're still using a version prior to 2.0, those are no longer supported and I highly recommend you update to the latest (currently in the 4.x series).

**Comment by keithf4** [comment]
Will be closing this issue by the end of the week if I don't hear anything back. Feel free to respond again later if you're still having issues.
