### ISSUE TITLE
pg_parman is scanning all the child table instead of relevant child tables per date

### ISSUE THREAD

**Issue by vasukamma2000** [pgpartman/pg_partman#280]
We have table loginfo , the following query is scanning all the child tables, instead of 10/14&10/15 tables.am i missing any configuration?

i have partitioned the table on logdate 

select * from from loginfo WHERE logdate>='2019-10-14'
and logdate<='2019-10-15'

**Comment by keithf4** [comment]
Please share the version of postgres you are using, the version of pg_partman, your partition table's full schema as well as the pg_partman configuration.

**Comment by vasukamma2000** [comment]
PostgreSQL DB version is 10.4
partman.part_config 
parent table = loginfo 
control= logdate
partition_type = partman
premake=10
partition_interval = 1 day
optimize_integer=4
optimize_constraint=30
epoch=none
inherit_fk=true

please sugget in i need to provide any other configs

**Comment by vasukamma2000** [comment]
deployed in AWS RDS

**Comment by keithf4** [comment]
Also need the table schema and what version of pg_partman you are running.

Also, there really is no good support for running pg_partman in RDS unfortunately. You can technically install the plpgsql code there, but it's impossible to manage it as an extension.

**Comment by keithf4** [comment]
I need the additional information I requested in order to provide any further assistance. Only other thing I can think of to do without that is to ensure the partition set has been analyzed at least once via the parent table. You can enable automatic analyzing during maintenance on a per partition set basis if you find it's necessary.

**Comment by keithf4** [comment]
Closing this issue for now. If you are able to provide the details I've asked for to diagnose your original post, feel free to respond directly to this issue and I'm happy to reopen it.
