### ISSUE TITLE
run_maintenance doesn't remove future partitions outside of premake value

### ISSUE THREAD

**Issue by nobleread** [pgpartman/pg_partman#281]
Hi Keith,

I can see that if I have e.g. 150 future partitions made by `partman.run_maintenance`, because `partman.part_config.premake` was to set 150, and I change `premake `to e.g. 30 and run maintenance again, old future partitions are not removed, that is to say, I still have 150 future partitions, even though I only want 30. `retention_keep_table` is set to false. This is somewhat not symmetrical with behavior for old partitions, controlled by `partman.part_config.retention` - they are removed when outside of retention scope. Is this WAD and I am missing something? Couldn't find any explanation in documentation nor closed issues.

**Comment by keithf4** [comment]
That is working as designed. Retention is about managing past data, not future data. Premake is for making sure there's a minimum number of future tables, not a maximum. You're free to drop the future tables without any issues as long as they don't have any data you need.

**Comment by keithf4** [comment]
Closing this question for now. If you have any further concerns with this issue, please feel free to reply or make a new issue.
