### ISSUE TITLE
run_maintenance_proc and run_maintenance don't create new partitions.

### ISSUE THREAD

**Issue by hedgss** [pgpartman/pg_partman#283]
run_maintenance_proc and run_maintenance don't create new partitions.
Partman 4.2.2 without BGW
Table for partitioning.
```
CREATE TABLE session_partman
(
    id character varying (64) NOT NULL,
     session_time_created timestamp without time zone NOT NULL
)PARTITION BY RANGE(time_created );
```
Create partitions:
```SELECT partman.create_parent('public.session_partman', 'session_time_created ', 'native', '5 minutes', p_premake := 2, p_jobmon := false);```

```
postgres=# select now();
              now
-------------------------------
 2019-11-04 11:28:25.797857+00
(1 row)

postgres=# CALL partman.run_maintenance_proc(0, true, false, true);
NOTICE:  v_sql run_maintenance_proc: SELECT partman.run_maintenance('public.session_partman', p_jobmon := 'f', p_debug := 't', p_analyze := 't')
NOTICE:  run_maint: v_partition_expression: session_time_created
NOTICE:  run_maint: parent_table: public.session_partman, v_last_partition: session_partman_p2019_11_04_1130
NOTICE:  run_maint: v_current_partition_timestamp: <NULL>, v_max_time_parent: <NULL>
CALL
postgres=#
postgres=# \dt
                      List of relations
 Schema |               Name               | Type  |  Owner
--------+----------------------------------+-------+----------
 public | postgres_log                     | table | postgres
--------+----------------------------------+-------+----------
 public | postgres_log                     | table | postgres
 public | session_partman                  | table | postgres
 public | session_partman_default          | table | postgres
 public | session_partman_p2019_11_04_1100 | table | postgres
 public | session_partman_p2019_11_04_1105 | table | postgres
 public | session_partman_p2019_11_04_1110 | table | postgres
 public | session_partman_p2019_11_04_1115 | table | postgres
 public | session_partman_p2019_11_04_1120 | table | postgres
 public | session_partman_p2019_11_04_1125 | table | postgres
 public | session_partman_p2019_11_04_1130 | table | postgres
(10 rows)
```

It doesn't keep 2 partitions ahead as it is expected.
moreover, it even doesn't create the current partition.
```
postgres=# select now();
              now
-------------------------------
 2019-11-04 11:37:44.111272+00
(1 row)

postgres=# CALL partman.run_maintenance_proc(0, true, false, true);
NOTICE:  v_sql run_maintenance_proc: SELECT partman.run_maintenance('public.session_partman', p_jobmon := 'f', p_debug := 't', p_analyze := 't')
NOTICE:  run_maint: v_partition_expression: session_time_created
NOTICE:  run_maint: parent_table: public.session_partman, v_last_partition: session_partman_p2019_11_04_1130
NOTICE:  run_maint: v_current_partition_timestamp: <NULL>, v_max_time_parent: <NULL>
CALL
postgres=# \dt
                      List of relations
 Schema |               Name               | Type  |  Owner
--------+----------------------------------+-------+----------
 public | postgres_log                     | table | postgres
 public | session_partman                  | table | postgres
 public | session_partman_default          | table | postgres
 public | session_partman_p2019_11_04_1100 | table | postgres
 public | session_partman_p2019_11_04_1105 | table | postgres
 public | session_partman_p2019_11_04_1110 | table | postgres
 public | session_partman_p2019_11_04_1115 | table | postgres
 public | session_partman_p2019_11_04_1120 | table | postgres
 public | session_partman_p2019_11_04_1125 | table | postgres
 public | session_partman_p2019_11_04_1130 | table | postgres
(10 rows)
```

**Comment by keithf4** [comment]
Looks like it created the initial partition set properly since it has `1125` and `1130` based on the current time being `11:28`.
However, if the partition set doesn't contain any data, it will not create any new partitions. This is to keep it consistent with the way it behaves in integer-based partitioning and to keep it from making empty tables indefinitely. If you need it to keep creating new partitions even though you're inserting no new data, set the `infinite_time_partitions` option to true in the partition configuration table.

Some additional tips:
- I don't recommend lowering the premake value lower than 4. In fact it's best to keep it high enough to ensure it keeps enough partitions made to account for the entire time-range of data being inserted and any gaps in time when you may not be inserting any data.
- I highly recommend using `timestamp with time zone`. Unless every single system involved, from the database to the highest application level, is using UTC time, `timestamp without time zone` almost never works as you expect it to. So unless you have a specific use-case for that datatype, I recommend changing to `with timezone`.

**Comment by hedgss** [comment]
@keithf4 
Thanks a lot! It works.

I updated this value in the part_config directly because I don't see how can I change it in another way.
Thank you for the tips:

- Ok, We are going to use 1 calendar month as the interval. I set 5 minutes in the example in test purposes. I thought that it is more than enough time to create a new partition actually during 2 months (1 current month + 1 premake month). But sure I will set it to 4 months if it can prevent some issues.
- Thank you for this warning. All our application use UTC. The date will be converted to the current User date in this side if it is required. But you are right, we cannot have a guaranty that some application won't try to store by mistake date with none UTC timezone.

**Comment by keithf4** [comment]
That is the correct way to update it. Glad it worked! 

I have been having quite a few people report this as an issue, so I may revisit setting `infinite_time_partitions` to true by default and leave it as an option that can be turned off instead.

**Comment by hedgss** [comment]
Thanks a lot for your help and tips.
