### ISSUE TITLE
Column "relhasoids" does not exist

### ISSUE THREAD

**Issue by netvoip** [pgpartman/pg_partman#286]
I'm using partman 4.2.2 with non-native partitioning. After upgrading to PG12 partitioning stopped working with the errors above. Please help.

**Comment by keithf4** [comment]
This should have been fixed as of version 4.2.0. I checked and all references I can find to `relhasoids ` are wrapped in a version check condition. Are you sure you're running the most recent version? It must be updated on all databases in the instance individually.

If you're still having issues, can you please provide 
 - the output of `\dx` on the database that is having the errors
 - the full error that you are getting and when it happens. During maintenance? When writing to the table?
- the schema (`\d+ tablename`) of your partition set parent 
- the full contents of the `part_config` table for that partition set

**Comment by netvoip** [comment]
As it turned out extension was not fully upgraded because it was just installed new package and command "ALTER EXTENSION pg_partman UPDATE;" required. After doing that partitioning is working fine.
Sorry for a noob question and thanks for such an outstanding extension.

**Comment by keithf4** [comment]
Glad to hear you got things working. And thanks!
