### ISSUE TITLE
Run Maintenance failure when table has a foreign key to a partitioned table (Postgres 12) 

### ISSUE THREAD

**Issue by JorgeFMorais** [pgpartman/pg_partman#294]
When using _run_maintenance()_ function on a partitioned table, one of the expected outcomes is that old partitions are automatically deleted (when configured with _p_keep_table:=False_). However if there are tables referencing the partitioned table configured to be deleted on cascade an error is raised.

In my case, the error is raised by the function _drop_partition_time()_ which first attempts to detach the partition and then drop it. The operation detach partition raises a foreign key violation constraint error. 

However if there is no desire to keep the partition a drop can be performed directly over the partition and the cascade delete will work as expected. I have tried modifying the  _drop_partition_time()_ function myself so that the detach partition portion is ommited when  _p_keep_table:=False_ and seems to work fine.

Please let me know if this is a bug or some misuse of the extension on my side.

Regards

**Comment by keithf4** [comment]
I think I understand what you're running into here and I'll have to test it out myself as well. But your fix does make sense so far. Thanks for reporting the issue!

**Comment by keithf4** [comment]
Fix for this is in my "migrate" branch if you want to test it out - https://github.com/pgpartman/pg_partman/tree/migrate

**Comment by JorgeFMorais** [comment]
Seems to be all good! Any news on when this new version will be released?

**Comment by keithf4** [comment]
I'm hoping this week, but no promises
