### ISSUE TITLE
Is it possible to set a retention policy for a partitioned table?

### ISSUE THREAD

**Issue by hedgss** [pgpartman/pg_partman#298]
Is it possible to set a retention policy for a partitioned table?
I have one partition per month. I need to keep information for the last 14 months.
Is it possible to set that partitions that older than 14 months must be deleted automatically?

**Comment by keithf4** [comment]
pg_partman has retention policy configuration already built in. Please see this section of the documentation: https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman.md#retention

And then the configuration table to set the columns appropriately for your partition set's entry in the config table: https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman.md#tables

**Comment by hedgss** [comment]
@keithf4 thank you!
Perhaps you can clarify how it actually works

> For time-based partitioning, the interval value will set that any partitions containing only data older than that will be dropped.

I have a table that is partitioned by time (1 partition per month).
I have 4 pre-created tables.

If I need to keep partitions for the last 6 month and delete the old partitions I need to set 
`
retention = 6 mon
retention_keep_table = false
`
Pre-created partitions will be ignored.
All partitions that don't have data for the last 6 months will be deleted. It means that I have current partition that contains new data for the current month. The current partition and 6 old partitions will be always available.
It will be handled when the run_maintenance_proc is called.
Is it correct?

**Comment by keithf4** [comment]
Your settings are correct for cleaning up partitions that have data older than 6 months, but your wording here is rather confusing.

`Pre-created partitions will be ignored.`

Pre-created partitions aren't anything special other than the fact that they're supposed to be created _before_ any data that is intended for them is ever inserted. So, it's not that they will always be ignored, it's that they're typically in the future so won't be removed until sometime in the future when they contain data that is older than 6 months. Then they will be removed, but by then you'll have all new pre-created partitions.

`All partitions that don't have data for the last 6 months will be deleted.`

No, that is not what the section your quoting is saying. It says _any partitions containing ONLY data older than the interval value WILL be dropped_. Or if they're completely empty, they will also be dropped based on the table's name indicating what data should be in it. So, any partitions that solely contain data that is older than six months (compared to the value of "now" when the retention maintenance is run), will have that partition dropped. So in your case, if the entirety of a child table's data is 6 months or older, based on the partition columns value, it will be dropped.

Another key thing to not is the word _only_. If your child table contains some data that is older than 6 months and other data that is not, it will not yet be dropped. All the data in that child table must be older than the retention interval for it to meet the requirements to be dropped.

`It means that I have current partition that contains new data for the current month. The current partition and 6 old partitions will be always available. It will be handled when the run_maintenance_proc is called.`

This is correct. And, yes, maintenance handles both new child table creation and retention at the same time. If you're concerned about losing data, note that by default the child table is not dropped, only removed from the partition set. So you can leave `retention_keep_table` set to true until you're sure it's doing what you intend.

**Comment by hedgss** [comment]
Sorry, I think I didn't make myself clear.
@keithf4 Thanks a lot for the clarification and suggestions.
