### ISSUE TITLE
Syntax does not exist in PG10 - `USING INDEX TABLESPACE` 

### ISSUE THREAD

**Issue by KevMurph** [pgpartman/pg_partman#299]
I believe the PostgreSQL10 section of inherit template properties might be trying to execute some SQL that only exists in PG11.(https://github.com/pgpartman/pg_partman/blob/258679998659f7f3d2fb75b0d870eb19ff8296f6/sql/functions/inherit_template_properties.sql#L148). 

The syntax here (`ALTER TABLE ... USING INDEX TABLESPACE ...`) wasn't introduced until PG11.

SEE:
https://www.postgresql.org/docs/11/sql-altertable.html
VS
https://www.postgresql.org/docs/10/sql-altertable.html) 

I wanted to put this out to you to verify from your end if you see this as a problem and how you want to address it.

**Comment by keithf4** [comment]
You're correct, this appears to be a new clause that was added in PG11. Looks like for prior to PG 11, I'll have to do a separate ALTER INDEX statement after the primary key creation to set the tablespace.  Since this is still part of the pre-creation of the child table ahead of time, I believe this should work. I'll try and add some unit tests in to check as well.

Thanks!

**Comment by keithf4** [comment]
So actually, this just seems to be an undocumented clause in PG 10. The pgTAP suite doesn't actually have a test to see what tablespace an index is in, but I did have a test in place that was hitting this code path and it wasn't failing. Also just confirmed by running a simple use-case directly in PG 10. So I think this issue should be fine as is.

https://github.com/pgpartman/pg_partman/blob/master/test/test_native/tablespace/test-time-daily-native-tablespace-template.sql

```
$ psql
Expanded display is used automatically.

Current Host Server Date Time : Wed Apr  8 17:36:37 EDT 2020 

psql (10.11)
Type "help" for help.

keith@keith=# CREATE TABLE testing (col1 int);
CREATE TABLE
Time: 4.364 ms
keith@keith=# ALTER TABLE testing ADD PRIMARY KEY ("col1") USING INDEX TABLESPACE mytablespace;
ALTER TABLE
Time: 13.928 ms
keith@keith=# \d+ testing;
                                  Table "public.testing"
 Column |  Type   | Collation | Nullable | Default | Storage | Stats target | Description 
--------+---------+-----------+----------+---------+---------+--------------+-------------
 col1   | integer |           | not null |         | plain   |              | 
Indexes:
    "testing_pkey" PRIMARY KEY, btree (col1), tablespace "mytablespace"
```
