### ISSUE TITLE
Not new partitions are created if partitions are empty and default have values

### ISSUE THREAD

**Issue by adrianlzt** [pgpartman/pg_partman#303]
Having this config:
```
    parent_table    | partition_type | partition_interval | control | premake | undo_in_progress | sub_partition_set_full |  epoch  | infinite_time_partitions | retention
--------------------+----------------+--------------------+---------+---------+------------------+------------------------+---------+--------------------------+-----------
 public.history_str | native         | 01:00:00           | clock   |      72 | f                | f                      | seconds | f                        | 7 days
```

During some time I had not inserted data into that table.
Partitions were dropped (except one, not deleted by partman).
Then some data start to be inserted into history_str and now new partitions are being created.

The run_maintenance in debug mode shows this line:
```
NOTICE:  run_maint: v_current_partition_timestamp: <NULL>, v_max_time_parent: 2020-04-12 11:39:32+02
```

``v_current_partition_timestamp`` is ``NULL`` because there is no data in the uniqe partition remaining.
``v_max_time_parent`` is the latest row inserted in the default table.

The functions [compares](https://github.com/pgpartman/pg_partman/blob/258679998659f7f3d2fb75b0d870eb19ff8296f6/sql/functions/run_maintenance.sql#L230) that two values:
```sql
IF v_max_time_parent > v_current_partition_timestamp THEN
```

I think that is the problem. That comparison (time VS NULL) always return false.
I have made a small test in PG12:

```sql
create function test_compare_time_null() RETURNS void
    LANGUAGE plpgsql AS $$
DECLARE
v_current_partition_timestamp   timestamptz;
BEGIN
IF now() < v_current_partition_timestamp THEN
  RAISE NOTICE 'compare correct';
ELSE
  RAISE NOTICE 'compare false';
END IF;

IF now() > v_current_partition_timestamp THEN
  RAISE NOTICE 'compare correct';
ELSE
  RAISE NOTICE 'compare false';
END IF;
END
$$;
```

```
# select test_compare_time_null();
NOTICE:  compare false
NOTICE:  compare false
```

Meanwhile I will use ``infinite_time_partitions``.

**Comment by keithf4** [comment]
So you're saying the only partition that maintenance left behind after retention was the default? If that's the case, I would rather try and fix that issue. I wouldn't want the default to be the only partition that maintenance is leaving behind.

**Comment by keithf4** [comment]
Actually, I'm now curious how this happened. 

This checks to see if there is only one partition left when dropping partitions - https://github.com/pgpartman/pg_partman/blob/master/sql/functions/drop_partition_time.sql#L150. If only a single partition is returned by that function, then it's not dropped.

However the function it uses to do this is `show_partitions()`. This function does NOT show the default partition in the list by default, which is how it's called above. So if any other child table existed, maintenance should not have dropped it - https://github.com/pgpartman/pg_partman/blob/master/sql/functions/show_partitions.sql#L1

**Comment by adrianlzt** [comment]
No, there was one partition left plus the default.

My use case was to create the partitions, don't use them for a while and then start to add data.
All that new data was being stored in the default partition and no new partitions were being created.

**Comment by keithf4** [comment]
I see what's happening now. Thanks for clarification. I have a slight modification to your PR to properly handle additional conditions and rename a variable to a more fitting name. If you don't mind testing, it's in the gist below. This includes the fix for another issue someone reported recently as well.

https://gist.github.com/keithf4/f36693a1a8eacc41fd11f34746faf756

However, my recommendation for you on this long term would be to continue leaving `infinite_time_partitions` set. 

Or if you really don't expect to have data for really long periods between ingestion, monitor for data going into the default, and then if that data is valid, run the `partition_data_proc()` to move it out to the proper children. You definitely do not want to leave data in the default if it is valid as this can cause other significant maintenance problems if it builds up too much - https://github.com/pgpartman/pg_partman/issues/262#issuecomment-510921984

I think you'll find `infinite_time_partitions` handles things better, though, especially if your data is often valid. It will avoid you having to do any manual intervention at all and won't leave you with large gaps in the child tables.

**Comment by keithf4** [comment]
Or here's just the diff
```
diff --git a/sql/functions/run_maintenance.sql b/sql/functions/run_maintenance.sql
index 323b094..ded4b32 100644
--- a/sql/functions/run_maintenance.sql
+++ b/sql/functions/run_maintenance.sql
@@ -26,7 +26,7 @@ v_last_partition_created        boolean;
 v_last_partition_id             bigint;
 v_last_partition_timestamp      timestamptz;
 v_max_id_parent                 bigint;
-v_max_time_parent               timestamptz;
+v_max_time_default               timestamptz;
 v_new_search_path               text := '@extschema@,pg_temp';
 v_next_partition_id             bigint;
 v_next_partition_timestamp      timestamptz;
@@ -222,20 +222,19 @@ LOOP
         END IF; -- end infinite time check
 
         -- Check for values in the parent/default table. If they are there and greater than all child values, use that instead
-        -- This allows maintenance to continue working properly if there is a large gap in data insertion. Data will remain in parent, but new tables will be created
-        EXECUTE format('SELECT max(%s) FROM ONLY %I.%I', v_partition_expression, v_parent_schema, v_default_tablename) INTO v_max_time_parent;
+        -- This allows maintenance to continue working properly if there is a large gap in data insertion. Data will remain in default, but new tables will be created
+        EXECUTE format('SELECT max(%s) FROM ONLY %I.%I', v_partition_expression, v_parent_schema, v_default_tablename) INTO v_max_time_default;
         IF p_debug THEN
-            RAISE NOTICE 'run_maint: v_current_partition_timestamp: %, v_max_time_parent: %', v_current_partition_timestamp, v_max_time_parent;
-        END IF;
-        IF v_max_time_parent > v_current_partition_timestamp THEN
-            SELECT suffix_timestamp INTO v_current_partition_timestamp FROM @extschema@.show_partition_name(v_row.parent_table, v_max_time_parent::text);
+            RAISE NOTICE 'run_maint: v_current_partition_timestamp: %, v_max_time_default: %', v_current_partition_timestamp, v_max_time_default;
         END IF;
-
-        IF v_current_partition_timestamp IS NULL THEN 
+        IF v_current_partition_timestamp IS NULL AND v_max_time_default IS NULL THEN 
             -- Partition set is completely empty and infinite time partitions not set
             -- Nothing to do
             CONTINUE;
         END IF;
+        IF v_current_partition_timestamp IS NULL OR (v_max_time_default > v_current_partition_timestamp) THEN
+            SELECT suffix_timestamp INTO v_current_partition_timestamp FROM @extschema@.show_partition_name(v_row.parent_table, v_max_time_default::text);
+        END IF;
 
         -- If this is a subpartition, determine if the last child table has been made. If so, mark it as full so future maintenance runs can skip it
         SELECT sub_min::timestamptz, sub_max::timestamptz INTO v_sub_timestamp_min, v_sub_timestamp_max FROM @extschema@.check_subpartition_limits(v_row.parent_table, 'time');
```

**Comment by adrianlzt** [comment]
Maybe is a better default infinite_time_partitions=true?

Thanks for the fix.
I cannot test the bugfix sorry, finally I changed the infinite_time_partitions parameter and the db now is running.

I will close the PR

**Comment by keithf4** [comment]
The default for pg_partman has been to only create partitions based on existing data for quite a long time, so that's probably not going to change without some big justifications. Maybe when trigger-based partitioning goes away completely since that would be introducing another big change anyway? 

It also keeps it consistent with the way partitioning works with integer-based partitioning as well. In that case there never will be a general way to keep partitions being created infinitely when no new data is being entered.

**Comment by keithf4** [comment]
Version 4.3.1 has been released and does include your fix. However, I do still recommend the `infinite_time_partitions` setting in your case.
