### ISSUE TITLE
small note

### ISSUE THREAD

**Issue by okbob** [pgpartman/pg_partman#310]
https://github.com/pgpartman/pg_partman/blob/c2cfb1ced6e6e0647bff452173cf25d548637ac0/sql/functions/partition_data_time.sql#L304

There is not necessary dynamic SQL. `set_config` is function, and can be called via `PERFORM`

**Comment by keithf4** [comment]
Appreciate the note. When I have some time to do another code review, I'll see about looking at EXECUTE vs PERFORM. I think my initial concern here was SQL injection by setting the search path to some odd value. This at least forces the value passed to set_config to be treated as a string literal no matter what.
