### ISSUE TITLE
Running run_maintenance endlessly creates partitions

### ISSUE THREAD

**Issue by sach3000** [pgpartman/pg_partman#316]
Hello!

Using Postgresql 10 with pg_partman 4.2.0

Create schema partman on existing table with data.
This part_config applied:
```sql
parent_table               | dlix.transactions
control                    | idp_timestamp
partition_type             | partman
partition_interval         | 7 days
constraint_cols            |
premake                    | 4
optimize_trigger           | 4
optimize_constraint        | 30
epoch                      | none
inherit_fk                 | t
retention                  | 90 days
retention_schema           |
retention_keep_table       | f
retention_keep_index       | f
infinite_time_partitions   | f
datetime_string            | IYYY"w"IW
automatic_maintenance      | on
jobmon                     | t
sub_partition_set_full     | f
undo_in_progress           | f
trigger_exception_handling | f
upsert                     |
trigger_return_null        | t
template_table             |
publications               |
inherit_privileges         | t
constraint_valid           | t
```

after applying configuration partman, creating partitions for parent table

```sql
Indexes:
    "transactions_pkey" PRIMARY KEY, btree (id)
    "transactions_upload_id" btree (upload_id)
Triggers:
    transactions_part_trig BEFORE INSERT ON dlix.transactions FOR EACH ROW EXECUTE PROCEDURE dlix.transactions_part_trig_func()
Child tables: dlix.transactions_p2020w14,
              dlix.transactions_p2020w22,
              dlix.transactions_p2020w23,
              dlix.transactions_p2020w24,
              dlix.transactions_p2020w25,
              dlix.transactions_p2020w26
```

But after run the request `SELECT * FROM partman.run_maintenance(p_analyze := false);` miracles began. Request hung.
I forcibly stopped him and see:
```
ERROR:  canceling statement due to user request
CONTEXT:  SQL statement "SELECT max(idp_timestamp)::text FROM dlix.transactions_p2025w05"
PL/pgSQL function create_function_time(text,bigint) line 132 at EXECUTE
SQL statement "SELECT partman.create_function_time(v_row.parent_table, v_job_id)"
PL/pgSQL function partman.run_maintenance(text,boolean,boolean,boolean) line 287 at PERFORM
```
Where did p2025w05 come from?
That is, in an endless cycle, partitions begin to be created that are not really created.
As a result, if the request is not stopped, an exception occurs
**ERROR:  out of shared memory**
Turned on debug mode PG, there are no errors either by permissions.
Why such strange behavior and how to cure it?

**Comment by keithf4** [comment]
I see this is being done with the old trigger-based method. Does any data already exist in the parent table? Can you share the exact command you gave when you ran `create_parent`? Can you also share the full table schema so I can try and recreate this scenario?

**Comment by keithf4** [comment]
Nevermind, I see you did say the table currently has data. What is the maximum value for the partition column?

**Comment by sach3000** [comment]
> I see this is being done with the old trigger-based method. Does any data already exist in the parent table? Can you share the exact command you gave when you ran `create_parent`? Can you also share the full table schema so I can try and recreate this scenario?

Yes, parent_table exist many data. 
Create table select
```sql
SELECT partman.create_parent('dlix.transactions', 'idp_timestamp', 'partman', 'weekly');
```
Schema table dlix.transactions
```sql
                                              Table "dlix.transactions"
     Column      |            Type             | Collation | Nullable |                    Default
-----------------+-----------------------------+-----------+----------+------------------------------------------------
 id              | bigint                      |           | not null | nextval('dlix.transactions_id_seq'::regclass)
 application_id  | integer                     |           | not null |
 cgpn            | character varying(16)       |           | not null |
 cgpn_nai        | smallint                    |           | not null |
 cdpn            | character varying(16)       |           | not null |
 cdpn_nai        | smallint                    |           | not null |
 cgpn_gt         | character varying(16)       |           | not null |
 cdpn_gt         | character varying(16)       |           | not null |
 idp_timestamp   | timestamp without time zone |           | not null |
 event_timestamp | timestamp without time zone |           | not null |
 completed_at    | timestamp without time zone |           |          |
 status          | integer                     |           | not null |
 mcid            | text                        |           | not null |
 destination_id  | integer                     |           | not null |
 upload_id       | integer                     |           |          |
 try_count       | smallint                    |           |          |
 event_id        | bigint                      |           |          |
 cbc_timestamp   | timestamp without time zone |           |          |
Indexes:
    "transactions_pkey" PRIMARY KEY, btree (id)
    "transactions_upload_id" btree (upload_id)
Triggers:
    transactions_part_trig BEFORE INSERT ON dlix.transactions FOR EACH ROW EXECUTE PROCEDURE dlix.transactions_part_trig_func()
```
Count row in dlix.transactions = 51804944 (current)

**Comment by keithf4** [comment]
What is the current max value for the `idp_timestamp` column? I can only recreate this issue if there is already data existing far in the future in the table. Reviewing the code, `create_parent()` always creates the initial set of child tables based on "now". So if you have data that exists far into the future, when you call run_maintenance() without first partitioning that data out, it may be trying to create all the intervening child tables to try and catch up with what the "newest" data is based on time.

If you have existing data, I would highly recommend partitioning that data out first before you start calling the maintenance function. I would also highly recommend upgrading to a more recent major version if you are looking to use partitioning so you can take better advantage of native partitioning.

Another option, if that data far in the future is valid, is to pass a value to `p_start_partition` so the partitions it creates are based on the highest current value of `p_start_partition`. Then you can go back and partition the data out later and call the maintenance function without any issues.

**Comment by sach3000** [comment]
> What is the current max value for the `idp_timestamp` column? I can only recreate this issue if there is already data existing far in the future in the table. Reviewing the code, `create_parent()` always creates the initial set of child tables based on "now". So if you have data that exists far into the future, when you call run_maintenance() without first partitioning that data out, it may be trying to create all the intervening child tables to try and catch up with what the "newest" data is based on time.

**Thx a lot!** 
I reviewed the entire selection on the `idp_timestamp` column and found 1 row with an incorrect date (52217-12-06 10:42:07.000064). Delete her and maintenance worked correctly.
