### ISSUE TITLE
pgsentineil issue

### ISSUE THREAD

**Issue by yuvarajrenukadevi1825** [pgpartman/pg_partman#317]
Can someone help me with below error message?

a302-5111-5202.stm.swissbank.com> ls -tlr
total 72
-rw-------. 1 postgres postgres   118 Oct 30  2019 pgsentinel.control
-rw-------. 1 postgres postgres    40 Oct 30  2019 pgsentinel.conf
-rw-------. 1 postgres postgres 54646 Oct 30  2019 pgsentinel.c
-rw-------. 1 postgres postgres  2152 Oct 30  2019 pgsentinel--1.0b.sql
-rw-------. 1 postgres postgres   514 Oct 30  2019 Makefile
a302-5111-5202.stm.swissbank.com> pwd
/app/pgsentinel/pgsentinel/src
a302-5111-5202.stm.swissbank.com> make
Makefile:19: /usr/pgsql-11/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory
make: *** No rule to make target `/usr/pgsql-11/lib/pgxs/src/makefiles/pgxs.mk'.  Stop.
a302-5111-5202.stm.swissbank.com>

**Comment by keithf4** [comment]
I believe you posted this to the wrong repository. Is this what you're looking for?

https://github.com/pgsentinel/pgsentinel

**Comment by yuvarajrenukadevi1825** [comment]
$ git clone https://github.com/pgsentinel/pgsentinel.git
$ cd pgsentinel/src
$ make
$ sudo make install
$ psql DB -c "CREATE EXTENSION pgsentinel;"

I am getting above error message while runing make .

**Comment by keithf4** [comment]
You are posting this issue to the wrong project. You're looking for this https://github.com/pgsentinel/pgsentinel
