### ISSUE TITLE
support for p_epoch in partition_data_time

### ISSUE THREAD

**Issue by mosen** [pgpartman/pg_partman#318]
Hi All,
I believe that there is no support for epoch columns in the partition_data_time() function.
This issue is for a feature request to add a p_epoch parameter similar to the create_parent() function.

I might end up writing this myself.

**Comment by keithf4** [comment]
The `partition_data_time()` function is made to be run against partition sets that are already configured in pg_partman. I should be using the value of the `epoch` column in the `part_config` table automatically.

What version of pg_partman are you running? There were some bug fixes in recent versions to fix the `partition_data_time()` function and `partition_data_proc()` procedure to work properly with epoch partitioning.  Please see the CHANGELOG - https://raw.githubusercontent.com/pgpartman/pg_partman/master/CHANGELOG.txt

If you're still having issues on the latest version (4.4.0), please let me know and I can investigate.

**Comment by mosen** [comment]
Ahh right, it may be the upstream repo not getting 4.4.0 so I'll have a look at that.
Also, thanks for all these wonderful extensions which are still going strong :)

**Comment by mosen** [comment]
You are correct, GitHub PR #309 in changelog addresses the problem, sorry to waste your time keith.
