### ISSUE TITLE
How does the partition table count the table size

### ISSUE THREAD

**Issue by xu-wenhao** [pgpartman/pg_partman#320]
For tables partitioned by time (year or month or day), how to count the size of the parent table and the child table？
I tried to use the following method, but the result is 0kb ：
`SELECT PG_SIZE_PRETTY(CITUS_TABLE_SIZE('TABLENAME'));`

**Comment by keithf4** [comment]
The only tables that actually contain any data in a partition set are the lowest level tables. So you'd have to get the sizes of all the child tables and then sum that up. I'm not sure how that citus_table_size() function itself works, or if it would be required to use in your case. But for standard postgres, you could do the following (replacing my history table with your own table). the `pg_total_relation_size()` function ensures that indexes are included in the size as well.

`select pg_size_pretty(sum(pg_total_relation_size(inhrelid))) from pg_inherits where inhparent = 'public.history'::regclass;`

**Comment by keithf4** [comment]
If you're using subpartitioning, that would get even trickier since even the sub-parents would be empty. So you'd have to somehow travel all the way down the inheritance tree.

**Comment by xu-wenhao** [comment]
> If you're using subpartitioning, that would get even trickier since even the sub-parents would be empty. So you'd have to somehow travel all the way down the inheritance tree.

Thank you very much for your reply, I refer to your suggestions to make statistics on the size of the partition table, and the size of the partition table can be obtained successfully
