### ISSUE TITLE
Auto partitioning in Postgres12/13 using pg_partman and efcore migrations ? 

### ISSUE THREAD

**Issue by k2ibegin** [pgpartman/pg_partman#323]
Hi,

Is it possible to use my EF Core migrations in .net core APP, to run a script OR raw Sql via pg_partman ? I am a little concerned about manual work to be done for every new installation of microservices we have. So it would be nice to run the partitioning automatically in migrations. 

Also another question I have is if  the only way to auto create partitions in Postgres12 is via pg_partman ? Does postgres12(still)/13(will)  not support this feature natively ? 

Thanks

**Comment by keithf4** [comment]
pg_partman has a built in background worker that can run the maintenance for you right in the database within a given interval of time. Please see the README for how to set it up and configure it.

Or if you want to control the maintenance more precisely, all you need to do is call the `run_maintenance()` function or `run_maintenance_proc()` procedure from your scheduling application. It's no different than calling any other function in postgres. As to the specifics of your app, I don't have any knowledge of it myself.

As of PG13, there still is no built in mechanism that will automatically create the partitions for you. There may be other tools out there besides pg_partman that can do it for you as well, but I'm not aware of any myself.
