### ISSUE TITLE
Q: No custom intervals in native partitioning?

### ISSUE THREAD

**Issue by dtseiler** [pgpartman/pg_partman#324]
Just testing native partitioning and hit this error:

```
ERROR:  Custom intervals are not allowed when moving data out of the DEFAULT partition in a native set. Please leave p_interval/p_batch_interval parameters unset or NULL to allow use of partition set's default partitioning interval.
CONTEXT:  PL/pgSQL function partman.partition_data_time(text,integer,interval,numeric,text,boolean,text) line 91 at RAISE
SQL statement "SELECT partman.partition_data_time ('public.users', p_lock_wait := '0', p_order := 'ASC', p_analyze := false, p_batch_interval := '1 hour')"
PL/pgSQL function partman.partition_data_proc(text,text,integer,integer,text,text,integer,integer,boolean) line 84 at EXECUTE
```

I have a table partitioned daily, and was trying to do the initial data migration in hourly batches. A daily batch would be pretty large and in previous non-native partitioning efforts I would often go hourly or even less. Is this there any alternative here?

**Comment by keithf4** [comment]
Unfortunately that isn't possible with native as far as I've been able to tell. You cannot add a new child table who's constraint would contain any data that currently exists in the default. So, at a minimum, you must move ALL the data that would go into the new child table out of the default before the new child table can be made. 

The old method was nice because it could transparently move the data, only causing sessions to be held if they tried to access the data being moved. There's no way to do that transparently anymore without requiring an entire child's tables data be moved at once. Having it not be transparent just seemed too risky since it could potentially show running queries that data disappears then reappears. Could really screw up an UPSERT statement for example.

**Comment by dtseiler** [comment]
Thanks for the reply. It definitely seems that native partitioning makes it a bit more difficult to partition existing tables "transprently".

**Comment by keithf4** [comment]
I suppose there could be an option added that wouldn't do it transparently. It would still need to move all the data out before it could make the new child table. It would just have to be two sets of batches to move the data out then back in again. It would also have to have a caveat that you could potentially corrupt your table (or application) if you access it during the migration process. But it would at least avoid possibly, huge transactions.

**Comment by dtseiler** [comment]
I'm going to have to run through my partman/pg12 tests again. I'm a little bewildered at these restrctions on PG's end.

Thanks again for the follow-up.

**Comment by dtseiler** [comment]
yeah I see what you mean now with the overlap constraint problem. I'll have to sort out how to partition active tables with existing data. I had been doing a renaming shell game to use the existing table as the default partition so existing apps/queries would still see that data and then I could begin processing it.

**Comment by dtseiler** [comment]
OK just confirmed (for my own simple mind) that I don't want to pre-create partitions that would cover any data in the default.

**Comment by dtseiler** [comment]
Looks like I can set `p_start_partition` to a future time (eg tomorrow) and then run partitioning on existing data that includes today.

This is the test I ran today (2020-09-17):

```
CREATE TABLE users (
  --id    INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id    VARCHAR(36) PRIMARY KEY,
  email VARCHAR(40) NOT NULL UNIQUE,
  created_at    TIMESTAMP NOT NULL
);

-- Use a fake UUID generator here
INSERT INTO users (id, email, created_at)
SELECT
  md5(random()::text || clock_timestamp()::text)::uuid as id,
  'user_' || seq || '@' || (
    CASE (RANDOM() * 2)::INT
      WHEN 0 THEN 'gmail'
      WHEN 1 THEN 'hotmail'
      WHEN 2 THEN 'yahoo'
    END
  ) || '.com' AS email,
  timestamp '2020-07-01 00:00:00' +
       random() * (now() - timestamp '2020-07-01 00:00:00')
FROM GENERATE_SERIES(1, 5000000) seq;

CREATE INDEX users_created_at_idx ON users(created_at);

SELECT date_trunc('day', created_at) as created_day, count(*)
FROM users
GROUP BY created_day
ORDER BY created_day;

VACUUM ANALYZE users;

CREATE TABLE users_part_template
  (LIKE users INCLUDING ALL);

ALTER TABLE users RENAME TO users_source;

CREATE TABLE users
  (LIKE users_part_template INCLUDING DEFAULTS INCLUDING CONSTRAINTS)
PARTITION BY RANGE (created_at);

SELECT partman.create_parent('public.users', 'created_at', 'native', 'daily', p_automatic_maintenance := 'off', p_template_table := 'public.users_part_template', p_debug := true, p_start_partition := '2020-09-18');
DROP TABLE users_default;
ALTER TABLE users_source RENAME TO users_default;
ALTER TABLE users ATTACH PARTITION users_default DEFAULT;
UPDATE partman.part_config SET automatic_maintenance='on' WHERE parent_table='public.users';

CALL partman.partition_data_proc('public.users');
VACUUM ANALYZE users;
VACUUM ANALYZE users_default;
REINDEX TABLE users_default;

SELECT relname, n_live_tup
FROM pg_stat_all_tables
WHERE relname like 'users%'
ORDER BY relname;

UPDATE partman.part_config SET retention = '30 days', retention_keep_table = false where parent_table='public.users';
SELECT partman.run_maintenance('public.users');
```

**Comment by dtseiler** [comment]
One last thing, Keith. If we're on PG12, would you always recommend native partitioning? ie is there a case that comes to mind where you'd still recommend using inheritance?

**Comment by keithf4** [comment]
I honestly cannot think of any specific case that sticks out in my mind. Unless there's some reason you cannot use the template table to manage features that aren't natively supported yet. Or, as you ran into here, you simply cannot migrate an existing table unless you are able to reduce the interval size when moving the data. Even then, you could initially do it with a trigger-based solution then migrate to native once all the data has been move  - https://github.com/pgpartman/pg_partman/blob/master/doc/migrate_to_native.md
