### ISSUE TITLE
Q: Trying to get data into partitions after bgw not running

### ISSUE THREAD

**Issue by dtseiler** [pgpartman/pg_partman#326]
I check in on a new install today and found that the bgw wasn't running. The table is partitioned but there is data in the default partition from all over the month, and the partitions only cover Sep 21-27. I restarted to get the bgw running and then tried to call run_maintenance but got this error, which I suspected I might based on our earlier conversations:

```
ERROR:  updated partition constraint for default partition would be violated by some row
CONTEXT: SQL statement "ALTER TABLE public.foo ATTACH PARTITION public.foo_p2020_09_28 FOR VALUES FROM ('2020-09-28 00:00:00+00') TO ('2020-09-29 00:00:00+00')"
```

Should I call `partition_data_proc()` to move data existing data and have it create new partitions on the fly? That's what I did for my example last time to partition an existing table after only pre-creating future-dated partitions. I just don't want to risk losing any data.

**Comment by keithf4** [comment]
Yes, that is the error you will get if maintenance fails because it cannot make a new child table due to data being in the default. That data either has to be moved out (if it's valid) or deleted. Just be careful it doesn't make a future partition out beyond what current child tables exists. Otherwise you will have a gap until that is fixed as well. Can use `partition_gap_fill()` to fix that.

**Comment by dtseiler** [comment]
Does running `partition_data_proc()` lock the default partition at all?

**Comment by keithf4** [comment]
It does not do any locks on the table itself, but it it does attempt a SELECT FOR UPDATE on the rows that are being moved. 

https://github.com/pgpartman/pg_partman/blob/master/sql/functions/partition_data_time.sql#L231

You can set a lock timeout wait as a parameter to partition_data_*() if you don't want it to wait indefinitely and possibly block other queries for too long

**Comment by dtseiler** [comment]
This is fine, thanks much. I'm testing it now and it looks like it's doing what I expected :)

**Comment by dtseiler** [comment]
So it worked well until it got to today, then it failed with the similar constraint error. I assume because new data is still being inserted. What I think we should do then is pre-create for tomorrow and the next few days and then move today's data tomorrow.

Can we use `create_partition_time()` to do that?

**Comment by dtseiler** [comment]
Hm looks like that function takes an array of timestamps. Are those just the start times for multiple partitions? Looking at the source code it seems so.

**Comment by dtseiler** [comment]
Yes this did the trick:

```
select partman.create_partition_time('public.foo',array['2020-10-01','2020-10-02'],p_debug := true);
```
