### ISSUE TITLE
New Partition Ownership

### ISSUE THREAD

**Issue by dtseiler** [pgpartman/pg_partman#329]
We have a PG12 native partitioned table, with daily partitions. Today we noticed that partitions from Oct 5 forward were all owned by `postgres`, where as the parent table and all partitions prior to Oct 5 were owned by the app user as desired. The new partitions were ones created by the pg_partman background worker.

We found this problem because our schema migration script failed trying to add a column to our partitions due to the ownership issue.

I'm wondering how this is controlled and what I can do to avoid having to manually assign ownership in the future to get these schema scripts to work. I don't see anything in the `part_config` table that would indicate ownership. The DB itself is owned by `postgres` but the tables are typically assigned to application owners in our environments.

**Comment by dtseiler** [comment]
I'm assuming the BGW runs as postgres since we have `pg_partman_bgw.role` defaulted to `postgres`.

Does this suggest that BGW would call `run_maintenance()` as this user for all DBs in the cluster and we should expect new partitions to be owned by that user?

**Comment by keithf4** [comment]
For native partitioning, by default ownership & privileges are not inherited and I believe the ownership is whoever created the child table. I'm not 100% on that, though. I know privileges are specifically not inherited, but not sure on ownership. Either way, all access to the child tables must be done through the parent (except by the owner).

Unless you set the `inherit_privileges` flag in `part_config` to true. Then it should take ownership & privilege information from the parent table.

It's covered in this section of the doc - https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman.md#child-table-property-inheritance

**Comment by dtseiler** [comment]
Thanks, I'll try to set up a couple test cases.

**Comment by dtseiler** [comment]
Trying to force the issue, I set the `premake` value to something higher, with the `pg_partman_bgw.interval` set down to `60` but I haven't seen it do anything yet. I can manually run `run_maintenance()` as the `postgres` user and observe the different ownership but I wanted to have the bgw do it for certain. I've verified that the bgw is running in the ps list and interval is set to 60 in the running instance.

Is there something I'm misunderstanding about how the background worker runs?

```
$ psql -c "show pg_partman_bgw.interval"
 pg_partman_bgw.interval
-------------------------
 60
(1 row)

$ ps -ef | grep partman | grep -v grep
postgres 16650 16643  0 14:45 ?        00:00:00 postgres: 12/main: pg_partman master background worker
```

**Comment by dtseiler** [comment]
I can confirm that setting `inherit_privileges=true` preserves the desired ownership when executing `run_maintenance();` as the `postgres` user, which is promising.

**Comment by dtseiler** [comment]
I understand that direct access to the child tables is usually not needed and so it makes sense to default `inherit_privileges` to `false`. Is there any harm in enabling it though? Just curious. Is it more of a lockdown to save the user from themselves?

I don't expect they'll need to regularly be adding columns or other such structural changes, but just curious.

**Comment by keithf4** [comment]
> Trying to force the issue, I set the `premake` value to something higher, with the `pg_partman_bgw.interval` set down to `60` but I haven't seen it do anything yet. I can manually run `run_maintenance()` as the `postgres` user and observe the different ownership but I wanted to have the bgw do it for certain. I've verified that the bgw is running in the ps list and interval is set to 60 in the running instance.
> 
> Is there something I'm misunderstanding about how the background worker runs?
> 
> ```
> $ psql -c "show pg_partman_bgw.interval"
>  pg_partman_bgw.interval
> -------------------------
>  60
> (1 row)
> 
> $ ps -ef | grep partman | grep -v grep
> postgres 16650 16643  0 14:45 ?        00:00:00 postgres: 12/main: pg_partman master background worker
> ```

Not sure on that one. Increasing premake and then lowering interval should make more child tables the next time it runs.



> I understand that direct access to the child tables is usually not needed and so it makes sense to default `inherit_privileges` to `false`. Is there any harm in enabling it though? Just curious. Is it more of a lockdown to save the user from themselves?
> 
> I don't expect they'll need to regularly be adding columns or other such structural changes, but just curious.

As far as I'm aware, there's no problem with direct child table access if the privileges on the child tables match that of the parent as. There may be some edge case I'm not familiar with, tho. In fact, you can potentially increase performance if your app is aware of the child table naming pattern and can just bypass tuple routing through the parent all together.

**Comment by dtseiler** [comment]
So my VM from last week was started up again and obviously now is behind in partitions (last partition is for Oct 25). The `pg_partman_bgw.interval` is still set to `60` but I haven't seen any activity from the bgw yet.

If the interval is at the default `3600`, is that interval from the time the bgw process started? Or top of the hour?

**Comment by keithf4** [comment]
It's since the bgw process was started. So there's nothing in the logs at all? Maybe try turning the logging level up to DEBUG and see if anything shows up? It does have some debug log entries that should be there even if it maintenance has nothing to do that round.

**Comment by dtseiler** [comment]
D'oh.

`DEBUG:  pg_partman_bgw.dbname GUC is NULL. Nothing to do in main loop.`

**Comment by dtseiler** [comment]
Yeah it works as expected when I remember to set `dbname`. So I can duplicate that case now where the background worker creates the partitions as postgres and so they are owned by postgres. I'll test with `inherit_privileges` set to true next and try again.

**Comment by dtseiler** [comment]
Confirmed setting `inherit_privileges = true` will have background worker maintain ownership from parent table to child partition.
