### ISSUE TITLE
run_maintenance is not dropping the old id based partitions

### ISSUE THREAD

**Issue by rajkumarvenkatasamy** [pgpartman/pg_partman#331]
**Environment:** 

OS - CentOS Linux release 7.8.2003 (Core)
Postgres Version - 12.2

**Issue Description:**

Created an **ID based partition table** as below:

```
CREATE TABLE second_events (
  id bigint,
  name text,
  year integer
) partition by range (year);
```

```
SELECT partman.create_parent(
p_parent_table := 'public.second_events', 
p_control := 'year', 
p_type := 'native', 
p_interval := '1', 
p_premake := 7, 
p_automatic_maintenance  := 'on', 
p_start_partition  := '2013'
);
```

Partitioned table got created as expected and as shown below:

![image](https://user-images.githubusercontent.com/6541019/98547904-dbb2f080-22be-11eb-8949-0341f92ef4ce.png)

**Updated the retention period in part_config** using the below command
`
update partman.part_config set retention = '4', retention_keep_table = False, retention_keep_index = False where parent_table = 'public.second_events';
`

Then, executed **run_maintenance** using the below command

`
select partman.run_maintenance(p_debug := true);
`

 to see if the old partitions (2020 - 4) = any partitions older than 2016 gets dropped. But it didn't and all the partitions as shown in the above screenshot remains / exists.

Is this a bug or am I doing anything wrong in here ?

**Comment by keithf4** [comment]
Do you have any data at all in the partition set? Brief glance at retention, it looks like it may not work if the partition set it empty. However, it's never going to make any new child tables either if there's no data with id-based partitioning.

**Comment by rajkumarvenkatasamy** [comment]
> Do you have any data at all in the partition set? Brief glance at retention, it looks like it may not work if the partition set it empty. However, it's never going to make any new child tables either if there's no data with id-based partitioning.

Hi @keithf4 

Thanks for your reply. 
Yes, there was no data earlier. After your feedback, I tried inserting some dummy records for testing using the below statements:

```
insert into second_events (id, name, year ) values (1, 'A', 2012);
insert into second_events (id, name, year ) values (1, 'A', 2013);
insert into second_events (id, name, year ) values (1, 'A', 2014);
insert into second_events (id, name, year ) values (1, 'A', 2015);
insert into second_events (id, name, year ) values (1, 'A', 2016);
insert into second_events (id, name, year ) values (1, 'A', 2017);
insert into second_events (id, name, year ) values (1, 'A', 2018);
insert into second_events (id, name, year ) values (1, 'A', 2019);
insert into second_events (id, name, year ) values (1, 'A', 2020);
```

Then tried calling the run_maintenance function. I could see new partitioned tables had got created based on the configured premake value : 7 (max inserted value in year field is 2020 based on the above inserts and hence I think pg_partman created new partitions up until 2027 : 2020 + 7). So this is ok.

**However the retention configuration is 4**, but I see the **older partitioned tables of 2013 and 2014 got dropped** as shown in below screenshot, where you don't see now the partitioned table for the year 2013 and 2014. I don't quite understand on what basis those two partitions alone was picked up for drop operation ? **Could you please clarify how the retention computation works**, because the doc says : max(id) - retention config is chosen as the candidate for drop operation, in that case, my interpretation of that is 2020 - 4 = 2016, **so any partitions older than 2016 should be dropped ?**

![image](https://user-images.githubusercontent.com/6541019/98629608-3ee46780-233f-11eb-9aea-2d9f4afbf49c.png)

**Note:** It would be better if this particular case around retention will not work when the partition set is empty, is explicitly mentioned in the retention section of the document.

Thanks again!!!

**Comment by keithf4** [comment]
I'll have to investigate this. I think it may have something to do with your low interval. Typically for a single value partitioned child you would do list partitioning, not ranged. But pg_partman only supports ranged. And it only supports ID partitioning intervals lower than 10 for native partitioning as well because the math for doing trigger-based partitioning on low ranges can get a little weird.

**Comment by rajkumarvenkatasamy** [comment]
> I'll have to investigate this. I think it may have something to do with your low interval. Typically for a single value partitioned child you would do list partitioning, not ranged. But pg_partman only supports ranged. And it only supports ID partitioning intervals lower than 10 for native partitioning as well because the math for doing trigger-based partitioning on low ranges can get a little weird.

Hi @keithf4 

Please ignore my above observation on drop partition not working as expected. 
It seems, I have changed the retention config value, during the subsequent round of testing to 5 and hence pg_partman has dropped (2020 - 5 = 2015) partitions older than 2015. Now, I retried with different retention config value and it drops the older partition as expected. 

Happy to close this issue. 

**Summary / Outcome**

In case of ID based partitioning, Partition set / partitioned table should have data in it for pg_partman's run_maintenance call to work as expected. This is something which I got to know by creating this issue.

Thanks again for your help!!!
