### ISSUE TITLE
Maintenance didn't create new partitions, now I can't create them since data is in default

### ISSUE THREAD

**Issue by dtseiler** [pgpartman/pg_partman#332]
I pre-created a partitioned table early last week but it wasn't used until today. However because it was empty, apparently pg_partman maintenance worker didn't create any new partitions. This means that all the data is being dumped into the default partition. However now that the data is there and the app is running, I can't run `run_maintenance()` due to the constraint violation.

Is there a way forward that doesn't involve moving the data out and back in? Could I manually pre-create partitions for the next few days and then after today move today's data out and back in?

**Comment by keithf4** [comment]
We'd discussed a bit on slack how to solve this by just running the partition data procedure once that time period of data insertion has passed.

To help prevent this again, I highly recommend setting your pre-make value high enough to account for larger gaps in time like this when data may not be entered.

**Comment by dtseiler** [comment]
Would it make sense to set `infinite_time_partitions=true` in the case of daily partitions as a matter of course?

**Comment by keithf4** [comment]
That could also help as well if you expect there to be large gaps in data insertion time, yes.

**Comment by dtseiler** [comment]
Typically I don't expect it but there was just the gap between table setup and application startup that bit me. I'll be sure to take that into consideration going forward with daily partitions.

**Comment by kayvonr** [comment]
@dtseiler in case it's helpful, i had a similar issue a while back that keith gave some very helpful pointers on: https://github.com/pgpartman/pg_partman/issues/110
