### ISSUE TITLE
Broken doc link in README.md

### ISSUE THREAD

**Issue by adrianlzt** [pgpartman/pg_partman#335]
https://github.com/pgpartman/pg_partman/blame/master/README.md#L84

``[pg_partman_howto.md file](doc/pg_partman_howto.md)`` does not longer exists.

**Comment by basaran** [comment]
There are two files now

`https://github.com/pgpartman/pg_partman/blob/master/doc/`

**Comment by keithf4** [comment]
Fixed the links. Thanks for letting me know!
