### ISSUE TITLE
How to specify the exact execution time of run_maintenance procedure in pg_partman?

### ISSUE THREAD

**Issue by rajkumarvenkatasamy** [pgpartman/pg_partman#337]
Is it possible to specify the exact execution time of run_maintenance procedure in pg_partman? 

I know there is pg_partman_bgw.interval parameter to specify the time interval between each maintenance run, but the question is, is it possible to specify the start time of the maintenance run ? Please clarify.

Thanks!!!

**Comment by keithf4** [comment]
Using the built in background worker, no, that can only work off of an interval.

If you need to schedule a specific time, you will have to use another scheduling tool like regular cron or pg_cron
