### ISSUE TITLE
Create Extension Language Error

### ISSUE THREAD

**Issue by JGovreau** [pgpartman/pg_partman#338]
After running the make install on the pg_partman 4.0.0 package successfully, I'm having issues getting the extension created due to a Language error. This is on PG 10.14.23.

```
=# create extension pg_partman schema partman;
ERROR:  syntax error at or near "LANGUAGE"

=# \dL
                      List of languages
  Name   |  Owner   | Trusted |         Description
---------+----------+---------+------------------------------
 edbspl  | postgres | t       | EDB-SPL procedural language
 plpgsql | postgres | t       | PL/pgSQL procedural language
(2 rows)
```

Any ideas on what could be causing this?

**Comment by JGovreau** [comment]
Output of the make install:

`# make install
/bin/mkdir -p '/usr/edb/as10/share/extension'
/bin/mkdir -p '/usr/edb/as10/share/extension'
/bin/mkdir -p '/usr/edb/as10/lib'
/bin/mkdir -p '/usr/edb/as10/doc/extension'
/bin/mkdir -p '/usr/edb/as10/bin'
/usr/bin/install -c -m 644 .//pg_partman.control '/usr/edb/as10/share/extension/'
/usr/bin/install -c -m 644 .//updates/pg_partman--1.5.1--1.6.0.sql .//updates/pg_partman--2.6.1--2.6.2.sql .//updates/pg_partman--0.4.2--1.0.0.sql .//updates/pg_partman--0.1.2--0.2.0.sql .//updates/pg_partman--1.8.5--1.8.6.sql .//updates/pg_partman--2.6.0--2.6.1.sql .//updates/pg_partman--2.5.0--2.5.1.sql .//updates/pg_partman--2.3.2--2.3.3.sql .//updates/pg_partman--3.0.1--3.0.2.sql .//updates/pg_partman--2.2.1--2.2.2.sql .//updates/pg_partman--1.8.7--2.0.0.sql .//updates/pg_partman--2.2.3--2.3.0.sql .//updates/pg_partman--1.8.0--1.8.1.sql .//updates/pg_partman--1.8.2--1.8.3.sql .//updates/pg_partman--2.2.0--2.2.1.sql .//updates/pg_partman--1.3.0--1.4.0.sql .//updates/pg_partman--2.3.1--2.3.2.sql .//updates/pg_partman--1.8.1--1.8.2.sql .//updates/pg_partman--1.6.0--1.6.1.sql .//updates/pg_partman--1.1.0--1.2.0.sql .//updates/pg_partman--1.8.4--1.8.5.sql .//updates/pg_partman--2.4.1--2.5.0.sql .//updates/pg_partman--2.3.0--2.3.1.sql .//updates/pg_partman--1.8.6--1.8.7.sql .//updates/pg_partman--2.0.0--2.1.0.sql .//updates/pg_partman--1.4.0--1.4.1.sql .//updates/pg_partman--0.2.0--0.3.0.sql .//updates/pg_partman--3.2.0--3.2.1.sql .//updates/pg_partman--1.7.1--1.7.2.sql .//updates/pg_partman--0.1.0--0.1.1.sql .//updates/pg_partman--2.3.4--2.4.0.sql .//updates/pg_partman--1.4.3--1.4.4.sql .//updates/pg_partman--1.4.5--1.5.0.sql .//updates/pg_partman--3.0.2--3.1.0.sql .//updates/pg_partman--2.1.0--2.2.0.sql .//updates/pg_partman--1.6.1--1.7.0.sql .//updates/pg_partman--2.6.3--2.6.4.sql .//updates/pg_partman--1.4.4--1.4.5.sql .//updates/pg_partman--3.0.0--3.0.1.sql .//updates/pg_partman--1.8.7--1.8.8.sql .//updates/pg_partman--2.4.0--2.4.1.sql .//updates/pg_partman--1.7.2--1.8.0.sql .//updates/pg_partman--3.1.2--3.1.3.sql .//updates/pg_partman--0.4.1--0.4.2.sql .//updates/pg_partman--0.3.2--0.4.0.sql .//updates/pg_partman--3.2.1--4.0.0.sql .//updates/pg_partman--3.1.1--3.1.2.sql .//updates/pg_partman--0.1.1--0.1.2.sql .//updates/pg_partman--1.7.0--1.7.1.sql .//updates/pg_partman--0.4.0--0.4.1.sql .//updates/pg_partman--1.4.2--1.4.3.sql .//updates/pg_partman--1.0.0--1.1.0.sql .//updates/pg_partman--2.3.3--2.3.4.sql .//updates/pg_partman--0.3.0--0.3.1.sql .//updates/pg_partman--1.8.8--2.0.0.sql .//updates/pg_partman--2.5.1--2.6.0.sql .//updates/pg_partman--3.1.0--3.1.1.sql .//updates/pg_partman--2.6.2--2.6.3.sql .//updates/pg_partman--2.6.4--3.0.0.sql .//updates/pg_partman--1.5.0--1.5.1.sql .//updates/pg_partman--1.4.1--1.4.2.sql .//updates/pg_partman--0.3.1--0.3.2.sql .//updates/pg_partman--1.8.3--1.8.4.sql .//updates/pg_partman--3.1.3--3.2.0.sql .//updates/pg_partman--2.2.2--2.2.3.sql .//updates/pg_partman--1.2.0--1.3.0.sql .//sql/pg_partman--4.0.0.sql  '/usr/edb/as10/share/extension/'
/usr/bin/install -c -m 755  src/pg_partman_bgw.so '/usr/edb/as10/lib/'
/usr/bin/install -c -m 644 .//doc/pg_partman.md .//doc/migration_to_partman.md .//doc/pg_partman_howto.md '/usr/edb/as10/doc/extension/'
/usr/bin/install -c -m 755 .//bin/common/*.py .//bin/pg10/*.py '/usr/edb/as10/bin/'`

**Comment by keithf4** [comment]
Version 4.0.0 is quite old and may contain some syntax errors. The latest version of pg_partman is 4.4.1. Please try that version. 

I would also highly, highly recommend upgrading to at least PostgreSQL 11 if you're just getting started with partitioning. Go straight to 12 if you can. There have been drastic improvements with managing partitions and you'll have to do quite a bit of work updating how pg_partman manages things if you start with 10 then upgrade to 11+ later.

**Comment by JGovreau** [comment]
Thanks Keith - I was able to get it to work with the latest 4.4.1 package. We're looking to upgrade to PG12 soon, just doing some initial testing in the meantime to get an idea of how the tool can be used.
