### ISSUE TITLE
Table Template not Copying Triggers

### ISSUE THREAD

**Issue by brystearns** [pgpartman/pg_partman#340]
I am attempting to partition a table, and have a template table that all the partitions will copy. This template has both indexes and a trigger. However, when I create a new partition from this template table, it copies the indexes, but not the trigger. Is this by design, or is there a solution to get the triggers copied as well. The code is:

`create_parent('parent_table', 'startDate', 'native', 'quarterly', p_template_table := 'template_table');`

**Comment by keithf4** [comment]
Triggers are not one of the objects supported via the template table. I have a table here that lists what the template table can be used for. Keep in mind that this varies by the version of PostgreSQL itself as I migrated items away from the template table as native supported them

https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman.md#child-table-property-inheritance

I believe more recent versions of PG support trigger inheritance directly from the parent table. I'm not sure off the top of my head which version and what restrictions on that support exist. 

I had tried to do trigger support with pg_partman, but it was a bit too complex for my skill. If native does not support what you need at the moment, it should in the future as I do know that is something they are actively working on.

**Comment by jains99** [comment]
What is the status with latest versions?
