### ISSUE TITLE
Unable to upgrade extension from 4.4.0 to 4.4.1

### ISSUE THREAD

**Issue by bleukert** [pgpartman/pg_partman#342]
Trying to upgrade the pg_partman extension from 4.4.0 to 4.4.1 in a PostgreSQL 10.16 database with the SQL statement "ALTER EXTENSION pg_partman UPDATE TO '4.4.1';" returns "ERROR:  syntax error at or near "PROCEDURE"".

Any idea how to fix this issues?

**Comment by keithf4** [comment]
Apologies for that. I forgot to put the version check for updating procedures into that update. I'll try and get a fix for that out in the near future.

**Comment by keithf4** [comment]
I do have a fix for this coming in the next version. In the mean time, if you need to install this update, you can remove the last section of the `pg_partman--4.4.0--4.4.1.sql` file that recreates the `undo_partition_proc` procedure.

**Comment by bleukert** [comment]
Thanks for fixing the issue and providing a workaround. With the workaround implemented I was able to update the extension without any errors.

**Comment by keithf4** [comment]
Glad to hear. Just be aware that if you upgrade to PG11 or later, the procedures in pg_partman will not be available without a re-install of the extension. I'm working to see about providing a method to get them added back in without losing the configuration information that would occur with a re-install.
