### ISSUE TITLE
Create migration process to add procedures to an existing, upgraded install (enhance dump config function)

### ISSUE THREAD

**Issue by keithf4** [pgpartman/pg_partman#343]
If pg_partman was installed prior to PG11, the procedures were not installed. If PG is later upgraded to PG11, they will not automatically be installed unless one happens to be updated.

Create a process to add procedures to an already existing installation.

**Comment by keithf4** [comment]
This would probably be best handled by enhancing the `dump_partitioned_table_definition()` function to have an alternate output option of creating INSERT statements for the config table vs `create_parent()` calls. Also add support for the `part_config_sub` table.

**Comment by keithf4** [comment]
Alternative solution:

A shell script that concatenates the PROCEDURE files to a single .sql file, followed by commands to add the procedures as member objects of the extension. See if script can figure out schema that extension is installed to. Otherwise script takes an argument for what schema the extension is installed in

**Comment by sumedhpathak** [comment]
Hi Keith, we (Citus/Microsoft) are running into this issue. We have some older versions of pg_partman installed on PG10, and alter-extension-update is complaining that certain procs don't exist. How do you recommend we fix this? 
The Changelog mentioned scripts will be provided, but AFAICS nothing exists. 
Thanks!

**Comment by keithf4** [comment]
Sorry I haven't had a chance to dive into this yet. Can see the two methods I was looking at above. 

The easier one in the mean time would be if you can back up the current contents of the `part_config` and `part_config_sub` tables, uninstall the extension, reinstall it then add those rows back in. 

If you're using native partitioning, this shouldn't cause any issues that I'm aware of with partition table usage.

However, if you are using trigger-based partitioning, this likely will break those partition sets since the trigger functions are calling functions that are part of the extension.

**Comment by keithf4** [comment]
Document to fix missing procedures has been added in 4.7.0

https://github.com/pgpartman/pg_partman/blob/master/doc/fix_missing_procedures.md
