### ISSUE TITLE
Feature Request/Question - support for other Timestamp types?

### ISSUE THREAD

**Issue by grayeul** [pgpartman/pg_partman#350]
I have been playing around with pg_partman some, and like what it is able to do for me.  However, I have a number of tables where I am using the timestamp9 extension from here: https://github.com/fvannee/timestamp9  which very conveniently gives me nanosecond resolution for time (yes, I do need that in my application).  I had originally modified my table definition to have an additional timestamp field (not hi-precision) just so I could partition it with pg_partman.  The timestamp9 is cast-able to a regular timestamp, so I was disappointed it didn't just work.  But then I looked into the code some, and thought I had an easy fix.  I tried changing the check_control_type() method, which was rejecting attempts to use timestamp9 because it was not in a fixed list.  I added timestamp9 to that list so that it would let me call create_parent() with no error -- and I thought I was good!

Then I realized that run_maintenance() is failing.... It complains ` ERROR:  function max(public.timestamp9) does not exist`.  I'm a little confused by that because I can run max() on those columns in my table with no problem.  And \df shows a max function of type aggregate seems to exist.  I tried digging around to see what else might be needed -- but no luck.

I'm hoping there would be an easy fix to this, if I just knew where to sneak it in.  I even tried defining the column to partition on as:  `my_time_name::timestamptz`  but not surprisingly that didn't work.

Any options/advice?

**Comment by keithf4** [comment]
While it would be nice to be able to support third-party data types like this, it would be hard for me to maintain that at this time unless there was a large demand for it. 

However, this is an open source project, so I have no issues with you maintaining a fork to support this data type. No issues with you publishing that fork for others to use as well to help maintain it. Depending how that goes and the demand for its usage, I could then possibly see about incorporating it.

Do you have the timestamp9 datatype installed in a schema other than public? If so, that schema may be in your search_path when you run things yourself, but not in the search_path of the role running maintenance. I would highly recommend putting a data type extension in a schema that is visible to all roles by default if any role is going to need to be able to use it.

**Comment by grayeul** [comment]
I understand.  Then, consider this more of a question than request.  Right now I'm trying to understand why it isn't working, and what would need to be changed.  When I check data types with \dT  -- I see timestamp9 and it shows in the public schema.  When I do \df max*  I can see:
```
                                  List of functions
   Schema   | Name |      Result data type       |     Argument data types     | Type 
------------+------+-----------------------------+-----------------------------+------
public     | max  | timestamp9                  | timestamp9                  | agg
```
And yet in my postgres logs I still see:
```
ERROR:  function max(public.timestamp9) does not exist
```
Any other thoughts on things I can check?  The line throwing the error (in run_maintenance) is:
```
 EXECUTE format('SELECT max(%s) FROM ONLY %I.%I', v_partition_expression, v_par
ent_schema, v_default_tablename) INTO v_max_time_default;
```

**Comment by keithf4** [comment]
Check the code that is generating the `v_partition_expression` variable since that's the value going into the `max()` function.

**Comment by grayeul** [comment]
Hmm.. the v_partition_expression seems to be coming from v_control, which is set to the column name I'm partitioning on, and is type timestamp9.  Trying to look at the flow, the partition_expression is either '%I'  or 'NEW.%I'  (I'm not sure which is in play at the point of the error).  The only time it isn't basically a copy of v_control is if v_epoch is seconds or milliseconds.  v_epoch seems to be set to none (is that expected), but my partition_interval is '1 day'

**Comment by grayeul** [comment]
It looks like the search_path is being set to specifically:  '@extschema@,pg_temp' -- which ends up excluding public (I assume).  I've set up all of the tables, etc in the 'partman' schema, which is I think what was recommended.  I'm not sure how it is finding/figuring out that the timestamp9 type exists in public (as shows up in the error msg).  I thought I had it fixed when I moved my timestamp9 definition to be in the partman schema.... but it just moved the problem.  Then it seems like it cannot find the 'max' function without specifying specifically partman.max('2021-04-07'::partman.timestamp9);   So there is definitely something going on with the search_path, and where is the right place to put this custom timestamp definition.  When it is in public (where I had it originally) then I think the run_maintenance() was still not finding the 'max' function, since public was removed from the search_path, and I guess it was just finding the standard max functions from pg_catalog.

**Comment by keithf4** [comment]
So you don't have to install your partitioned tables nor the timestamp9 extension in the partman schema. I just had a recommendation to install the pg_partman extension itself in the `partman` schema.

If you've removed public from the default search path, that could definitely cause issues like this if you didn't also add the necessary search paths to all users that will then need to use any objects in any schemas you are not specifically schema qualifying. There's nothing wrong with removing public and people often do that for security concerns. It's just you then have to make sure you handle search paths properly for anyone that may use objects without schema qualifying them. This is especially important for things like data types and operators which are rarely ever schema qualified.

This is why I recommended ensuring that whichever schema you installed timestamp9 to is in the search path for all users that will be making use of that data type. Including the user that is running pg_partman maintenance.

**Comment by keithf4** [comment]
Actually, I see what you mean how the run_maintenance function is resetting the search path. If you alter the run_maintenance function's resetting of the search path to include `public` does that fix it?

**Comment by keithf4** [comment]
Also, since this seems to be trying to use the same function name as a pretty standard function (`max`), unless you actually change your search_path to force pg_catalog to be last, it is always assumed to be first before any custom paths are given 

https://www.postgresql.org/docs/current/ddl-schemas.html#DDL-SCHEMAS-CATALOG

`In addition to public and user-created schemas, each database contains a pg_catalog schema, which contains the system tables and all the built-in data types, functions, and operators. pg_catalog is always effectively part of the search path. If it is not named explicitly in the path then it is implicitly searched before searching the path's schemas. This ensures that built-in names will always be findable. However, you can explicitly place pg_catalog at the end of your search path if you prefer to have user-defined names override built-in names.`

I believe this means that the custom `max(timestamp9)` function must essentially always be schema qualified no matter what or you have to change your search path to force `pg_catalog` to be last.

**Comment by grayeul** [comment]
I made the change you suggested -- where run_maintenance() was setting a new search_path (two places I think) -- I just modified your pg_temp references to be public,pg_temp.  That seemed to work when running by hand from pgsql!  So -- I think that might do it.  It should run automatically again (as a background_worker task) in about 20 minutes... I don't know how to force/change that schedule -- so I'm going to just let time tick by to make sure that works in that mode... but I think it should, since it seemed to work manually now.

I think it doesn't need pg_catalog last, because it won't find the 'max' with the right argument type in pg_catalog at all -- that is why it was complaining before.  I do understand the desire to not necessarily pull in public for everything... but not sure what the best way is around that, yet.  I was originally thinking that you might could accept other types if they could be cast into a regular timestamp... then if all the run_maintenance() code just tried to do that explicitly on the v_control field (at least when 'time' is the selected type) -- that might work for a variety of other types, and avoid the problem -- but I didn't try that yet.

**Comment by keithf4** [comment]
Ahh yeah you're right, the signature would skip over the catalog version.

I'll see about adding `public` into my rewritten search path. If I put it last, I don't think that would actually be a problem. I think that would solve your problem then?

**Comment by grayeul** [comment]
Yes -- I think that would do it, thanks!  I wasn't entirely sure what gets inherited/put into the pg_temp local schema by default.
ah -- bummer.  I just checked my 'background_task' which I let run on different tables, ones that actually had data in them.  I'm getting an error there that I need to track down/resolve:

**Comment by keithf4** [comment]
It's trying to add a new partition whose constraint matches data that exists in the default. You'll need to move that data out or delete it. You can use the `partition_data_*()` function or procedure to move it and it will create the necessary child table.

**Comment by keithf4** [comment]
So I have a test branch up for the next version that should allow much better custom search path handling. Not only adds "public" into the custom search path changes, but the entire value of the search_path that exists at the time pg_partman is run. If you'd like to test this out the branch is below. 

Do not install this to a production system yet as there could still be additional changes coming in the next release.

https://github.com/pgpartman/pg_partman/tree/4.6.1

**Comment by keithf4** [comment]
Version 4.6.1 has been released. Apologies for the delay on this. I've improved overall search_path handling so any existing search_path that you have set should be accounted for and work as expected.
