### ISSUE TITLE
Pre-Create Past Partitions for Bulk Loading

### ISSUE THREAD

**Issue by GabeBigBoxVR** [pgpartman/pg_partman#352]
I'm bulk loading approximately 500GB of data into a new table and would like to pre-create partitions for data that occurred in the past.  I've been searching the documentation but haven't been able to find anything to do this.

Ideally there would be a function I could call: 

`CALL create_partitions('2018-01-01', '2020-01-01', 'table_name')`

Is there any solution like this?

What I've been doing has been to:
```
1. Insert data into the table, all data goes to default table.
2. Run CALL partman.partition_data_proc('table_name') to move data and create partitions
3. Run `VACUUM analyze`
```

**Comment by keithf4** [comment]
If you're doing this when you're initially creating the partition set, you could set the `p_start_partition` to a point in time far in the past and set the `premake` value high enough to make all the partitions you need. Note that a high number of child tables could take a little while depending on your interval. You can then update the `part_config` table to set the `premake` value down to your normally expected value.

If you're looking to do this after the partition set is already made, that isn't currently supported but a really good idea. I marked this as a feature request so I don't forget, but I don't have an ETA on when that will be. Or if you'd like to work on a patch, I'd be happy to review it.

In the mean time, you could write some SQL to generate the SQL statements for you for the relevant child tables, just ensuring they're following the naming format that pg_partman expects. See my migration documents for examples on generating ALTER TABLE statements dynamically - https://github.com/pgpartman/pg_partman/blob/master/doc/migrate_to_native.md

**Comment by GabeBigBoxVR** [comment]
Ok, that's a great idea.
We're setting this up for benchmarking purposes to see what partition size makes the most sense for our data and then continuing after that.

Once we start the final copy over, we'll definitely use this.

Thanks!
