### ISSUE TITLE
Feature Request - Add partition CHECK constraint with native partitioning

### ISSUE THREAD

**Issue by Cesarla** [pgpartman/pg_partman#354]
Partman does not create CHECK constraints that matches the partitions constraints when using native partitioning.

Relaying only on the partition constraint works well at runtime, but it is inconvenient when reattaching a partition, since the partition constraint will be removed while detaching, so I will be forced to create an invalid constraint to bypass Postgres sequential scan, and then, I will have to validate the constraint.

Currently I am adding the constraints though event-triggers, but I would appreciate if partman cover this scenario out of the box.

**Comment by keithf4** [comment]
Part of the entire reason for native partitioning was to get away from using check constraints, especially with partition pruning features of 11+. The latter is tremendously more efficient. Having both means that it's likely every write to the table would have to check both the native partitioning constraint as well as the new one, impacting performance needlessly. If that can be disproven, I may consider it, but until then this isn't likely going to be a feature that will be added.

If you can give the use-case where you are regularly having to attach and re-attach partitions so often, maybe there's a better solution.

**Comment by keithf4** [comment]
Please feel free to re-open this issue if you are able to provide your use-case where you think this feature is needed.
