### ISSUE TITLE
Question: Is default partition necessary?

### ISSUE THREAD

**Issue by take-five** [pgpartman/pg_partman#359]
Hello

Recently we faced a problem with default partitions and **pg_partman** maintenance (we use native partitioning, PostgreSQL 12).

According to [PostgreSQL documentation](https://www.postgresql.org/docs/13/sql-altertable.html#SQL-ALTERTABLE-ATTACH-PARTITION):
>   Attaching a partition acquires a `SHARE UPDATE EXCLUSIVE` lock on the parent table, in addition to `ACCESS EXCLUSIVE` locks on the table to be attached and on the default partition (if any).

The problem occurred when **pg_partman** maintenance coincided with a long-running analytics SELECT query that scanned all partitions (including the default one).

The SELECT query was something like this:
```
SELECT * FROM partitioned_table
```
(Yes, this shouldn't have been run in the first place, but normally it wouldn't be as disastrous - just increased I/O for a short period of time)

The partitioned table is quite big, so the SELECT query takes quite some time (10+ minutes) to complete.
Somewhere in the middle of this query **pg_partman** maintenance routine was called by Cron. **pg_partman** decided to create a new future partition in that table, but it could not acquire ACCESS EXCLUSIVE lock on the default partition, because SELECT query was holding `ACCESS SHARE` lock. **pg_partman** maintenance query `CALL partman.run_maintenance_proc()` was put into lock wait queue and so were all the subsequent queries that somehow needed access to the default partition.

Granted, we've caused this incident ourselves and **pg_partman** is not to blame:
1. Poorly constructed queries that unintentionally scanned default partition.
2. The lack of `lock_timeout` setting for **pg_partman** routine.
3. The uncontrolled SELECT query which was run by an unsuspicious employee.

We will, of course, address these issues ourselves. 

However, I'd like to understand - is it vital for tables managed by **pg_partman** to have default partitions? The necessity for `ACCESS EXCLUSIVE` lock when attaching partitions can be quite surprising if you didn't study `CREATE TABLE ... ATTACH PARTITION` documentation carefully :)

Best regards

**Comment by take-five** [comment]
Thanks a lot, it is clear now.
I'd like to suggest to mention that default partitions can lead to unexpected outages if not dealt with carefully, but that is totally up to you.

Thank you for the great tool!

**Comment by keithf4** [comment]
Appreciate the suggestion. I'll see if there's anything I can add. I did try and cover that it's important to make sure data isn't left in the default in my howto documentation. And it's also really important to include WHERE conditions when querying the partition sets, otherwise there's not much point in partitioning in the first place.

Thank you!
