### ISSUE TITLE
Question: dropping uninherited partitions manually after running maintenace

### ISSUE THREAD

**Issue by jorenvandeweyer** [pgpartman/pg_partman#361]
I looked through the documentation and I was wondering if there was a function or other way to retrieve uninherited tables when retention is turned on when `retention_keep_table` is true. I want to drop them manually after I dumped the partitions to S3.

## 

I think I am looking for a function which would work like `partman.show_partitions('public.point')` but instead of showing all table partitions, it would show the tables that are uninherited.

| show_partitions                     |
|-------------------------------------|
| (public,point_p2021_04) |
| (public,point_p2021_05) |

| show_uninherited_partitions                     |
|-------------------------------------|
| (public,point_p2021_02) |
| (public,point_p2021_03) |

Does anyone know which function or SQL I could use to accomplish this?

## My setup:

| parent_table     | control   | partition_type | partition_interval | constraint_cols | premake | optimize_trigger | optimize_constraint | epoch | inherit_fk | retention | retention_schema | retention_keep_table | retention_keep_index | infinite_time_partitions | datetime_string | automatic_maintenance | jobmon | sub_partition_set_full | undo_in_progress | trigger_exception_handling | upsert | trigger_return_null | template_table            | publications | inherit_privileges | constraint_valid | subscription_refresh |
|------------------|-----------|----------------|--------------------|-----------------|---------|------------------|---------------------|-------|------------|-----------|------------------|----------------------|----------------------|--------------------------|-----------------|-----------------------|--------|------------------------|------------------|----------------------------|--------|---------------------|---------------------------|--------------|--------------------|------------------|----------------------|
| public.point | createdAt | native         | 1 mon              |                 |       2 |                4 |                  30 | none  | t          |           |                  | t                    | t                    | f                        | YYYY_MM         | on                    | t      | f                      | f                | f                          |        | t                   | public.point_template |              | f                  | t                |                      |

| sub_parent       | sub_partition_type | sub_control | sub_partition_interval | sub_constraint_cols | sub_premake | sub_optimize_trigger | sub_optimize_constraint | sub_epoch | sub_inherit_fk | sub_retention | sub_retention_schema | sub_retention_keep_table | sub_retention_keep_index | sub_infinite_time_partitions | sub_automatic_maintenance | sub_jobmon | sub_trigger_exception_handling | sub_upsert | sub_trigger_return_null | sub_template_table        | sub_inherit_privileges | sub_constraint_valid | sub_subscription_refresh |
|------------------|--------------------|-------------|------------------------|---------------------|-------------|----------------------|-------------------------|-----------|----------------|---------------|----------------------|--------------------------|--------------------------|------------------------------|---------------------------|------------|--------------------------------|------------|-------------------------|---------------------------|------------------------|----------------------|--------------------------|
| public.point | native             | userId       | 1000                   |                     |           2 |                    4 |                      30 | none      | t              |               |                      | t                        | t                        | f                            | on                        | t          | f                              |            | t                       | public.point_template | f                      | t                    |                          |

```
point
point_default
point_p2019_05
point_p2019_05_default
point_p2019_05_p0
point_p2019_05_p1000
point_p2019_05_p2000
point_p2019_06
point_p2019_06_default
point_p2019_06_p0
point_p2019_06_p1000
point_p2019_06_p2000
...
point_p2021_05
point_p2021_05_default
point_p2021_05_p0
point_p2021_05_p1000
point_p2021_05_p2000
...
```

**Comment by keithf4** [comment]
There is nothing like that in pg_partman currently. The way `show_partitions` works is by looking at the catalog tables to see which tables are part of the inheritance tree. When you uninherit them, there is nothing tying those tables together anymore in any sort of relationship. Such a function would have to rely entirely on the naming pattern of the child tables to find them. And while pg_partman does have a predictable naming pattern for the most part, it still wouldn't exactly be trivial to manage something like this vs simply looking up the inheritance tree.

What process are you using to dump them to S3? Couldn't you have that process drop the table after the dump was successful? That's what the `dump_partition.py` script that pg_partman comes with does. That works by using the feature of pg_partman retention to move old tables to a different schema and then dumping out everything that exists in that schema.

**Comment by jorenvandeweyer** [comment]
Thanks for the clarification!

At the moment I have no retention enabled and I'm not actually dumping anything to S3 yet. 

So if I'm understanding you correctly, the process go as the following:
1. Configure retention to move old partitions to a dedicated schema
2. Dump any new table that appears in this schema to S3 by modifying the `dump_partition.py` file
3. On a successful S3 dump, drop the table

**Comment by keithf4** [comment]
Yes those steps you have listed should work. Just note that that script is set to drop the tables by default on a successful dump.
