### ISSUE TITLE
Question: How to apply 'daily' partition to an integer column?

### ISSUE THREAD

**Issue by lihaostar** [pgpartman/pg_partman#366]
Hi. I'm new to pg_parman. We have a table with a date column which is actually of integer type in yyyyMMdd format. Is there a way I can enable the 'daily' partition creation for that integer column?

thanks.

**Comment by keithf4** [comment]
If you are talking about storing the date as an integer in a format that results in values like "20210618", then no it does not support that. It does support storing timestamps as integers but only in epoch format in either seconds or milliseconds.

**Comment by lihaostar** [comment]
Thank you.
