### ISSUE TITLE
partition_data.py is not migrating data

### ISSUE THREAD

**Issue by akshat113** [pgpartman/pg_partman#368]
Hi,

I recently started using partitioning on a dataset with 75mln rows and which is gonna expand much further. I was able to implement everything. The new data is going into partitions. But when I am trying to move the existing data in the parent table using partition_data.py the migration is happening very slow. 8-10 rows at a time. 

Below is the arguments I am using:

python partition_data.py -p "public.main_data3" -t time -c 'host=XXX.XXX.XXX.XXXX dbname=burning_glass password=XXXXX user=XXXXXX'

P.S I am not a dba guy, more of a finance quant. If my description is not good please pardon me.

**Comment by akshat113** [comment]
Also even if it is moving 8-10 rows at one time, the speed is very slow.

**Comment by akshat113** [comment]
I think it was a silly issue. It is moving data day by day. And there was an issue with the server thats why the migration was slow.

**Comment by keithf4** [comment]
By default it will move the data in the size of the partition interval and I believe that will be the largest interval it can work in. And by default each batch will be one interval's worth of data and it will only run a single batch. You can tell it to run more than one batch in a single call.

**Comment by akshat113** [comment]
Got it. Also just wanted to confirm if partition_data.py by default remove data from the original parent table. I have noticed, it is not removing any data.

**Comment by keithf4** [comment]
No, it should be "moving" the data. Deleting from parent and inserting to child table. It's doing a CTE operation using `DELETE ... RETURNING ... INSERT `

https://github.com/pgpartman/pg_partman/blob/master/sql/functions/partition_data_time.sql#L305

If you have a reproducible case where the data is not being removed, I can investigate more.

**Comment by akshat113** [comment]
@keithf4 
I tried to create everything new, as migration of old data was taking time. I ran following queries:
CREATE TABLE public.main_data4 (LIKE public.main_data3 INCLUDING ALL);
SELECT partman.create_parent('public.main_data4','jobdate','partman','daily', p_start_partition := '2021-01-01');

and then I just inserted data into main_data4. The data is going into the partitions but once copy is also maintained on main_data4. I don't want anything in main_data4. Do you know can I do that?
