### ISSUE TITLE
p_start_partition not honored (always date_trunc)

### ISSUE THREAD

**Issue by wesselvdv** [pgpartman/pg_partman#369]
When using a p_start_partition of '04-07-2021' and a p_interval of '9 weeks' it'll result in INVALID time partitions being created. This because all the start dates of the partitions are truncated to the first of the month. This creates overlapping partitions if you're using an interval that's not standard.

```
+--------------------------+--------------------------+--------------+------------+-------+
|child_start_time          |child_end_time            |child_start_id|child_end_id|suffix |
+--------------------------+--------------------------+--------------+------------+-------+
|2021-07-01 00:00:00.000000|2021-09-02 00:00:00.000000|NULL          |NULL        |2021_07|
|2021-09-01 00:00:00.000000|2021-11-03 00:00:00.000000|NULL          |NULL        |2021_09|
+--------------------------+--------------------------+--------------+------------+-------+
```

I think it'd be best if we put the date_trunc behind a flag, or don't do it if p_start_partition is passed in.

**Comment by wesselvdv** [comment]
It seems that `partman.show_partition_info()` is showing the wrong partition info, whereas postgres is actually doing the correct thing:

```
+--------------------------+--------------------------+--------------+------------+-------+
|child_start_time          |child_end_time            |child_start_id|child_end_id|suffix |
+--------------------------+--------------------------+--------------+------------+-------+
|2021-07-01 00:00:00.000000|2021-09-02 00:00:00.000000|NULL          |NULL        |2021_07|
+--------------------------+--------------------------+--------------+------------+-------+
```

```
+--------------------------+------------------------------------------------------------------------+
|partition_name            |partition_expression                                                    |
+--------------------------+------------------------------------------------------------------------+
|player_attributes_p2021_07|FOR VALUES FROM ('2021-07-04 00:00:00+00') TO ('2021-09-05 00:00:00+00')|
|player_attributes_default |DEFAULT                                                                 |
+--------------------------+------------------------------------------------------------------------+
```

**Comment by wesselvdv** [comment]
I ended up monkey patching the `partman.show_partition_info` as well, I won't create a PR for that, because I am sure it will work for all cases:

```sql
CREATE OR REPLACE FUNCTION partman.show_partition_info(p_child_table TEXT
, p_partition_interval TEXT DEFAULT NULL
, p_parent_table TEXT DEFAULT NULL
, OUT child_start_time TIMESTAMPTZ
, OUT child_end_time TIMESTAMPTZ
, OUT child_start_id BIGINT
, OUT child_end_id BIGINT
, OUT suffix TEXT)
  RETURNS RECORD
  LANGUAGE plpgsql
  STABLE
AS
$$
DECLARE

  v_child_schema       TEXT;
  v_child_tablename    TEXT;
  v_control            TEXT;
  v_control_type       TEXT;
  v_datetime_string    TEXT;
  v_epoch              TEXT;
  v_new_search_path    TEXT := 'partman,pg_temp';
  v_old_search_path    TEXT;
  v_parent_table       TEXT;
  v_partition_interval TEXT;
  v_partition_type     TEXT;
  v_quarter            TEXT;
  v_suffix             TEXT;
  v_suffix_position    INT;
  v_year               TEXT;

BEGIN
  /*
   * Show the data boundries for a given child table as well as the suffix that will be used.
   * Passing the parent table argument improves performance by avoiding a catalog lookup.
   * Passing an interval lets you set one different than the default configured one if desired.
   */

  SELECT
    CURRENT_SETTING('search_path')
  INTO v_old_search_path;
  EXECUTE FORMAT('SELECT set_config(%L, %L, %L)', 'search_path', v_new_search_path, 'false');

  SELECT
    n.nspname,
    c.relname
  INTO v_child_schema, v_child_tablename
  FROM
    pg_catalog.pg_class c
      JOIN pg_catalog.pg_namespace n
           ON c.relnamespace = n.oid
  WHERE
    n.nspname = SPLIT_PART(p_child_table, '.', 1)::NAME
    AND c.relname = SPLIT_PART(p_child_table, '.', 2)::NAME;

  IF v_child_tablename IS NULL THEN
    EXECUTE FORMAT('SELECT set_config(%L, %L, %L)', 'search_path', v_old_search_path, 'false');
    RAISE EXCEPTION 'Child table given does not exist (%)', p_child_table;
  END IF;

  IF p_parent_table IS NULL THEN
    SELECT
      n.nspname || '.' || c.relname
    INTO v_parent_table
    FROM
      pg_catalog.pg_inherits h
        JOIN pg_catalog.pg_class c
             ON c.oid = h.inhparent
        JOIN pg_catalog.pg_namespace n
             ON c.relnamespace = n.oid
    WHERE
      h.inhrelid::REGCLASS = p_child_table::REGCLASS;
  ELSE
    v_parent_table := p_parent_table;
  END IF;

  IF p_partition_interval IS NULL THEN
    SELECT
      control,
      partition_interval,
      partition_type,
      datetime_string,
      epoch
    INTO v_control, v_partition_interval, v_partition_type, v_datetime_string, v_epoch
    FROM
      partman.part_config
    WHERE
      parent_table = v_parent_table;
  ELSE
    v_partition_interval := p_partition_interval;
    SELECT
      control,
      partition_type,
      datetime_string,
      epoch
    INTO v_control, v_partition_type, v_datetime_string, v_epoch
    FROM
      partman.part_config
    WHERE
      parent_table = v_parent_table;
  END IF;

  IF v_control IS NULL THEN
    RAISE EXCEPTION 'Parent table of given child not managed by pg_partman: %', v_parent_table;
  END IF;

  SELECT
    general_type
  INTO v_control_type
  FROM
    partman.check_control_type(v_child_schema, v_child_tablename, v_control);

  v_suffix_position := (LENGTH(v_child_tablename) - POSITION('p_' IN REVERSE(v_child_tablename))) + 2;
  v_suffix := SUBSTRING(v_child_tablename FROM v_suffix_position);

  IF v_control_type = 'time' OR (v_control_type = 'id' AND v_epoch <> 'none') THEN
    IF CURRENT_SETTING('server_version_num')::INT >= 120000 THEN
      SELECT
        t1.match
      INTO child_start_time
      FROM
        pg_class t2
          JOIN LATERAL (
          SELECT
            UNNEST(t3)::TIMESTAMPTZ AS match
          FROM
            REGEXP_MATCHES(PG_GET_EXPR(t2.relpartbound, t2.oid, TRUE),
                           $REGEX$'\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\+\d{2}'\)$REGEX$) t3
          ) t1
               ON TRUE
      WHERE
        t2.oid = (v_child_schema || '.' || v_child_tablename)::REGCLASS;
    ELSE
      IF v_partition_interval::INTERVAL <> '3 months' OR
         (v_partition_interval::INTERVAL = '3 months' AND v_partition_type = 'time-custom') THEN
        child_start_time := TO_TIMESTAMP(v_suffix, v_datetime_string);
      ELSE
        -- to_timestamp doesn't recognize 'Q' date string formater. Handle it
        v_year := SPLIT_PART(v_suffix, 'q', 1);
        v_quarter := SPLIT_PART(v_suffix, 'q', 2);
        CASE
          WHEN v_quarter = '1' THEN
            child_start_time := TO_TIMESTAMP(v_year || '-01-01', 'YYYY-MM-DD');
          WHEN v_quarter = '2' THEN
            child_start_time := TO_TIMESTAMP(v_year || '-04-01', 'YYYY-MM-DD');
          WHEN v_quarter = '3' THEN
            child_start_time := TO_TIMESTAMP(v_year || '-07-01', 'YYYY-MM-DD');
          WHEN v_quarter = '4' THEN
            child_start_time := TO_TIMESTAMP(v_year || '-10-01', 'YYYY-MM-DD');
          ELSE
            -- handle case when partition name did not use "q" convetion
            child_start_time := TO_TIMESTAMP(v_suffix, v_datetime_string);
        END CASE;
      END IF;
    END IF;
    child_end_time := (child_start_time + v_partition_interval::INTERVAL);

  ELSIF v_control_type = 'id' THEN

    child_start_id := v_suffix::BIGINT;
    child_end_id := (child_start_id + v_partition_interval::BIGINT) - 1;

  ELSE
    RAISE EXCEPTION 'Invalid partition type encountered in show_partition_info()';
  END IF;

  suffix = v_suffix;

  EXECUTE FORMAT('SELECT set_config(%L, %L, %L)', 'search_path', v_old_search_path, 'false');

  RETURN;

END
$$;
```

**Comment by keithf4** [comment]
So I'm working through your PRs. Found a simpler method to fix the show_partition_info() function not returning the proper boundary values. However, that and your other PR are having some consequences with other areas in subpartitioning (it's making more child tables than it used to with create_parent()). So trying to figure that out.

I'll have a test branch up for you to review once I've either figured it out or gotten stuck and could use some feedback.

**Comment by keithf4** [comment]
I have a preview of 4.6.0 with a proposed solution to this pushed up. Lot of internal changes, but for the user there is just a new parameter to `create_parent()`, that being `p_date_trunc_interval`. 

https://github.com/pgpartman/pg_partman/tree/4.6.0

So the issue that you pointed out here, that it is truncating to the wrong point depending on the interval chosen and a possible custom start time, is an issue in two places

- I'm forcing a specific truncation interval based on the size of the partition interval
- The datetime_string used to name the child tables

By having the user now able to choose the truncation interval (values that can be fed to the `date_trunc()` function - https://www.postgresql.org/docs/13/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC), this allows it to truncate at the desired location. However, since the partition interval can literally be anything, I can't easily predict what the proper truncation interval should be. In your case of 9 weeks, you'd actually want to truncate at the `week` interval. But someone partitioning at 4 months may want it the boundaries at the `month`, while someone wanting it a 16 week interval may want it at the `week`. So only the user would know what they actually want.

Also with the old method, your 9 week interval was getting partition names like `YYYY_MM` which isn't actually very clear since neighboring children could easily share the same month's data. So if someone sets the custom truncation interval, only two possible naming patterns are now possible:

- YYYY_MM_DD when >= 1 day
- YYYY_MM_DD_HH24MISS when < 1 day

And reviewing the code, I may actually remove the more specific datetime_string possibilities in the future and just have these two, or something similar.

So, apologies for how long this took to solve. I was limited on time and it turned out to be a lot trickier to handle properly than I anticipated. But this turned `show_partition_info()` into a much better function and allows a lot more flexibility in the end.

I'm still testing things, so the 4.6.0 branch is not finalized. But if you wouldn't mind testing it as well, I'd appreciate it. Here's an example that should work for your given scenario with the new option. You'll have to put the update file (`pg_partman--4.5.1--4.6.0.sql`) in the proper location for PostgreSQL to pick it up (`$SHAREDIR/extension`)
```
ALTER EXTENSION pg_partman UPDATE TO '4.6.0';

create schema partman_test;

CREATE TABLE partman_test.time_taptest_table (col1 int, col2 text, col3 timestamptz NOT NULL DEFAULT now()) PARTITION BY RANGE (col3);

select partman.create_parent('partman_test.time_taptest_table', 'col3', 'native', '9 weeks', p_start_partition := '2021-04-07', p_date_trunc_interval := 'week');
```
```
keith@keith=# \d+ partman_test.time_taptest_table
                            Partitioned table "partman_test.time_taptest_table"
 Column |           Type           | Collation | Nullable | Default | Storage  | Stats target | Description 
--------+--------------------------+-----------+----------+---------+----------+--------------+-------------
 col1   | integer                  |           |          |         | plain    |              | 
 col2   | text                     |           |          |         | extended |              | 
 col3   | timestamp with time zone |           | not null | now()   | plain    |              | 
Partition key: RANGE (col3)
Partitions: partman_test.time_taptest_table_p2021_04_05 FOR VALUES FROM ('2021-04-05 00:00:00-04') TO ('2021-06-07 00:00:00-04'),
            partman_test.time_taptest_table_p2021_06_07 FOR VALUES FROM ('2021-06-07 00:00:00-04') TO ('2021-08-09 00:00:00-04'),
            partman_test.time_taptest_table_p2021_08_09 FOR VALUES FROM ('2021-08-09 00:00:00-04') TO ('2021-10-11 00:00:00-04'),
            partman_test.time_taptest_table_p2021_10_11 FOR VALUES FROM ('2021-10-11 00:00:00-04') TO ('2021-12-13 00:00:00-05'),
            partman_test.time_taptest_table_p2021_12_13 FOR VALUES FROM ('2021-12-13 00:00:00-05') TO ('2022-02-14 00:00:00-05'),
            partman_test.time_taptest_table_p2022_02_14 FOR VALUES FROM ('2022-02-14 00:00:00-05') TO ('2022-04-18 00:00:00-04'),
            partman_test.time_taptest_table_p2022_04_18 FOR VALUES FROM ('2022-04-18 00:00:00-04') TO ('2022-06-20 00:00:00-04'),
            partman_test.time_taptest_table_default DEFAULT
```

**Comment by keithf4** [comment]
I've got what is hopefully the finalized code for version 4.6.0 in this branch if you have a moment to test. I'm hoping to have this out next week.

https://github.com/pgpartman/pg_partman/tree/4.6.0

This should fix this issue along with the other PR you made to fix `show_partition_info()`. It's also a bit challenging trying to describe how to use this new option, so if you have any suggestions on the language for the `p_date_trunc_interval` option to `create_parent()` I'd also appreciate any feedback.

https://github.com/pgpartman/pg_partman/commit/92fd354b34c378746753cc8eda8bc27dde91ace5#diff-63161454387a5dc587c5dd1fbb0a3c781871f3b99e4f1303d33481523b5328e5R179

Apologies on the length of time to fix this, but it was a much more challenging issue than it seemed. But this should greatly increase pg_partman's usage with any custom time intervals and starting points desired, so thank you for bringing it up!

**Comment by wesselvdv** [comment]
> I've got what is hopefully the finalized code for version 4.6.0 in this branch if you have a moment to test. I'm hoping to have this out next week.
> 
> https://github.com/pgpartman/pg_partman/tree/4.6.0
> 
> This should fix this issue along with the other PR you made to fix `show_partition_info()`. It's also a bit challenging trying to describe how to use this new option, so if you have any suggestions on the language for the `p_date_trunc_interval` option to `create_parent()` I'd also appreciate any feedback.
> 
> [92fd354#diff-63161454387a5dc587c5dd1fbb0a3c781871f3b99e4f1303d33481523b5328e5R179](https://github.com/pgpartman/pg_partman/commit/92fd354b34c378746753cc8eda8bc27dde91ace5#diff-63161454387a5dc587c5dd1fbb0a3c781871f3b99e4f1303d33481523b5328e5R179)
> 
> Apologies on the length of time to fix this, but it was a much more challenging issue than it seemed. But this should greatly increase pg_partman's usage with any custom time intervals and starting points desired, so thank you for bringing it up!

No need for apologies, I am running with my own monkey patches, and besides I am using this in an AWS RDS environment, so any release you make has a significant lead time before it's time for me to remove said monkey patches.

I'll give this a shot locally, and I'll remove my monkey patches and apply the update `4.5.1-4.6.0`

Regarding the nomenclature, the only word I could come up with is `precision`. This new option basically determines level of precision when truncating the date. Not sure if that makes it easier to understand. 

On the other side, if one is having issues because of this then they'd probably already know a bit more so they'd be able to understand is more easily.
