### ISSUE TITLE
How to automatically create new daily partitions?

### ISSUE THREAD

**Issue by kartikdc** [pgpartman/pg_partman#375]
Hello.

Sorry for the noob question. Basically I am trying to understand how to make the best of pg_partman. I would like set up daily partitioning for a table such that when the first set of partitions are exhausted, new partitions are created for days that don't have partitions created for them in the beginning.

My set up is [this PostgreSQL container (`postgres:13-buster`)](https://hub.docker.com/_/postgres). I installed pg_partman via apt. I enabled the background worker in the docker-compose file I use. Then I followed the instructions [here](https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman_howto_native.md#simple-time-based-1-partition-per-day). The init script looks something like this:

```sql
CREATE TABLE public.logs (
    ...
    "timestamp" timestamp with time zone,
    ...
)
PARTITION BY RANGE ("timestamp");

CREATE INDEX ON public.logs ("timestamp");
SELECT partman.create_parent('public.logs', 'timestamp', 'native', 'daily');
```

After this, the partitioned setup looks like this:

```
logs=# \d+ logs;
...
Partitions: logs_p2021_07_24 FOR VALUES FROM ('2021-07-24 00:00:00+00') TO ('2021-07-25 00:00:00+00'),
            logs_p2021_07_25 FOR VALUES FROM ('2021-07-25 00:00:00+00') TO ('2021-07-26 00:00:00+00'),
            logs_p2021_07_26 FOR VALUES FROM ('2021-07-26 00:00:00+00') TO ('2021-07-27 00:00:00+00'),
            logs_p2021_07_27 FOR VALUES FROM ('2021-07-27 00:00:00+00') TO ('2021-07-28 00:00:00+00'),
            logs_p2021_07_28 FOR VALUES FROM ('2021-07-28 00:00:00+00') TO ('2021-07-29 00:00:00+00'),
            logs_p2021_07_29 FOR VALUES FROM ('2021-07-29 00:00:00+00') TO ('2021-07-30 00:00:00+00'),
            logs_p2021_07_30 FOR VALUES FROM ('2021-07-30 00:00:00+00') TO ('2021-07-31 00:00:00+00'),
            logs_p2021_07_31 FOR VALUES FROM ('2021-07-31 00:00:00+00') TO ('2021-08-01 00:00:00+00'),
            logs_p2021_08_01 FOR VALUES FROM ('2021-08-01 00:00:00+00') TO ('2021-08-02 00:00:00+00'),
            logs_default DEFAULT
```

The background worker is loaded:

```
nudjur_logs=# SHOW shared_preload_libraries;
 shared_preload_libraries
--------------------------
 pg_partman_bgw
```

But past 2021-08-02, new partitions have not been created. I was wondering what I need to make it happen.

Any advice is appreciated since I am a bit inexperienced. Let me know if any more clarification is required. Thanks for your patience.

**Comment by keithf4** [comment]
Do you have any data entered into the table? By default new partitions will only be made if there is sufficient data for it to premake new partitions ahead of that data.

**Comment by kartikdc** [comment]
Yes @keithf4. There is a lot of data in the table with `timestamp` past `2021-08-02`:

```
logs=# WITH newer AS (SELECT * FROM logs WHERE timestamp > '2021-08-02' LIMIT 100000) SELECT COUNT(*) FROM newer;
 count
--------
 100000
(1 row)

```

**Comment by keithf4** [comment]
Did you set an interval for the background worker to run? It does have a default of 1 hour, so just seeing if you set it to something significantly higher.

**Comment by keithf4** [comment]
Are you seeing any errors in your PostgreSQL logs concerning the background worker running?

**Comment by kartikdc** [comment]
I haven't specified any interval for the background worker so it should be using the default.

I checked the logs and this is the only line regarding partman:

```
2021-07-28 05:36:10.291 UTC [55] LOG:  pg_partman master background worker master process initialized with role postgres
```

Perhaps it isn't working because there is no user called `postgres`. I feel a bit silly because this is right there in the README. Will update the settings and close the issue if this turned out to be the cause.

**Comment by keithf4** [comment]
Not a problem. Just let me know if there's still any issues.

**Comment by kartikdc** [comment]
@keithf4 So I updated the configuration and restarted the container. This got the background worker to work, but the maintenance fails:

```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2021-08-06 15:30:38.664 UTC [1] LOG:  starting PostgreSQL 13.3 (Debian 13.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2021-08-06 15:30:38.664 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-08-06 15:30:38.665 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2021-08-06 15:30:38.669 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-08-06 15:30:38.673 UTC [25] LOG:  database system was shut down at 2021-08-06 15:30:37 UTC
2021-08-06 15:30:38.677 UTC [1] LOG:  database system is ready to accept connections
2021-08-06 15:30:38.678 UTC [31] LOG:  pg_partman master background worker master process initialized with role kartik
2021-08-06 15:30:38.690 UTC [33] LOG:  pg_partman dynamic background worker (dbname=kartik_logs) dynamic background worker initialized with role kartik on database kartik_logs
2021-08-06 15:30:39.636 UTC [33] ERROR:  updated partition constraint for default partition "logs_default" would be violated by some row
        CONTEXT: SQL statement "ALTER TABLE public.logs ATTACH PARTITION public.logs_p2021_08_02 FOR VALUES FROM ('2021-08-02 00:00:00+00') TO ('2021-08-03 00:00:00+00')"
        PL/pgSQL function create_partition_time(text,timestamp with time zone[],boolean,text) line 239 at EXECUTE
        PL/pgSQL function partman.run_maintenance(text,boolean,boolean) line 273 at assignment
        SQL statement "SELECT "partman".run_maintenance(p_analyze := false, p_jobmon := true)"
        DETAIL:
        HINT:
        CONTEXT: PL/pgSQL function create_partition_time(text,timestamp with time zone[],boolean,text) line 479 at RAISE
        PL/pgSQL function partman.run_maintenance(text,boolean,boolean) line 273 at assignment
        SQL statement "SELECT "partman".run_maintenance(p_analyze := false, p_jobmon := true)"
        DETAIL:
        HINT:
2021-08-06 15:30:39.636 UTC [33] CONTEXT:  PL/pgSQL function partman.run_maintenance(text,boolean,boolean) line 402 at RAISE
        SQL statement "SELECT "partman".run_maintenance(p_analyze := false, p_jobmon := true)"
2021-08-06 15:30:39.637 UTC [1] LOG:  background worker "pg_partman dynamic background worker (dbname=kartik_logs)" (PID 33) exited with exit code 1
```

This seems to be caused by there being four days between today and the date for the latest partitions. Any idea if I can still create partitions for these days without having to create a new volume?

Closing since the problem for which the issue was opened has been figured out. Thanks for your patience.

**Comment by keithf4** [comment]
The error is because you have data in the default and you cannot create a new child table if that new child table's constraint matches data in the default. 

If the data in the default is data you need to keep, you can use the `partition_data_proc()` procedure to have it manage moving the data out to the proper child tables, creating them if it needs to.

If the data in the default isn't needed, you can simply delete it.

Either way, maintenance should work once you've done either of these options.

**Comment by kartikdc** [comment]
Last question: Will `partition_data_proc()` lock the table?

**Comment by keithf4** [comment]
It locks it as much as run_maintenance would for adding/removing child tables. And the rows that are being moved will themselves be locked since they're being transferred between tables.

**Comment by kartikdc** [comment]
@keithf4 Thanks very much for all your help.
