### ISSUE TITLE
ERROR:  could not establish connection

### ISSUE THREAD

**Issue by BundeAmos** [pgpartman/pg_partman#376]
Any help with this?

Look at the query that yielded the error.
SELECT partman.create_parent('public.trial_partition','create_date','native' ,'monthly',p_start_partition := '2017-10-01');

ERROR:  could not establish connection
DETAIL:  could not parse network address "kenyadev.kenya.com": Name or service not known
CONTEXT:  SQL statement "SELECT job_id FROM public.dblink('port=5432 dbname=qa_sap_erp user=sap password=sappgpwd hostaddr=copiadev.copiakenya.com','SELECT jobmon._autonomous_add_job (''sap'',''PARTMAN CREATE PARENT: public.trial_partition'',319370)',TRUE) t (job_id int)"
PL/pgSQL function add_job(text) line 14 at EXECUTE
SQL statement "SELECT jobmon.add_job('PARTMAN CREATE PARENT: public.trial_partition')"
PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,text[],boolean,text,boolean) line 763 at EXECUTE
SQL state: 0800

**Comment by keithf4** [comment]
Duplicate
