### ISSUE TITLE
How to recreate hourly partitions based on next hour?

### ISSUE THREAD

**Issue by strahinjalalic** [pgpartman/pg_partman#381]
Hi,

I have a table that is always storing last 15 days of data (new data is arriving every 5mins). Is it possible to create new partition when clock hit next hour? Droping last partition table is not a problem, but I need to have new one every hour. 

I called function like this: **SELECT partman.create_parent('table_name', 'column_name', 'native', 'hourly', p_template_table := 'public.template_table');** 

* column_name is timestamp without timezone in format **2021-08-24 14:55:00**

**Comment by keithf4** [comment]
Please read the sections on maintenance in the documentation. Specifically either scheduling the run_maintenance() or using the background worker. Just run either of those often enough and, with an hourly interval, you should be fine.

**Comment by strahinjalalic** [comment]
Thanks for assist, it works fine now.
