### ISSUE TITLE
[question] how to create partitions in a separate schema ?

### ISSUE THREAD

**Issue by mdespriee** [pgpartman/pg_partman#390]
Just to tidy up our public schema, is it possible to specify a target schema for partition creation ?
Also, is it possible to move existing partitions to another schema ?

(Sorry if it's already documented, didn't found)

**Comment by thomasboussekey** [comment]
Hello Mathieu,

You can use the following syntax:

```sql
CREATE EXTENSION pg_partman
  WITH SCHEMA <<my_schema>>;
```

**Comment by keithf4** [comment]
Are you talking about the schema for the actual partitioned tables or for the pg_partman extension itself.

Thomas's answer is correct for where to install pg_partman.

For the partition sets themselves, it is required to fully schema qualify the parent table given to `create_parent()`, so just make sure and use the schema you want at that time.

**Comment by keithf4** [comment]
Moving them to another schema may be a bit tricky and I'd recommend testing this out.

For the tables themselves, you'd use the ALTER TABLE ... SET SCHEMA ... command

https://www.postgresql.org/docs/current/sql-altertable.html

Then update the parent table's entry in the `part_config` table to use the new schema name.

**Comment by mdespriee** [comment]
Sorry if my question is not clear. It's not about the schema of pg_partman.
I'd like to have parent tables in a schema, say `public`, and partitions (sub-tables) in another schema.

**Comment by keithf4** [comment]
Sorry, creating child tables in a separate schema is not supported at this time.

**Comment by mdespriee** [comment]
clear. thanks.
