### ISSUE TITLE
SQL error applying privileges to users with "." in name

### ISSUE THREAD

**Issue by McCio** [pgpartman/pg_partman#395]
In a situation where some execute privileges were given to users with dots in the username (e.g. john.doe), the name must be double-quoted when issuing commands.

While updating from partman 4.4 to 4.6 the following error was in fact raised:
```
ERROR:  syntax error at or near "."
LINE 1: ...ean, text, text, boolean, boolean) TO PUBLIC,john.doe,p...
                                                            ^
QUERY:  GRANT EXECUTE ON FUNCTION partman.create_sub_parent(text, text, text, text, text, text[], int, text, boolean, text, text, boolean, boolean) TO PUBLIC,john.doe,partman;
CONTEXT:  PL/pgSQL function inline_code_block line 7 at EXECUTE
```

All usernames should be probably quoted.

**Comment by keithf4** [comment]
Version 4.6.1 has been released and fixes the more recent update files so this works better. Apologies for the delay in release and thank you for reporting the issue!
