### ISSUE TITLE
partition constraint is violated by some row: Online Partitioning

### ISSUE THREAD

**Issue by BundeAmos** [pgpartman/pg_partman#406]
Odoo ORM is  responsible for creating the tables, when I do an offline partitioning it needs the partition column to be the PRIMARY KEY ---"create_date" in my case as I need to so with ranges(timestamp). When the odoo Modules are updated it fails to recognize the partitioned table. This then locks Odoo ORM in creating or updating modules.

USE CASE:
I have tried Using Online partitioning to get the solution to this but I am struck with the following ERROR and steps are down below.

ERROR:  partition constraint is violated by some row
SQL state: 23514

Existing Table Structures(Created by Odoo ORM):::: PARENT/ORIGINAL TABLE
(
    id integer NOT NULL DEFAULT nextval('res_partner_id_seq'::regclass),
    name character varying COLLATE pg_catalog."default",
    company_id integer,
    display_name character varying COLLATE pg_catalog."default",
    date date,
    title integer,
    parent_id integer,
    ref character varying COLLATE pg_catalog."default",
    lang character varying COLLATE pg_catalog."default",
    tz character varying COLLATE pg_catalog."default",
    user_id integer,
    vat character varying COLLATE pg_catalog."default",
    website character varying COLLATE pg_catalog."default",
    comment text COLLATE pg_catalog."default",
    credit_limit double precision,
    barcode character varying COLLATE pg_catalog."default",
    active boolean,
    customer boolean,
    supplier boolean,
    employee boolean,
    function character varying COLLATE pg_catalog."default",
    type character varying COLLATE pg_catalog."default",
    street character varying COLLATE pg_catalog."default",
    street2 character varying COLLATE pg_catalog."default",
    zip character varying COLLATE pg_catalog."default",
    city character varying COLLATE pg_catalog."default",
    state_id integer,
    country_id integer NOT NULL,
    email character varying COLLATE pg_catalog."default",
    phone character varying COLLATE pg_catalog."default",
    mobile character varying COLLATE pg_catalog."default",
    is_company boolean,
    industry_id integer,
    color integer,
    partner_share boolean,
    commercial_partner_id integer,
    commercial_partner_country_id integer,
    commercial_company_name character varying COLLATE pg_catalog."default",
    company_name character varying COLLATE pg_catalog."default",
    create_uid integer,
    create_date timestamp without time zone,
    write_uid integer,
    write_date timestamp without time zone,
    activity_date_deadline date,
    message_last_post timestamp without time zone,
    message_bounce integer,
    opt_out boolean,
    signup_token character varying COLLATE pg_catalog."default",
    signup_type character varying COLLATE pg_catalog."default",
    signup_expiration timestamp without time zone,
    debit_limit numeric,
    last_time_entries_checked timestamp without time zone,
    invoice_warn character varying COLLATE pg_catalog."default" NOT NULL,
    invoice_warn_msg text COLLATE pg_catalog."default",
    team_id integer,
    sale_warn character varying COLLATE pg_catalog."default" NOT NULL,
    sale_warn_msg text COLLATE pg_catalog."default",
    is_agent boolean,
    agent_type_id integer,
    can_purchase boolean,
    active_agent boolean,
    sale_associate_id integer,
    is_sale_associate boolean,
    partner_type character varying COLLATE pg_catalog."default",
    agent_id integer,
    picking_warn character varying COLLATE pg_catalog."default" NOT NULL,
    picking_warn_msg text COLLATE pg_catalog."default",
    purchase_warn character varying COLLATE pg_catalog."default" NOT NULL,
    purchase_warn_msg text COLLATE pg_catalog."default",
    referral_date timestamp without time zone,
    referrer_id integer,
    referral_program_id integer,
    openerp_7_id integer,
    credit_days integer,
    receiving_agent_id integer,
    ban_date date,
    fake_customer boolean,
    woo_company_name_ept character varying COLLATE pg_catalog."default",
    woo_customer_id character varying COLLATE pg_catalog."default",
    agent_validated boolean,
    validated_by integer,
    area_team_id integer,
    agent_launch_date timestamp without time zone,
    sacco_id integer,
    new_can_self_order boolean,
    agent_referrer_id integer,
    recruitment_channel_id integer,
    dob date,
    first_name character varying COLLATE pg_catalog."default",
    last_name character varying COLLATE pg_catalog."default",
    trainer_associate_id integer,
    associate_type character varying COLLATE pg_catalog."default",
    date_registration date,
    registration_date date,
    sms_count integer,
    credit_program_id integer
)

Step 01:
CREATE TABLE IF NOT EXISTS public.res_partner_partitioned
(
    id integer NOT NULL DEFAULT nextval('res_partner_id_seq'::regclass),
    name character varying ,
    company_id integer,
    display_name character varying ,
    date date,
    title integer,
    parent_id integer,
    ref character varying ,
    lang character varying ,
    tz character varying ,
    user_id integer,
    vat character varying ,
    website character varying ,
    comment text ,
    credit_limit double precision,
    barcode character varying ,
    active boolean,
    customer boolean,
    supplier boolean,
    employee boolean,
    function character varying ,
    type character varying ,
    street character varying ,
    street2 character varying ,
    zip character varying ,
    city character varying ,
    state_id integer,
    country_id integer NOT NULL,
    email character varying ,
    phone character varying ,
    mobile character varying ,
    is_company boolean,
    industry_id integer,
    color integer,
    partner_share boolean,
    commercial_partner_id integer,
    commercial_partner_country_id integer,
    commercial_company_name character varying ,
    company_name character varying ,
    create_uid integer,
    create_date timestamp without time zone,
    write_uid integer,
    write_date timestamp without time zone,
    activity_date_deadline date,
    message_last_post timestamp without time zone,
    message_bounce integer,
    opt_out boolean,
    signup_token character varying ,
    signup_type character varying ,
    signup_expiration timestamp without time zone,
    debit_limit numeric,
    last_time_entries_checked timestamp without time zone,
    invoice_warn character varying  NOT NULL,
    invoice_warn_msg text,
    team_id integer,
    sale_warn character varying NOT NULL,
    sale_warn_msg text ,
    is_agent boolean,
    agent_type_id integer,
    can_purchase boolean,
    active_agent boolean,
    sale_associate_id integer,
    is_sale_associate boolean,
    partner_type character varying ,
    agent_id integer,
    picking_warn character varying ,
    picking_warn_msg text ,
    purchase_warn character varying NOT NULL,
    purchase_warn_msg text,
    referral_date timestamp without time zone,
    referrer_id integer,
    referral_program_id integer,
    openerp_7_id integer,
    credit_days integer,
    receiving_agent_id integer,
    ban_date date,
    fake_customer boolean,
    woo_company_name_ept character varying ,
    woo_customer_id character varying ,
    agent_validated boolean,
    validated_by integer,
    area_team_id integer,
    agent_launch_date timestamp without time zone,
    sacco_id integer,
    new_can_self_order boolean,
    agent_referrer_id integer,
    recruitment_channel_id integer,
    dob date,
    first_name character varying ,
    last_name character varying ,
    trainer_associate_id integer,
    associate_type character varying ,
    date_registration date,
    registration_date date,
    sms_count integer,
    credit_program_id integer
	) PARTITION BY RANGE (create_date);

Step 02:
CREATE TABLE public.res_partner_template (LIKE public.res_partner_partitioned);

Step 03:
ALTER TABLE public.res_partner_template ADD PRIMARY KEY (id);

Step 04:
SELECT partman.create_parent('public.res_partner_partitioned', 'create_date', 'native', 'monthly', p_template_table:= 'public.res_partner_template', p_premake := 52,p_inherit_fk := 'true', p_start_partition := '2018-11-01');

Step 05:
UPDATE partman.part_config SET parent_table = 'public.res_partner', premake = 40,infinite_time_partitions = true,retention = '24 months',retention_keep_table=true WHERE parent_table = 'public.res_partner_partitioned';

Step 06:'
BEGIN;
LOCK TABLE public.res_partner IN ACCESS EXCLUSIVE MODE;
LOCK TABLE public.res_partner_partitioned IN ACCESS EXCLUSIVE MODE;
ALTER TABLE public.res_partner RENAME TO res_partner_default;
ALTER TABLE public.res_partner_partitioned RENAME TO res_partner;
ALTER TABLE public.res_partner_partitioned_p2018_11  RENAME TO  res_partner_p2018_11;
ALTER TABLE public.res_partner_partitioned_p2018_12  RENAME TO  res_partner_p2018_12;
ALTER TABLE public.res_partner_partitioned_p2019_01  RENAME TO  res_partner_p2019_01;
ALTER TABLE public.res_partner_partitioned_p2019_02  RENAME TO  res_partner_p2019_02;
ALTER TABLE public.res_partner_partitioned_p2019_03  RENAME TO  res_partner_p2019_03;
ALTER TABLE public.res_partner_partitioned_p2019_04  RENAME TO  res_partner_p2019_04;
ALTER TABLE public.res_partner_partitioned_p2019_05  RENAME TO  res_partner_p2019_05;
ALTER TABLE public.res_partner_partitioned_p2019_06  RENAME TO  res_partner_p2019_06;
ALTER TABLE public.res_partner_partitioned_p2019_07  RENAME TO  res_partner_p2019_07;
ALTER TABLE public.res_partner_partitioned_p2019_08  RENAME TO  res_partner_p2019_08;
ALTER TABLE public.res_partner_partitioned_p2019_09  RENAME TO  res_partner_p2019_09;
ALTER TABLE public.res_partner_partitioned_p2019_10  RENAME TO  res_partner_p2019_10;
ALTER TABLE public.res_partner_partitioned_p2019_11  RENAME TO  res_partner_p2019_11;
ALTER TABLE public.res_partner_partitioned_p2019_12  RENAME TO  res_partner_p2019_12;
ALTER TABLE public.res_partner_partitioned_p2020_01  RENAME TO  res_partner_p2020_01;
ALTER TABLE public.res_partner_partitioned_p2020_02  RENAME TO  res_partner_p2020_02;
ALTER TABLE public.res_partner_partitioned_p2020_03  RENAME TO  res_partner_p2020_03;
ALTER TABLE public.res_partner_partitioned_p2020_04  RENAME TO  res_partner_p2020_04;
ALTER TABLE public.res_partner_partitioned_p2020_05  RENAME TO  res_partner_p2020_05;
ALTER TABLE public.res_partner_partitioned_p2020_06  RENAME TO  res_partner_p2020_06;
ALTER TABLE public.res_partner_partitioned_p2020_07  RENAME TO  res_partner_p2020_07;
ALTER TABLE public.res_partner_partitioned_p2020_08  RENAME TO  res_partner_p2020_08;
ALTER TABLE public.res_partner_partitioned_p2020_09  RENAME TO  res_partner_p2020_09;
ALTER TABLE public.res_partner_partitioned_p2020_10  RENAME TO  res_partner_p2020_10;
ALTER TABLE public.res_partner_partitioned_p2020_11  RENAME TO  res_partner_p2020_11;
ALTER TABLE public.res_partner_partitioned_p2020_12  RENAME TO  res_partner_p2020_12;
ALTER TABLE public.res_partner_partitioned_p2021_01  RENAME TO  res_partner_p2021_01;
ALTER TABLE public.res_partner_partitioned_p2021_02  RENAME TO  res_partner_p2021_02;
ALTER TABLE public.res_partner_partitioned_p2021_03  RENAME TO  res_partner_p2021_03;
ALTER TABLE public.res_partner_partitioned_p2021_04  RENAME TO  res_partner_p2021_04;
ALTER TABLE public.res_partner_partitioned_p2021_05  RENAME TO  res_partner_p2021_05;
ALTER TABLE public.res_partner_partitioned_p2021_06  RENAME TO  res_partner_p2021_06;
ALTER TABLE public.res_partner_partitioned_p2021_07  RENAME TO  res_partner_p2021_07;
ALTER TABLE public.res_partner_partitioned_p2021_08  RENAME TO  res_partner_p2021_08;
ALTER TABLE public.res_partner_partitioned_p2021_09  RENAME TO  res_partner_p2021_09;
ALTER TABLE public.res_partner_partitioned_p2021_10  RENAME TO  res_partner_p2021_10;
ALTER TABLE public.res_partner_partitioned_p2021_11  RENAME TO  res_partner_p2021_11;
ALTER TABLE public.res_partner_partitioned_p2021_12  RENAME TO  res_partner_p2021_12;
ALTER TABLE public.res_partner_partitioned_p2022_01  RENAME TO  res_partner_p2022_01;
ALTER TABLE public.res_partner_partitioned_p2022_02  RENAME TO  res_partner_p2022_02;
ALTER TABLE public.res_partner_partitioned_p2022_03  RENAME TO  res_partner_p2022_03;
ALTER TABLE public.res_partner_partitioned_p2022_04  RENAME TO  res_partner_p2022_04;
ALTER TABLE public.res_partner_partitioned_p2022_05  RENAME TO  res_partner_p2022_05;
ALTER TABLE public.res_partner_partitioned_p2022_06  RENAME TO  res_partner_p2022_06;
ALTER TABLE public.res_partner_partitioned_p2022_07  RENAME TO  res_partner_p2022_07;
ALTER TABLE public.res_partner_partitioned_p2022_08  RENAME TO  res_partner_p2022_08;
ALTER TABLE public.res_partner_partitioned_p2022_09  RENAME TO  res_partner_p2022_09;
ALTER TABLE public.res_partner_partitioned_p2022_10  RENAME TO  res_partner_p2022_10;
ALTER TABLE public.res_partner_partitioned_p2022_11  RENAME TO  res_partner_p2022_11;
ALTER TABLE public.res_partner_partitioned_p2022_12  RENAME TO  res_partner_p2022_12;
ALTER TABLE public.res_partner_partitioned_p2023_01  RENAME TO  res_partner_p2023_01;
ALTER TABLE public.res_partner_partitioned_p2023_02  RENAME TO  res_partner_p2023_02;
ALTER TABLE public.res_partner_partitioned_p2023_03  RENAME TO  res_partner_p2023_03;
ALTER TABLE public.res_partner_partitioned_p2023_04  RENAME TO  res_partner_p2023_04;
ALTER TABLE public.res_partner_partitioned_p2023_05  RENAME TO  res_partner_p2023_05;
ALTER TABLE public.res_partner_partitioned_p2023_06  RENAME TO  res_partner_p2023_06;
ALTER TABLE public.res_partner_partitioned_p2023_07  RENAME TO  res_partner_p2023_07;
ALTER TABLE public.res_partner_partitioned_p2023_08  RENAME TO  res_partner_p2023_08;
ALTER TABLE public.res_partner_partitioned_p2023_09  RENAME TO  res_partner_p2023_09;
ALTER TABLE public.res_partner_partitioned_p2023_10  RENAME TO  res_partner_p2023_10;
ALTER TABLE public.res_partner_partitioned_p2023_11  RENAME TO  res_partner_p2023_11;
ALTER TABLE public.res_partner_partitioned_p2023_12  RENAME TO  res_partner_p2023_12;
ALTER TABLE public.res_partner_partitioned_p2024_01  RENAME TO  res_partner_p2024_01;
ALTER TABLE public.res_partner_partitioned_p2024_02  RENAME TO  res_partner_p2024_02;
ALTER TABLE public.res_partner_partitioned_p2024_03  RENAME TO  res_partner_p2024_03;
ALTER TABLE public.res_partner_partitioned_p2024_04  RENAME TO  res_partner_p2024_04;
ALTER TABLE public.res_partner_partitioned_p2024_05  RENAME TO  res_partner_p2024_05;
ALTER TABLE public.res_partner_partitioned_p2024_06  RENAME TO  res_partner_p2024_06;
ALTER TABLE public.res_partner_partitioned_p2024_07  RENAME TO  res_partner_p2024_07;
ALTER TABLE public.res_partner_partitioned_p2024_08  RENAME TO  res_partner_p2024_08;
ALTER TABLE public.res_partner_partitioned_p2024_09  RENAME TO  res_partner_p2024_09;
ALTER TABLE public.res_partner_partitioned_p2024_10  RENAME TO  res_partner_p2024_10;
ALTER TABLE public.res_partner_partitioned_p2024_11  RENAME TO  res_partner_p2024_11;
ALTER TABLE public.res_partner_partitioned_p2024_12  RENAME TO  res_partner_p2024_12;
ALTER TABLE public.res_partner_partitioned_p2025_01  RENAME TO  res_partner_p2025_01;
ALTER TABLE public.res_partner_partitioned_p2025_02  RENAME TO  res_partner_p2025_02;
ALTER TABLE public.res_partner_partitioned_p2025_03  RENAME TO  res_partner_p2025_03;
ALTER TABLE public.res_partner_partitioned_p2025_04  RENAME TO  res_partner_p2025_04;
ALTER TABLE public.res_partner_partitioned_p2025_05  RENAME TO  res_partner_p2025_05;
ALTER TABLE public.res_partner_partitioned_p2025_06  RENAME TO  res_partner_p2025_06;
ALTER TABLE public.res_partner_partitioned_p2025_07  RENAME TO  res_partner_p2025_07;
ALTER TABLE public.res_partner_partitioned_p2025_08  RENAME TO  res_partner_p2025_08;
ALTER TABLE public.res_partner_partitioned_p2025_09  RENAME TO  res_partner_p2025_09;
ALTER TABLE public.res_partner_partitioned_p2025_10  RENAME TO  res_partner_p2025_10;
ALTER TABLE public.res_partner_partitioned_p2025_11  RENAME TO  res_partner_p2025_11;
ALTER TABLE public.res_partner_partitioned_p2025_12  RENAME TO  res_partner_p2025_12;
ALTER TABLE public.res_partner_partitioned_p2026_01  RENAME TO  res_partner_p2026_01;
ALTER TABLE public.res_partner_partitioned_p2026_02  RENAME TO  res_partner_p2026_02;
ALTER TABLE public.res_partner_partitioned_p2026_03  RENAME TO  res_partner_p2026_03;

ALTER TABLE public.res_partner ATTACH PARTITION public.res_partner_default DEFAULT;

COMMIT;

ERROR:  partition constraint is violated by some row
SQL state: 23514

What could be the problem as the template table equally doesn't have CONSTRAINTS?

**Comment by keithf4** [comment]
So i haven't tried running the code yet, but reviewing the steps contained in the Online Partitioning guide, this statement may be relevant

https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman_howto_native.md#online-partitioning

```
The tricky part here is that we cannot yet have any child tables in the partition set that match data that currently exists in the original table. 
```
It looks like when you called `create_parent()`, you set the premake to 52. You actually don't want any child partitions created yet, especially for the time period of data that exists in the current child table. When it's trying to add your original table as the default table, it may be seeing that a child table already exists for the data that is in your "default". There's another sentence further in the same paragraph that may have been misread
```
So, with the below create_parent() call, we're going to start the partition set well ahead of the data we inserted.
```
The key word here is `ahead`. You've started your partition set's children far in the past, likely for data that already exists in the original. You can see in the example in those docs, the premake is also only `1`. 

So, I'd recommend redoing this and trying to follow that guide a little more closely. Mainly, you don't want to have any child tables to exist that would contain any current data. There is a step later that will move that data out of the default and create the child table as needed.

**Comment by keithf4** [comment]
Also make note that the `p_inherit_fk` option is only relevant for trigger-based partitioning or if you're using PG 10.  For PG11+, foreign key inheritance is automatically managed. If you're trying to partition on PG10, I would highly encourage you to upgrade to a later version to make it much easier to manage.

**Comment by BundeAmos** [comment]
> Also make note that the `p_inherit_fk` option is only relevant for trigger-based partitioning or if you're using PG 10. For PG11+, foreign key inheritance is automatically managed. If you're trying to natively partition on PG10, I would highly encourage you to upgrade to a later version to make it much easier to manage.

Thanks Keith

**Comment by keithf4** [comment]
Closing this issue for now. If you have any further questions feel free to re-open it.
