### ISSUE TITLE
drop_partition_time error: missing FROM-clause entry

### ISSUE THREAD

**Issue by rostamiani** [pgpartman/pg_partman#407]
When running `partman.drop_partition_time` command there is an error:
```
# select partman.drop_partition_time(public.session_by_date);
ERROR:  missing FROM-clause entry for table "public"
LINE 1: select partman.drop_partition_time(public.session_by...
                                           ^
```
And if I execute without schema address there is no entry because I added the table with it's schema:
```
# select partman.drop_partition_time(session_by_date);
ERROR:  column "session_by_date" does not exist
LINE 1: select partman.drop_partition_time(session_by_date);
                                           ^
```

I'm using partman 4.6.0 and Postgres 12.9

**Comment by keithf4** [comment]
You have to single-quote parameter values to a function. And it must be schema qualified in this case as well.

`select partman.drop_partition_time('public.session_by_date`);'
