### ISSUE TITLE
create_partition_time creates tables with incorrect constraints

### ISSUE THREAD

**Issue by josharrington** [pgpartman/pg_partman#420]
I've discovered a bug where the create_partition_time function will create a table with incorrect constraints. I've verified this occurs on native and partman partitioned tables.

Versions:

```
postgres=# SELECT version();
                                        version
---------------------------------------------------------------------------------------
 PostgreSQL 12.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit
(1 row)

postgres=# \dx
                                            List of installed extensions
          Name          | Version |   Schema   |                             Description
------------------------+---------+------------+---------------------------------------------------------------------
 fuzzystrmatch          | 1.1     | public     | determine similarities and distance between strings
 hstore                 | 1.6     | public     | data type for storing sets of (key, value) pairs
 pg_partman             | 4.6.0   | public     | Extension to manage partitioned tables by time or ID
 plpgsql                | 1.0     | pg_catalog | PL/pgSQL procedural language
 postgis                | 3.0.1   | public     | PostGIS geometry, geography, and raster spatial types and functions
 postgis_tiger_geocoder | 3.0.1   | tiger      | PostGIS tiger geocoder and reverse geocoder
 postgis_topology       | 3.0.1   | topology   | PostGIS topology spatial types and functions
(7 rows)
```

To recreate:

```sql
create table timeseries_test_native(time timestamptz not null, data text) partition by range (time);
select create_parent('public.timeseries_test_native', 'time', 'native', 'monthly', p_start_partition := '2021-01-01');
select create_partition_time('public.timeseries_test_native', array(select '2022-12-02 12:01'::timestamptz), true, null);
```

This will create a parent table and several child tables, some created with `create_parent` and one created with `create_partition_time` in the future (2022-12 in this case):

```
...
 public | timeseries_test_native_p2022_02        | table             | postgres
 public | timeseries_test_native_p2022_03        | table             | postgres
 public | timeseries_test_native_p2022_04        | table             | postgres
 public | timeseries_test_native_p2022_05        | table             | postgres
 public | timeseries_test_native_p2022_12        | table             | postgres
...
```

When inspecting the constraints, we see there's a 12 hour mismatch between the two ways the tables were created:

```
postgres=# \d+ timeseries_test_native_p2022_05
                               Table "public.timeseries_test_native_p2022_05"
 Column |           Type           | Collation | Nullable | Default | Storage  | Stats target | Description
--------+--------------------------+-----------+----------+---------+----------+--------------+-------------
 time   | timestamp with time zone |           | not null |         | plain    |              |
 data   | text                     |           |          |         | extended |              |
Partition of: timeseries_test_native FOR VALUES FROM ('2022-05-01 00:00:00+00') TO ('2022-06-01 00:00:00+00')
Partition constraint: (("time" IS NOT NULL) AND ("time" >= '2022-05-01 00:00:00+00'::timestamp with time zone) AND ("time" < '2022-06-01 00:00:00+00'::timestamp with time zone))
Access method: heap

postgres=# \d+ timeseries_test_native_p2022_12
                               Table "public.timeseries_test_native_p2022_12"
 Column |           Type           | Collation | Nullable | Default | Storage  | Stats target | Description
--------+--------------------------+-----------+----------+---------+----------+--------------+-------------
 time   | timestamp with time zone |           | not null |         | plain    |              |
 data   | text                     |           |          |         | extended |              |
Partition of: timeseries_test_native FOR VALUES FROM ('2022-12-02 12:01:00+00') TO ('2023-01-02 12:01:00+00')
Partition constraint: (("time" IS NOT NULL) AND ("time" >= '2022-12-02 12:01:00+00'::timestamp with time zone) AND ("time" < '2023-01-02 12:01:00+00'::timestamp with time zone))
Access method: heap
```

This caused a bit of a surprise for us in our production database as we needed to precreate some tables to ensure no disruption occured over the holiday and we could preconfigure fivetran to pull those tables in (we have recently automated this so hopefully never again).

**Comment by josharrington** [comment]
I somehow missed that the start time of the constraint is the same as the time I put in the create_partition_time. I guess my question is if this is intended behavior? I had made a (possibly poor) assumption that the partition _for_ the time provided rather than starting on that time and running for a month (and runs over the partition limit).

**Comment by keithf4** [comment]
Yeah, the create_partition_time() function generally isn't called directly and there's a note of that in the documentation. And it uses the exact value given to it for boundary values to be able to support any possible interval that may be in use. Since your interval is greater than 1 day, you're not going to want that boundary to be anything except exactly midnight (`00:00:00`).

If you're trying to have partitions created further out than the default 4, I'd recommend increasing the premake value. That will ensure all intervening child tables are also created as needed. As it is now, you have a large gap that has to be filled as well and any data between May and Dec will go to the default and have to be cleaned up. Also maintenance will not automatically fill that gap (there is a function to do that for you but it has to be run manually). Maintenance only makes new partitions based on whatever the highest boundary child that exists.

**Comment by josharrington** [comment]
Gotcha. It could be useful to add that note to that function in the doc. My expectation was for the date provided to create a table that would appropriately contain the record that would have been created with that date with the appropriate constraints. In the actual case, I need to be aware of the partition interval prior to running create_partition_time.

In our case, we have a partitioned table where sometimes we will insert items for months in the future. This gives us gaps in the tables (like above) and the maintenance task is unable to fill in the tables. We run `partition_data_time` on an interval to ensure those missing tables are created promptly when it rolls over. 

However, we are also syncing data via Fivetran. Fivetran does not have a way to automatically include a subset of tables, only _all_ tables or some manually selected tables. Because the tables didn't exist due to the gap issue, I created them manually in advance using `partition_data_time` and selected them in Fivetran to avoid interruption over the holidays. 

To be clear, I have no expectations for this issue. I think it is valuable to make clear the limitations. I greatly appreciate all the work you have put in and the support you have generously provided during my time using your project. Thank you!

**Comment by keithf4** [comment]
If you're partitioning by month, I wouldn't see any harm in setting the premake to 12 or even 24 to allow up to two years in advance to catch out of bound data. Then you don't even have to worry about a manual partition_data run. The tables are empty so they have very minimal impact on performance, especially if you're on PG12+ where partition pruning was implemented.

The first time it runs, it will pre-create a lot of partitions. But after that, it's still only ever creating one new partition at a time since it's just trying to keep at least that many made from that point forward.

**Comment by josharrington** [comment]
Thank you! Closing

**Comment by keithf4** [comment]
No problem. If you have any issues with premaking tables that far out, please let me know. So far that's worked well for people that need to deal with frequent out-of-bound data.

Thank you!
