### ISSUE TITLE
Archiving function/script call when maintenance dropping partition?

### ISSUE THREAD

**Issue by dtseiler** [pgpartman/pg_partman#426]
I'm looking to set up an archiving function so that data from the oldest partition is dumped and pushed to cold storage before its partition is dropped during bgw maintenance. I had believed that pg_partman supported some sort of way to specify to execute a function or system command (eg to call an executable script or go app etc) that would be run prior to dropping a partition, however now I can't find this in the documentation. I'm not sure if it was all just a fever dream.

The closest thing I can find is this blurb from the Crunchy version documentation:

> There is also a method available to dump the tables out if they don’t need to be in the database anymore but still need to be kept.

FWIW, I'm on PG 12, pg_partman 4.6.0 using native range (date) partitioning.

**Comment by keithf4** [comment]
This script can be used to dump any tables contained within a given schema. It can also be set to drop the table after it has completed the dump successfully. Should be installed when you run `make` or with whatever package you use.

https://github.com/pgpartman/pg_partman/blob/master/bin/common/dump_partition.py

There's nothing in pg_partman itself that will set this up to automatically happen. You will have to schedule this. What normal partman maintenance can do is move child tables to the schema that this script will target.

**Comment by keithf4** [comment]
https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman.md#scripts

**Comment by dtseiler** [comment]
OK so in lieu of that script I'm fine having my own script do a pg_dump and push to cloud storage ahead of time (via crontab) and then just let the partman background worker drop the partition as normal.
