### ISSUE TITLE
Difficult to create tests of pg_partman partitioning application

### ISSUE THREAD

**Issue by andylowry-turbo** [pgpartman/pg_partman#428]
Using pg_partman v4.6.0 and postgres v13.5

As far as I can tell, many `pg_partman` maintenance operations are based on current value of the system clock. This makes it difficult to create effective tests of applications that use pg_partman, where partition intervals are likely to be much too long for a live test to be feasible. One would have to contract intervals dramatically for the test in order to reduce the test duration, and probably also alter timestamps generated by the code under test to fit in the narrow intervals.

A far better approach would be possible if `pg_partman` were to support a mode in which the clock used is one controlled by the test code rather than the system clock.

For example, perhaps there could be a new parameter to set the clock as part of the initial `create_parent` call. Doing this would mean that whenever `pg_partman` operated on that parent table, it would use the alternate clock time rather than the system clock. If the clock value were made a column of `part_config`, a non-null value could indicate this mode of operation, and the test code could update the table row at any time to advance the clock as needed for the test.

(Even with the column in `part_config` it would still be important to include the initial clock value in `create_parent` call because otherwise that call will create partitions based on the system clock.)

**Comment by keithf4** [comment]
If you take a look in the test folder, I make use of the pgtap test suite to do various tests. You can simulate partition creation in several ways. You can set the starting partition to be further in the past and then gradually insert data so that the next maintenance run keeps up and makes new partitions based on that data. Or you can adjust the premake value to force pg_partman to make new partitions at any time.

**Comment by andylowry-turbo** [comment]
Thanks, I'll take a look!

**Comment by keithf4** [comment]
Sure. If I ever need some other testing methods, though, I'll keep this in mind. Thanks for the suggestion!
