### ISSUE TITLE
Missing procedures in Azure

### ISSUE THREAD

**Issue by jarrettprosser** [pgpartman/pg_partman#444]
Howdy,

Figuring this is an Azure issue rather than a partman issue, but I thought I'd double check.

When I deploy an Azure database for Postgres Flexible Server (12.8, or 13.4) and enable `pg_partman` (4.5.0), I can create the extension, but none of the procedures are included. This includes `run_maintenance_proc`, which I want to run as a cronjob with `pg_cron`.

I checked with a query to list functions in the schema. 
```
SELECT format('%I.%I(%s)', ns.nspname, p.proname, oidvectortypes(p.proargtypes)) 
FROM pg_proc p INNER JOIN pg_namespace ns ON (p.pronamespace = ns.oid)
WHERE ns.nspname = 'partman' order by format;
```
In the Azure database, I get: 
```
partman.apply_cluster(text, text, text, text)
partman.apply_constraints(text, text, boolean, bigint)
partman.apply_foreign_keys(text, text, bigint, boolean)
partman.apply_privileges(text, text, text, text, bigint)
partman.apply_publications(text, text, text)
partman.autovacuum_off(text, text, text, text)
partman.autovacuum_reset(text, text, text, text)
partman.check_automatic_maintenance_value(text)
partman.check_control_type(text, text, text)
partman.check_default(boolean)
partman.check_epoch_type(text)
partman.check_name_length(text, text, boolean)
partman.check_partition_type(text)
partman.check_subpart_sameconfig(text)
partman.check_subpartition_limits(text, text)
partman.create_function_id(text, bigint)
partman.create_function_time(text, bigint)
partman.create_parent(text, text, text, text, text[], integer, text, text, boolean, text, text, text[], boolean, text, boolean)
partman.create_partition_id(text, bigint[], boolean, text)
partman.create_partition_time(text, timestamp with time zone[], boolean, text)
partman.create_sub_parent(text, text, text, text, text, text[], integer, text, boolean, text, text, boolean, boolean)
partman.create_trigger(text)
partman.drop_constraints(text, text, boolean)
partman.drop_partition_column(text, text)
partman.drop_partition_id(text, bigint, boolean, boolean, text)
partman.drop_partition_time(text, interval, boolean, boolean, text)
partman.dump_partitioned_table_definition(text, boolean)
partman.inherit_template_properties(text, text, text)
partman.partition_data_id(text, integer, bigint, numeric, text, boolean, text, text[])
partman.partition_data_time(text, integer, interval, numeric, text, boolean, text, text[])
partman.partition_gap_fill(text)
partman.reapply_privileges(text)
partman.run_maintenance(text, boolean, boolean)
partman.show_partition_info(text, text, text)
partman.show_partition_name(text, text)
partman.show_partitions(text, text, boolean)
partman.stop_sub_partition(text, boolean)
partman.undo_partition(text, integer, text, boolean, numeric, text, text[])
```
This doesn't include any of the `_proc` functions. In an RDS database, I get all of those, and the additional procedures:
```
partman.partition_data_proc(text, text, integer, integer, text, text, integer, integer, boolean, text[])
partman.reapply_constraints_proc(text, boolean, boolean, integer, boolean)
partman.run_maintenance_proc(integer, boolean, boolean)
partman.undo_partition_proc(text, text, integer, integer, text, boolean, integer, integer, boolean, text[])
```

Is this a known limitation of Azure Postgres? I haven't been able to find any documentation on it. 

Thanks!

**Comment by keithf4** [comment]
Unfortunately I don't have any control of what extensions or what version of those extensions are included in Azure, RDS or any SaaS database provider. So you'll likely have to ask their support.

There is currently an issue where if you had pg_partman installed on a version of PG before procedures were supported (prior to 11), then upgrade to a newer version of PG that does, the procedures won't be there (https://github.com/pgpartman/pg_partman/issues/343). I'm still trying to work on a fix for that. But I'd be surprised if that's the issue here. Especially if it's a brand new database.

**Comment by jarrettprosser** [comment]
Thanks Keith. I've also created an Azure support ticket to follow this up, they've confirmed they are seeing the same issue in their test database, so they're chasing it down now. Good to know about #343, I'll pass that on in case it is related somehow. As you say, seems unlikely given this was a brand new PG12/13 database. I'll drop updates in here for future travellers.
