### ISSUE TITLE
Oldest partition retention

### ISSUE THREAD

**Issue by visciang** [pgpartman/pg_partman#446]
From the retention specification chapter (https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman.md#retention):

> Retention
> If you don't need to keep data in older partitions, a retention system is available to automatically drop unneeded child partitions. By default, they are only uninherited/detached not actually dropped, but that can be configured if desired. There is also a method available to dump the tables out if they don't need to be in the database anymore but still need to be kept. To set the retention policy, enter either an interval or integer value into the retention column of the part_config table. <ins>For time-based partitioning, the interval value will set that any partitions containing only data older than that will be dropped</ins>. For id-based partitioning, the integer value will set that any partitions with an id value less than the current maximum id value minus the retention value will be dropped. For example, if the current max id is 100 and the retention value is 30, any partitions with id values less than 70 will be dropped. The current maximum id value at the time the drop function is run is always used. Keep in mind that for subpartition sets, when a parent table has a child dropped, if that child table is in turn partitioned, the drop is a CASCADE and ALL child tables down the entire inheritance tree will be dropped. Also note that a partition set managed by pg_partman must always have at least one child, so retention will never drop the last child table in a set.

What I would expect is that if we have an "oldest partition" half outside the retention interval and half inside the retention interval the retention policy would not drop the partition.

Example:
```sql
create schema partman;
create extension pg_partman with schema partman;

create table z(t timestamptz) partition by range (t);
select partman.create_parent(
    p_parent_table => 'public.z',
    p_control => 't',
    p_type => 'native',
    p_interval => 'monthly',
    p_start_partition => (now() - interval '3 years')::text
);
```

Given that today is 2022-03-16, this lead to (as expected):

```
\d+
                                       Partitioned table "public.z"
 Column |           Type           | Collation | Nullable | Default | Storage | Stats target | Description 
--------+--------------------------+-----------+----------+---------+---------+--------------+-------------
 t      | timestamp with time zone |           |          |         | plain   |              | 
Partition key: RANGE (t)
Partitions: z_p2019_03 FOR VALUES FROM ('2019-03-01 00:00:00+00') TO ('2019-04-01 00:00:00+00'),
            z_p2019_04 FOR VALUES FROM ('2019-04-01 00:00:00+00') TO ('2019-05-01 00:00:00+00'),
            z_p2019_05 FOR VALUES FROM ('2019-05-01 00:00:00+00') TO ('2019-06-01 00:00:00+00'),
...
```

Let's apply a retention policy of 3 years:

```sql
update partman.part_config
set infinite_time_partitions = true,
    retention = '3 years',
    retention_keep_table = false
where parent_table = 'public.z';

call partman.run_maintenance_proc();
```

what we have now is:

```
                                       Partitioned table "public.z"
 Column |           Type           | Collation | Nullable | Default | Storage | Stats target | Description 
--------+--------------------------+-----------+----------+---------+---------+--------------+-------------
 t      | timestamp with time zone |           |          |         | plain   |              | 
Partition key: RANGE (t)
Partitions: z_p2019_04 FOR VALUES FROM ('2019-04-01 00:00:00+00') TO ('2019-05-01 00:00:00+00'),
            z_p2019_05 FOR VALUES FROM ('2019-05-01 00:00:00+00') TO ('2019-06-01 00:00:00+00'),
...
```

Parition `z_p2019_03 FOR VALUES FROM ('2019-03-01 00:00:00+00') TO ('2019-04-01 00:00:00+00')` has been dropped.

I'm a misreading the retention specification ?
I would expect this partition to be dropped only after it completelly falls out of the retention period.

Thank you

**Comment by keithf4** [comment]
So if the partition interval is monthly, that is what it is basing the retention on. It's not looking at anything more fine-grained than that at this time. March 2019 is 3 years ago so that is what it will drop. If you need it to be more fine grained as far as data retention, you'll have to lower the interval. In this case if you wanted it to not remove data after March 16th, it would need to be partitioned daily.

I think I looked at this in the past trying to account for data retention at a level lower than the partition interval. But that is adding additional processing time looking for at least one row that exists. Also, at what granularity do you consider it "old" then? By the day, by the hour, by the minute? Starts to get a bit tricky.

**Comment by visciang** [comment]
@keithf4 thank you for the prompt answer.

So I'n misreading:
For time-based partitioning, the interval value will set that any partitions containing only data older than that will be dropped.

specifically the "containing only data older than".

My understanding, intuitively, is that the retention should keep 2019-03 and drop only from 2019-02 include backward.

In other words, if the last partition falls in the middle of the retention interval it would be "safer" to keep it rather than drop it since some data there is in the retention.

Thank you

**Comment by keithf4** [comment]
Actually, I'm looking at the code for this again, and I think you're interpretation is right and that is what I intended

https://github.com/pgpartman/pg_partman/blob/master/sql/functions/drop_partition_time.sql#L151

I'll have to see what's going on here.

**Comment by keithf4** [comment]
Yeah, apologies for the confusion. Forget what my own code does sometimes and I'm at least glad when it turns out I was consistent in my docs and the code. :)

So here's the comparison that ends up happening with March 2019 and a 3 year interval. The table should only be dropped when the resulting interval is GREATER than the retention interval.
```
keith@keith=# select '2022-03-16 18:19:14.402523-04'::timestamptz - ('2019-04-01 00:00:00-04'::timestamptz);
         ?column?          
---------------------------
 1080 days 18:19:14.402523
(1 row)
Time: 2.410 ms

keith@keith=# select '3 years'::interval < '1080 days 18:19:14.402523'::interval;
 ?column? 
----------
 t
(1 row)

Time: 4.319 ms
```
That's simply not right. Taking out the hours/minutes/seconds from that interval turns into
```
keith@keith=# select '3 years'::interval < '1080 days'::interval;
 ?column? 
----------
 f
(1 row)

Time: 2.463 ms
```
Trying to find out what's going on with interval comparisons internally here.

**Comment by keithf4** [comment]
So this has to do with the imprecision of how intervals are stored internally in PG. As far as an interval is concerned, a month is 30 days and a year is 12 months. So `30*12*3 = 1080` days exactly.

If you're trying to be more precise with larger retention values, looks like you will have to give the explicit number of days as far as you would realistically interpret them. So 365 days * 3 would be 1095 days.

Doing this
```
update partman.part_config
set infinite_time_partitions = true,
    retention = '1095 days',
    retention_keep_table = false
where parent_table = 'public.z';
```
Then running maintenance, it works as you would expect it.  There's some vague explanations as to this imprecision with intervals in the PG docs here - https://www.postgresql.org/docs/14/datatype-datetime.html  But talking with a coworker that knows the internals better is the only way I was able to figure this one out.

I'll update the docs with some info on this. Thanks for reporting it!

**Comment by visciang** [comment]
Thank you very much @keithf4 
Stepping down to "days" for the retention configuration is definitely the right this.
months / years are not defined without a calendar context

**Comment by keithf4** [comment]
@visciang 

Version 4.6.1 has been released and there's actually a fix for this in there now so you should actually be able to set your retention to 3 years and it will calculate it accurately. Had some help from @sfrost on this one and he clarified that if you just use the interval to calculate a date based on an actual timestamp value (vs just using the raw interval value), PostgreSQL is smart enough to figure things out properly then.
