### ISSUE TITLE
run_maintenance_proc() does not create new partitions

### ISSUE THREAD

**Issue by s3dse** [pgpartman/pg_partman#449]
I have some monthly partitioned tables that are configured to pre-make 4 partitions. Data is inserted every day and partition maintenance is run every first day of a month. Calling `run_maintenance_proc()` worked for all of the tables until 1st of April. On that day for some of the tables no new partitions were created and I got the following error message:

    Exception in thread "main" org.postgresql.util.PSQLException: ERROR: Child table given does not exist (<NULL>)
    CONTEXT: PL/pgSQL function show_partition_info(text,text,text) line 38 at RAISE
    SQL statement "SELECT child_start_time                                              FROM     partman.show_partition_info(v_parent_schema||'.'||v_last_partition, v_row.partition_interval, v_row.parent_table)"
    PL/pgSQL function partman.run_maintenance(text,boolean,boolean) line 196 at SQL statement
    SQL statement "SELECT partman.run_maintenance('features2.product_clicks_with_category', p_jobmon := 't')"
    PL/pgSQL function partman.run_maintenance_proc(integer,boolean,boolean) line 42 at EXECUTE
    DETAIL: 
    HINT: 
      Where: PL/pgSQL function partman.run_maintenance(text,boolean,boolean) line 402 at RAISE
    SQL statement "SELECT partman.run_maintenance('features2.product_clicks_with_category', p_jobmon := 't')"
    PL/pgSQL function partman.run_maintenance_proc(integer,boolean,boolean) line 42 at EXECUTE

To fix the error, I set infinite_time_partitions to `true`, but when I call `run_maintenance_proc()` I still get the same error message.
Do I miss something?

I use pg_partman 4.5.1 on cloud-sql Postgres 13.

**Comment by keithf4** [comment]
Not a problem. Glad I was able to help narrow down the issue.

**Comment by alifengineer** [comment]
> Can you share the schema of your table and the `part_config` entry for this partition set?

insert into public.part_config (parent_table, control, partition_type, partition_interval, constraint_cols, premake, optimize_trigger, optimize_constraint, epoch, inherit_fk, retention, retention_schema, retention_keep_table, retention_keep_index, infinite_time_partitions, datetime_string, automatic_maintenance, jobmon, sub_partition_set_full, undo_in_progress, trigger_exception_handling, upsert, trigger_return_null, template_table, publications, inherit_privileges, constraint_valid, subscription_refresh, drop_cascade_fk, ignore_default_data)
values  ('public.payments', 'created_at', 'native', '1 mon', null, 1, 4, 30, 'none', true, null, null, true, true, false, 'YYYY_MM', 'on', true, false, false, false, '', true, 'public.template_public_payments', null, false, tr

show_partions: ![Снимок экрана 2024-03-19 в 10 58 46](https://github.com/pgpartman/pg_partman/assets/132895624/ed3035af-7991-442b-9676-9f5c72047cc8)
ue, null, false, false);

after run_maintenance('public.payments'); not created any parmitions

**Comment by alifengineer** [comment]
> > Can you share the schema of your table and the `part_config` entry for this partition set?
> 
> ```sql
> insert into public.part_config (parent_table, control, partition_type, partition_interval, constraint_cols, premake, optimize_trigger, optimize_constraint, epoch, inherit_fk, retention, retention_schema, retention_keep_table, retention_keep_index, infinite_time_partitions, datetime_string, automatic_maintenance, jobmon, sub_partition_set_full, undo_in_progress, trigger_exception_handling, upsert, trigger_return_null, template_table, publications, inherit_privileges, constraint_valid, subscription_refresh, drop_cascade_fk, ignore_default_data)
> values  ('public.payments', 'created_at', 'native', '1 mon', null, 1, 4, 30, 'none', true, null, null, true, true, false, 'YYYY_MM', 'on', true, false, false, false, '', true, 'public.template_public_payments', null, false, true, null, false, false);
> ```
> 
> show_partitions: ![Снимок экрана 2024-03-19 в 10 58 46](https://private-user-images.githubusercontent.com/132895624/313938751-ed3035af-7991-442b-9676-9f5c72047cc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mjg0MTEsIm5iZiI6MTcxMDgyODExMSwicGF0aCI6Ii8xMzI4OTU2MjQvMzEzOTM4NzUxLWVkMzAzNWFmLTc5OTEtNDQyYi05Njc2LTlmNWM3MjA0N2NjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwNjAxNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGY1NDA3MGVhZjkwMjBkOWU0ZGEzZTE3NjRlODIxMmI3MjNmNmY4ZjI0ZjFmYTYyOTM2ZDNhOGIwMzlmYmY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H_NM2_Nh4TECDIuPsif78eN7JSoLZsCyU2I5NCEakQs)
> 
> after run_maintenance('public.payments') partitions doesn't created

Can any help me please ? 🙏

**Comment by keithf4** [comment]
@alifengineer unless you are seeing the same errors as this person reported, please open a new issue. Also please browse through existing closed issues for people that have reported the same problem of new partitions not being made to see if they may solve your issue

**Comment by alifengineer** [comment]
> @alifengineer unless you are seeing the same errors as this person reported, please open a new issue. Also please browse through existing closed issues for people that have reported the same problem of new partitions not being made to see if they may solve your issue

Thanks, problem is solved. 

I have another one question, 

![telegram-cloud-document-2-5192870332813296258](https://github.com/pgpartman/pg_partman/assets/132895624/d701ba32-535f-40d7-80d9-0e9e722d4699)

Why in that case after canceling request advisory block left ? If i close this client connection and open new new connection it will run without problem. Advisory block also removed.

**Comment by keithf4** [comment]
That is how advisory locks work. 

https://www.postgresql.org/docs/16/explicit-locking.html#ADVISORY-LOCKS

Due to it being a procedure and not a regular function, the maintenance procedure takes out a non-transactional, session level advisory lock that must be manually closed to be run again within the same session. That manual close is at the end of the procedure which you've cancelled before it finishes. If you allow it to finish it will cleanly release the advisory lock. Non-transactional advisory locks are based on the session so if you close the session it automatically releases it.
