### ISSUE TITLE
partman.create_parent error ERROR:  partition "testpartition_w_p2022w16" would overlap partition "testpartition_w_p220404"

### ISSUE THREAD

**Issue by beginpgsql** [pgpartman/pg_partman#452]
Hi All,

We are in process of migrating data from oracle to managed postgres and trying to automate partition process and we already have the partitioned tables with partition.

While try to automate through partman i m getting error as partition is overlapping with existing partition.
Sharing the details to reproduce the senario. Consider the public.testpartition_w_P220404 already exists.

CREATE TABLE public.testpartition_w (
    trx_cache_id bigint NOT NULL,
    trx_cache_vendor_id bigint NOT NULL,
    trx_cache_vendor_name character varying(256) NOT NULL,
    trx_cache_request_id character varying(50) NOT NULL,
    trx_cache_api_type bigint NOT NULL,
    trx_cache_action_type bigint NOT NULL,
    modify_site_id bigint NOT NULL,
    create_date timestamp without time zone NOT NULL,
    modify_date timestamp without time zone NOT NULL,
    modify_user character varying(50) NOT NULL
)
PARTITION BY RANGE (create_date);

ALTER TABLE ONLY public.testpartition_w
    ADD CONSTRAINT pk_testpartition_w PRIMARY KEY (trx_cache_id, trx_cache_request_id, create_date);

CREATE TABLE public.testpartition_w_P220404 PARTITION OF public.testpartition_w FOR VALUES FROM ('2022-04-19 00:00:00') TO ('2022-04-27 00:00:00');

postgres=> \d+ public.testpartition_w
                                          Partitioned table "public.testpartition_w"
        Column         |            Type             | Collation | Nullable | Default | Storage  | Stats target | Description 
-----------------------+-----------------------------+-----------+----------+---------+----------+--------------+-------------
 trx_cache_id          | bigint                      |           | not null |         | plain    |              | 
 trx_cache_vendor_id   | bigint                      |           | not null |         | plain    |              | 
 trx_cache_vendor_name | character varying(256)      |           | not null |         | extended |              | 
 trx_cache_request_id  | character varying(50)       |           | not null |         | extended |              | 
 trx_cache_api_type    | bigint                      |           | not null |         | plain    |              | 
 trx_cache_action_type | bigint                      |           | not null |         | plain    |              | 
 modify_site_id        | bigint                      |           | not null |         | plain    |              | 
 create_date           | timestamp without time zone |           | not null |         | plain    |              | 
 modify_date           | timestamp without time zone |           | not null |         | plain    |              | 
 modify_user           | character varying(50)       |           | not null |         | extended |              | 
Partition key: RANGE (create_date)
Indexes:
    "pk_testpartition_w" PRIMARY KEY, btree (trx_cache_id, trx_cache_request_id, create_date)
Partitions: testpartition_w_p220404 FOR VALUES FROM ('2022-04-19 00:00:00') TO ('2022-04-27 00:00:00')

postgres=> 
postgres=> SELECT partman.create_parent( p_parent_table => 'public.testpartition_w',
postgres(>  p_control => 'create_date',
postgres(>  p_type => 'native',
postgres(>  p_interval=> 'weekly',
postgres(>  p_premake => 3);
ERROR:  partition "testpartition_w_p2022w16" would overlap partition "testpartition_w_p220404"
CONTEXT: SQL statement "ALTER TABLE public.testpartition_w ATTACH PARTITION public.testpartition_w_p2022w16 FOR VALUES FROM ('2022-04-18 00:00:00+00') TO ('2022-04-25 00:00:00+00')"
PL/pgSQL function create_partition_time(text,timestamp with time zone[],boolean,text) line 239 at EXECUTE
PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,text[],boolean,text,boolean) line 473 at assignment
DETAIL: 
HINT: 
CONTEXT: PL/pgSQL function create_partition_time(text,timestamp with time zone[],boolean,text) line 479 at RAISE
PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,text[],boolean,text,boolean) line 473 at assignment
DETAIL: 
HINT: 
CONTEXT:  PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,text[],boolean,text,boolean) line 771 at RAISE
postgres=>

**Comment by keithf4** [comment]
pg_partman does not support child partitions that do not follow its own naming patterns. That is how it keeps track of the current state of the latest child tables existing in order to premake them and also so it knows how to manage retention if dropping old ones.

If you already have child tables for an existing partition set not managed by pg_partman and want to migrate to using pg_partman, you will have to rename them so pg_partman will not try and remake those existing child tables. 

There is some documentation on migrating to pg_partman with an existing set, but it is focused on the old trigger-based method - https://github.com/pgpartman/pg_partman/blob/master/doc/migration_to_partman.md I haven't had a chance to update it for native yet, but the guidance on renaming the tables should still be relevant. I do plan on revisiting this doc as part of the deprecation of trigger-based partitioning - https://github.com/pgpartman/pg_partman/discussions/360

**Comment by keithf4** [comment]
Closing this issue for now. If you are still having issues and need assistance please feel free to re-open it.
