### ISSUE TITLE
Table retention not working

### ISSUE THREAD

**Issue by internetuser2008** [pgpartman/pg_partman#455]
Hello,

Unable to get the settings correctly working for table retention on partitions. Would like to keep the last 7days worth of partitions active and data searchable, any table older than 7days should be dropped and removed from a primary table as well.

When setting "retention_keep_table" to True it drops all tables older than today even when "retention" is set to 7.
What I am missing?

`
Version     | 4.5.1

SELECT partman.create_parent(
  p_parent_table => 'public.test1',
  p_control => 'publishdate',
  p_type => 'native',
  p_interval=> 'daily',
  p_premake => 4,
  p_start_partition => (now() - interval '7 day')::text
 );

 select * from part_config;
-[ RECORD 1 ]--------------+----------------------------------------------
parent_table               | public.test1
control                    | publishdate
partition_type             | native
partition_interval         | 1 day
constraint_cols            |
premake                    | 4
optimize_trigger           | 4
optimize_constraint        | 30
epoch                      | none
inherit_fk                 | t
retention                  | 7
retention_schema           |
retention_keep_table       | t
retention_keep_index       | t
infinite_time_partitions   | f
datetime_string            | YYYY_MM_DD
automatic_maintenance      | on
jobmon                     | t
sub_partition_set_full     | f
undo_in_progress           | f
trigger_exception_handling | f
upsert                     |
trigger_return_null        | t
template_table             | partman.template_public_test1
publications               |
inherit_privileges         | f
constraint_valid           | t
subscription_refresh       |`

**Comment by keithf4** [comment]
The `retention` column value has to be an `interval` value. So for time based partitioning it would be `'7 days'`. The column is a text type but it will cast to the appropriate type for the type of partitioning happening.

So your value of `7` here is getting turned into 7 seconds

```
keith@keith=# select '7'::interval;
 interval 
----------
 00:00:07
(1 row)
```

**Comment by internetuser2008** [comment]
> The `retention` column value has to be an `interval` value for time-based partitioning. So for you it would be `'7 days'`. The column is a text type but it will cast to the appropriate type for the type of partitioning happening.
> 
> So your value of `7` here is getting turned into 7 seconds
> 
> ```
> keith@keith=# select '7'::interval;
>  interval 
> ----------
>  00:00:07
> (1 row)
> ```

Hi, not sure if I understand the issue. Are you stating that ```retention``` should be set to 604,800 sec?

```
select interval '7 day';
 interval
----------
 7 days
```

**Comment by keithf4** [comment]
No, I was just saying that your value of `7` is getting turned into 7 seconds and that's why it's dropping all the tables. For time-based partitioning, the value can be any valid interval value. The value `7 days` would be what you want to set it to.

Just FYI, there was a bug was fixed with this in version 4.6.1 around intervals involving months and years - https://github.com/pgpartman/pg_partman/issues/446

**Comment by internetuser2008** [comment]
Ohk got it. Yes, I did see it in previously closed issues. I am hoping AWS RDS update the extension soon.

**Comment by keithf4** [comment]
If you run into that issue in the mean time, you can get around it by just giving your retention value in days.

**Comment by internetuser2008** [comment]
Awesome thanks for the quick turnaround.
