### ISSUE TITLE
drop_partition_time takes a very long time

### ISSUE THREAD

**Issue by jorenvandeweyer** [pgpartman/pg_partman#459]
When I'm dropping a single partition with `drop_partition_time` it takes around 5-20 minutes to drop the partition. I also have to complete shutdown the application because of the locks that are set.

The partition that i'm trying to drop has around 50 million records. This partition is referenced in an other table (also partitioned) using foreign keys. (this table has around 1 billion records, each partition around 50 million records).

I'm considering dropping the foreign keys and only use indices for the joins in my application. 
_I already tested this with a fork of my database and the function took less than a second without the foreign keys._

I already tried `ALTER TABLE "data_point" DISABLE TRIGGER ALL`, but that gives me an error `ERROR:  permission denied: "RI_ConstraintTrigger_a_2733168" is a system trigger`

Should I just drop those FK's or are there any other better ways to drop old partitions?

**Comment by keithf4** [comment]
If the FK is the thing that is causing the delay in dropping the child table, then I'm not sure of any way to help with this other than making the interval for each child table smaller so there is less data to check when dropping them.

**Comment by jorenvandeweyer** [comment]
We discussed this internally and this is unfortunately not an option, that kind of migration would be to big of a change.

What are the cons of dropping the FK? 
_(data integrity is important but a few missing links would not impact the collected data)_

**Comment by keithf4** [comment]
Actually, thinking about that second option again, it may not work. Since the FK will only be looking at a small portion of all of the potential data it may need to reference. It may work if both tables are partitioned and they only need to reference that other specific portion though.

Very tricky situation with partition sets and foreign keys.

**Comment by jorenvandeweyer** [comment]
In our situation it would work since both tables are partitioned per month, and they always refer to the same month in the other table.
