### ISSUE TITLE
migrating existing partitioned table to pg_partman failed

### ISSUE THREAD

**Issue by akshataraskar** [pgpartman/pg_partman#460]
Hello All,

We are in process of migrating current existing partitioned tables to adapt the partition process using pg_partman.

While trying to automate through the partman create_parent() function, it did not create indexes and FK constraints that are supposed to be created on new partitions as same as existing partitions.
Please find the below scenario. Consider table public.test_gen already exists with partitions that were created by using a custom procedure. 

postgres=# \d+ test_gen_y2022m05d05    ===============>>> OLD PARTITION
                                                         Table "public.test_gen_y2022m05d05"
     Column      |           Type           | Collation | Nullable |                     Default                      | Storage  | Stats target | Description 
xxxx
xxxx
xxxx
xxxx
xxxx

Partition of: test_gen FOR VALUES FROM ('2022-05-05') TO ('2022-05-06')
Partition constraint: ((date IS NOT NULL) AND (date >= '2022-05-05'::date) AND (date < '2022-05-06'::date))
Indexes:
    "test_gen_y2022m05d05_date_country_campaign_id_coale_idx" UNIQUE, btree (date, country, campaign_id, COALESCE(adgroup_id, '-1'::integer), COALESCE(ad_id, '-1'::integer), COALESCE(subpublisher_id, '-1'::integer))
    "test_gen_y2022m05d05_ad_id_idx" btree (ad_id)
    "test_gen_y2022m05d05_adgroup_id_idx" btree (adgroup_id)
    "test_gen_y2022m05d05_app_id_idx" btree (app_id)
    "test_gen_y2022m05d05_campaign_id_idx" btree (campaign_id)
Check constraints:
    "test_gen_clicks_check" CHECK (clicks >= 0)
    "test_gen_impressions_check" CHECK (impressions >= 0)
    "test_gen_installs_check" CHECK (installs >= 0)
Foreign-key constraints:
    "test_gen_y2022m05d05_ad_id" FOREIGN KEY (ad_id) REFERENCES core_generic_ad(id) DEFERRABLE INITIALLY DEFERRED
    "test_gen_y2022m05d05_adgroup_id" FOREIGN KEY (adgroup_id) REFERENCES core_generic_adgroup(id) DEFERRABLE INITIALLY DEFERRED
    "test_gen_y2022m05d05_app_id" FOREIGN KEY (app_id) REFERENCES core_app(id) DEFERRABLE INITIALLY DEFERRED
    "test_gen_y2022m05d05_campaign_id" FOREIGN KEY (campaign_id) REFERENCES core_campaign(id) DEFERRABLE INITIALLY DEFERRED
    "test_gen_y2022m05d05_subpublisher_id" FOREIGN KEY (subpublisher_id) REFERENCES space_subpublisher_app(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED
Triggers:
    test_gen_y2022m05d05_update BEFORE UPDATE ON test_gen_y2022m05d05 FOR EACH ROW EXECUTE PROCEDURE suppress_redundant_updates_trigger()
Options: autovacuum_enabled=false

******************************************************************************************************************************

postgres=# \d+ test_gen_p2022_05_06  =======================>>> NEW PARTITION CREATED USING CREATE_PARENT()
                                                                Table "public.test_gen_p2022_05_06"
     Column      |           Type           | Collation | Nullable |                     Default                      | Storage  | Compression | Stats target | Description 
-----------------+--------------------------+-----------+----------+--------------------------------------------------+----------
xxxx
xxxx
xxxx
xxxx

Partition of: test_gen FOR VALUES FROM ('2022-05-06') TO ('2022-05-07')
Partition constraint: ((date IS NOT NULL) AND (date >= '2022-05-06'::date) AND (date < '2022-05-07'::date))
Check constraints:
    "test_gen_clicks_check" CHECK (clicks >= 0)
    "test_gen_impressions_check" CHECK (impressions >= 0)
    "test_gen_installs_check" CHECK (installs >= 0)
Access method: heap

**Comment by akshataraskar** [comment]
Please find the requested output below. Indexes and FK don't exist on the parent table. 

```postgres=# \d+ test_gen
                                                                Partitioned table "public.test_gen"
     Column      |           Type           | Collation | Nullable |                     Default                      | Storage  | Compression | Stats target | Description 
-----------------+--------------------------+-----------+----------+--------------------------------------------------+----------+-------------+--------------+-------------
 created_at      | timestamp with time zone |           | not null |                                                  | plain    |             |              | 
 date            | date                     |           | not null |                                                  | plain    |             |              | 
 app_id          | integer                  |           | not null |                                                  | plain    |             |              | 
 campaign_id     | integer                  |           | not null |                                                  | plain    |             |              | 
 adgroup_id      | integer                  |           |          |                                                  | plain    |             |              | 
 ad_id           | integer                  |           |          |                                                  | plain    |             |              | 
 subpublisher_id | integer                  |           |          |                                                  | plain    |             |              | 
 country         | character varying(2)     |           | not null |                                                  | extended |             |              | 
 budget_spend    | numeric(12,6)            |           | not null |                                                  | main     |             |              | 
 impressions     | integer                  |           | not null |                                                  | plain    |             |              | 
 clicks          | integer                  |           | not null |                                                  | plain    |             |              | 
 installs        | integer                  |           | not null |                                                  | plain    |             |              | 
 id              | bigint                   |           | not null | nextval('stats_generic_ad_new_id_seq'::regclass) | plain    |             |              | 
Partition key: RANGE (date)
Check constraints:
    "test_gen_clicks_check" CHECK (clicks >= 0)
    "test_gen_impressions_check" CHECK (impressions >= 0)
    "test_gen_installs_check" CHECK (installs >= 0)
Partitions: test_gen_y2019 FOR VALUES FROM ('2019-01-01') TO ('2020-01-01'),
            test_gen_y2020 FOR VALUES FROM ('2020-01-01') TO ('2021-01-01'),
            test_gen_y2021m01 FOR VALUES FROM ('2021-01-01') TO ('2021-02-01'),
            test_gen_y2021m02 FOR VALUES FROM ('2021-02-01') TO ('2021-03-01'),
            test_gen_y2021m03 FOR VALUES FROM ('2021-03-01') TO ('2021-04-01'),
            test_gen_y2021m04 FOR VALUES FROM ('2021-04-01') TO ('2021-05-01'),
            test_gen_y2021m05 FOR VALUES FROM ('2021-05-01') TO ('2021-06-01'),
            test_gen_y2021m06 FOR VALUES FROM ('2021-06-01') TO ('2021-07-01'),
            test_gen_y2021m07 FOR VALUES FROM ('2021-07-01') TO ('2021-08-01'),
            test_gen_y2021m08 FOR VALUES FROM ('2021-08-01') TO ('2021-09-01'),
            test_gen_y2021m09 FOR VALUES FROM ('2021-09-01') TO ('2021-10-01'),
            test_gen_y2021m10 FOR VALUES FROM ('2021-10-01') TO ('2021-11-01'),
            test_gen_y2021m11 FOR VALUES FROM ('2021-11-01') TO ('2021-12-01'),
            test_gen_y2021m12 FOR VALUES FROM ('2021-12-01') TO ('2022-01-01'),
            test_gen_y2022m01 FOR VALUES FROM ('2022-01-01') TO ('2022-02-01'),
            test_gen_y2022m02 FOR VALUES FROM ('2022-02-01') TO ('2022-03-01')```

**Comment by keithf4** [comment]
Closing this issue for now. If you still need further assistance, please feel free to reopen.
