### ISSUE TITLE
pg_jobmon stopped working with 4.6.1

### ISSUE THREAD

**Issue by Dakotah312** [pgpartman/pg_partman#461]
I am working on implementing jobmon with partman and had everything connected and working. I then saw that v4.6.1 was released so I upgraded to it. with no other changes I get a 
`"server process (PID #) was terminated by signal 11: Segmentation fault"`.
With no logs or detail as to why. 
This happens when trying to run create_parent().
I have tested switching back and forth between versions and v4.6.0 continues to work.
On version v1.4.1 for jobmon

**Comment by keithf4** [comment]
Does appear to be a bug here. Something around the changes I did to handling search paths. Investigating now.

**Comment by keithf4** [comment]
Found the issue. Will work on a bug fix. Thank you for reporting this!

**Comment by keithf4** [comment]
Below is a gist with an update file to fix this issue. If you're able to run this on a test system, or still easily able to roll back as you did before, I'd appreciate a quick test. If not, I'll continue my testing and hopefully have an update out this week.

https://gist.github.com/keithf4/7ece82af0871915a4da2b3c21b9a4bc1

**Comment by keithf4** [comment]
Great! Thank you. I'll continue working the update to try and get this out soon.

**Comment by keithf4** [comment]
I've released version 4.6.2 with this bug fix. Thank you for reporting it!

**Comment by Dakotah312** [comment]
Thanks for the quick responses and release!
