### ISSUE TITLE
On retention copy data to different table and then drop.

### ISSUE THREAD

**Issue by kegel2904** [pgpartman/pg_partman#466]
I have a table partitioned by hour which I want to have for only the last 7 days so that my calculations are as fast as possible. I have another partitioned table which is the same as this one but is partitioned by week and holds data for last 6 months.
When the retention time for hourly partitioned table comes, I want to copy the data into weekly partitioned one and drop the hourly partitioned one.
The issue is that if I only detach the partition then I cannot drop it after 6 months. But I want to detach when 7 days period is over so that my calculations still only use certain amount of data and to have fewer checks done when selecting, inserting the data.
Is something like this built in or should I write my own process for this?

**Comment by keithf4** [comment]
Do you have any other questions around this issue? Otherwise will close this during my next issue review.

**Comment by keithf4** [comment]
Closing this issue for now. Please feel free to reopen if you have further questions.
