### ISSUE TITLE
How to install pg_partman in Windows 10?

### ISSUE THREAD

**Issue by gsrirangan** [pgpartman/pg_partman#477]
I'm tryin to create extension in PostgreSql running in Windows 10. I see documentation for other OS but not for Windows. Any help is appreciated.

**Comment by keithf4** [comment]
I do not do development on Windows myself at this time. There are several closed issues on this. Maybe some of them can help?

https://github.com/pgpartman/pg_partman/issues?q=is%3Aissue+is%3Aclosed+windows

**Comment by keithf4** [comment]
Will be closing this issue during my next review. Hopefully one of those other issues was able to assist.
