### ISSUE TITLE
Large Default Partition Question

### ISSUE THREAD

**Issue by dtseiler** [pgpartman/pg_partman#479]
Just read this note from the HOWTO:

> The next step is to partition the data out of the default. You DO NOT want to leave data in the default partition set for any length of time and especially leave any significant amount of data. If you look at the constraint that exists on a partitioned default, it is basically the anti-constraint of all other child tables. And when a new child table is added, PostgreSQL manages updating that default constraint as needed. But it must check if any data that should belong in that new child table already exists in the default. If it finds any, it will fail. But more importantly, it has to check EVERY entry in the default which can take quite a long time even with an index if there are billions of rows. During this check, there is an exclusive lock on the entire partition set.

We were hoping to do just that. Basically swap the old table in for the default partition and then leave it until we can finally just truncate it. This table current does not delete/drop any old data but that is being considered as part of the partitioning move.

I'm wondering if we would avoid any locking if we simply pre-created many child tables into the future (i.e. enough to get us past the point of truncating the default partition). Once we get that default partition cleared out, we could set a reasonable `premake` and enable automatic maintenance. Or would there be a massive locking event when we swapped in the old table for the default partition, even with the child tables already in place?

**Comment by keithf4** [comment]
The main issue with the default table having a lot of data is when adding new child tables. If you're not going to be adding any new child tables for the entire duration that the default will be around then, no, there should be no issues with it.

At the time you're dropping the old one, you could just detach it then add a normal default. It may need an exclusive lock to add that default, but as long as it's able to do so without waiting on getting that lock, it should be a quick operation as far as I understand.

**Comment by dtseiler** [comment]
Sounds good, thanks much. My early plan is just to truncate the default partition. Is there any advantage to dropping it and creating a new one?

**Comment by keithf4** [comment]
Guess that could work just as well.
