### ISSUE TITLE
retention_schema not working properly

### ISSUE THREAD

**Issue by gsrirangan** [pgpartman/pg_partman#481]
Hi,
I have set retention_schema='archive' and below is the part_config settings.

-- CREATE SCHEMA IF NOT EXISTS partman;
-- CREATE SCHEMA IF NOT EXISTS archive;
-- CREATE EXTENSION pg_partman WITH SCHEMA partman;

SELECT partman.create_parent(
	'public.Runtime', --p_parent_table
	'ExpireDate', --control
	'native', --partition_type
	'hourly', --partition_interval
	p_start_partition := now()::text, --p_start_partition
	p_premake:= 48, --how many additional partitions to always stay ahead of the current partition. Default value is 4. 
	p_automatic_maintenance :=  'on'::text 	
);

update partman.part_config
	set infinite_time_partitions = true -- to create automatic future partitions
	,retention = '1 hour'
	,retention_schema = 'archive' -- Archive data will be moved to this schema
	,retention_keep_table=false  -- true: then table will be archived. false: then table will be Purged
where parent_table = 'public.Runtime'

I have scheduled maintanence job to run every 1 hr. Ran all queries as superadmin role.

Issue#1
When the system time is 5.20 PM (17th hour), I see these partitions schema changed from public to archive 

archive."Runtime_p2022_08_12_1500"
archive."Runtime_p2022_08_12_1600" -- expected to be in public because of 1 hr retention
archive."Runtime_p2022_08_12_1700"-- expected to be in public because this is at current time range
archive."Runtime_p2022_08_12_1800" -- expected to be in public because this is at past time
public."Runtime_p2022_08_12_1900"
public."Runtime_p2022_08_12_2000"

Issue#2
Though the schema changed from 'public' to 'archive', these child partitions are still listed under the parent table in public schema. When I query the parent table public."Runtime",  I still see the expired records getting populated.

Issue#3:
When executing partman.undo_partition, below exception is thrown because the pg_partman is expecting Runtime_p2022_08_11_1700 to be in public schema where as this partition is already moved to archive schema.
Reason:
SQL Error [P0001]: ERROR: relation "public.Runtime_p2022_08_11_1700" does not exist
CONTEXT: PL/pgSQL function partman.undo_partition(text,integer,text,boolean,numeric,text,text[],boolean) line 263 at EXECUTE
DETAIL: 
HINT: 
  Where: PL/pgSQL function partman.undo_partition(text,integer,text,boolean,numeric,text,text[],boolean) line 503 at RAISE

Please let me know if I'm missing anything.

**Comment by keithf4** [comment]
So yeah it looks like if you set the table to be kept and not dropped, it doesn't detach them from the partition set. Will look into this and try to get a bug fix. 

You should be safe to manually detach the child table in the archive schema for a fix in the mean time.

Thanks for reporting!

**Comment by gsrirangan** [comment]
Great! Thanks for looking into this.

**Comment by keithf4** [comment]
I have a potential fix pushed up in the 4.7.1 branch if you'd like to give it a try. Please do not install this on production since this may not be the final 4.7.1 update. But if you're able to test it I would appreciate it 

https://github.com/pgpartman/pg_partman/tree/4.7.1
https://github.com/pgpartman/pg_partman/blob/4.7.1/updates/pg_partman--4.7.0--4.7.1.sql

**Comment by gsrirangan** [comment]
Thanks for the quick response. Unfortunately, I cannot test it because I'm
using AWS Aurora PostgreSQL.

**Comment by keithf4** [comment]
Sorry for the delay. This has been fixed in the new release for 4.7.1
