### ISSUE TITLE
pg_cron is detecting deleted table during CALL partman.run_maintenance_proc()

### ISSUE THREAD

**Issue by gsrirangan** [pgpartman/pg_partman#484]
Hi, I created a Table called public.TestPartition and enabled partition by running partman.create_parent and then deleted this table. I scheduled "CALL partman.run_maintenance_proc()" using pg_cron and seeing the job failed with below error message.

ERROR: Given parent table not found in system catalogs: public.TestPartition
CONTEXT: PL/pgSQL function show_partitions(text,text,boolean) line 51 at RAISE
SQL statement "SELECT partition_tablename                                   FROM partman.show_partitions(v_row.parent_table, p_include_default := true) LIMIT 1"
PL/pgSQL function partman.run_maintenance(text,boolean,boolean) line 156 at SQL statement
SQL statement "SELECT partman.run_maintenance('public.TestPartition', p_jobmon := 't')"
PL/pgSQL function partman.run_maintenance_proc(integer,boolean,boolean) line 42 at EXECUTE
DETAIL: 
HINT: 
CONTEXT: PL/pgSQL function partman.run_maintenance(text,boolean,boolean) line 402 at RAISE
SQL statement "SELECT partman.run_maintenance('public.TestPartition', p_jobmon := 't')"
PL/pgSQL function partman.run_maintenance_proc(integer,boolean,boolean) line 42 at EXECUTE

**Comment by keithf4** [comment]
If you dropped the table, then you need to remove it from the pg_partman configuration. Just delete the entry in the `part_config` table with the name of the table you dropped.

**Comment by gsrirangan** [comment]
Thank you. I did the same and worked fine.
