### ISSUE TITLE
Partition maintenance breaks when any partitioned table name contains _p

### ISSUE THREAD

**Issue by tsutsu** [pgpartman/pg_partman#487]
```
ERROR:  invalid value "robe" for "YYYY"
CONTEXT: SQL statement "SELECT n.nspname::text AS partition_schemaname, c.relname::text AS partition_name FROM
        pg_catalog.pg_inherits h
        JOIN pg_catalog.pg_class c ON c.oid = h.inhrelid
        JOIN pg_catalog.pg_namespace n ON c.relnamespace = n.oid
        WHERE h.inhparent = 'public.contract_balance_update_probes'::regclass
        AND pg_get_expr(relpartbound, c.oid) != 'DEFAULT'
            ORDER BY to_timestamp(substring(c.relname from ((length(c.relname) - position('p_' in reverse(c.relname))) + 2) ), 'YYYY_MM') ASC"
PL/pgSQL function show_partitions(text,text,boolean) line 111 at RETURN QUERY
SQL statement "SELECT partition_tablename                                   FROM partman.show_partitions(v_row.parent_table, p_include_default := true) LIMIT 1"
PL/pgSQL function partman.run_maintenance(text,boolean,boolean) line 156 at SQL statement
SQL statement "SELECT partman.run_maintenance('public.contract_balance_update_probes', p_jobmon := 't')"
PL/pgSQL function partman.run_maintenance_proc(integer,boolean,boolean) line 42 at EXECUTE
DETAIL: Value must be an integer.
HINT: 
CONTEXT:  PL/pgSQL function partman.run_maintenance(text,boolean,boolean) line 402 at RAISE
SQL statement "SELECT partman.run_maintenance('public.contract_balance_update_probes', p_jobmon := 't')"
PL/pgSQL function partman.run_maintenance_proc(integer,boolean,boolean) line 42 at EXECUTE
```

This seems to be because the functions `show_partition_info` and `show_partitions` contain code like the following:

```sql
substring(c.relname from ((length(c.relname) - position(''p_'' in reverse(c.relname))) + 2) )
```

...which breaks for tables that have a name containing `_p` (in the above case, `contract_balance_update_probes`.)

The parsing of partition names overall looks to be very ad-hoc. Given that partman isn't in any kind of hot path, I would suggest taking a more rigorous approach — i.e. introducing an explicit `timestamp_from_partition_suffix` function, which uses regex matching (a `CASE` expression with a series of `a SIMILAR TO r ESCAPE e` head-clause expressions) to match on the various potential partition name patterns, where each clause extracts the timestamp from the table name according to the deduced interval-type.

This change (deducing each partition's interval-type separately, rather than relying on the currently-set interval-type for the partitioned table) would also allow partitioning intervals to be mixed freely in historical partitions, without partman becoming confused. Currently, partman breaks if you switch a table from using quarterly partitioning to monthly partitioning for new partitions while retaining existing historical quarterly partitions, as `show_partitions` tries to parse all partition name suffixes as monthly partitions, and this fails for the quarterly partitions whose suffix contains `q`.

**Comment by tsutsu** [comment]
And here's a `timestamp_from_partition_suffix` function for you:

```plpgsql
CREATE OR REPLACE FUNCTION partman.extract_timestamp_from_partition_suffix (part_name text) RETURNS timestamp
    LANGUAGE plpgsql
    SET search_path = partman,pg_temp
	IMMUTABLE
	RETURNS NULL ON NULL INPUT
    AS $$
DECLARE
  suffix text;
BEGIN
  suffix := substring(part_name similar '%!_p!"[0-9]{4}!"' escape '!');
  IF suffix IS NOT NULL THEN
    -- yearly partition
    RETURN to_timestamp(suffix, 'YYYY');
  END IF;

  suffix := substring(part_name similar '%!_p!"[0-9]{4}!_[0-9]{1,2}!"' escape '!');
  IF suffix IS NOT NULL THEN
    -- monthly partition
    RETURN to_timestamp(suffix, 'YYYY_MM');
  END IF;

  suffix := substring(part_name similar '%!_p!"[0-9]{4}m[0-9]{1,2}!"' escape '!');
  IF suffix IS NOT NULL THEN
    -- monthly partition (alternate syntax)
    RETURN to_timestamp(suffix, 'YYYY"m"MM');
  END IF;

  suffix := substring(part_name similar '%!_p!"[0-9]{4}q[1234]!"' escape '!');
  IF suffix IS NOT NULL THEN
    -- quarterly partition
    RETURN to_timestamp(substring(suffix for 4), 'YYYY') + (((substring(suffix from 6)::integer - 1) * 3) || ' months')::interval;
  END IF;

  suffix := substring(part_name similar '%!_p!"[0-9]{4}w[0-9]{1,2}!"' escape '!');
  IF suffix IS NOT NULL THEN
    -- weekly partition
    RETURN to_timestamp(suffix, 'YYYY"w"WW');
  END IF;

  suffix := substring(part_name similar '%!_p!"[0-9]{4}d[0-9]{1,3}!"' escape '!');
  IF suffix IS NOT NULL THEN
    -- daily partition
    RETURN to_timestamp(suffix, 'YYYY"d"DDD');
  END IF;

  RETURN NULL;
END
$$;
```

Use of this function for `ORDER BY` requires two pre-checks / assumptions:

- That the table is using time-based intervals, not ID-based intervals. (A table cannot be switched from using one to using the other while retaining existing partitioning, so it's fine to have ID-based partition parsing exist separately — the ID parser will never see tables with any of the complex time-based interval types.)

- That the default partition has been excluded. (Already done in the current code.)

**Comment by keithf4** [comment]
Appreciate the bug report and the suggestions. I have plans for the 5.x refactor (see https://github.com/pgpartman/pg_partman/discussions/360) to not even try parsing the boundaries out of the partition name anymore and just look them up directly from the catalogs. I already started doing this in `show_partition_inf()` here: https://github.com/pgpartman/pg_partman/blob/master/sql/functions/show_partition_info.sql#L85. Main reason it still parses the name itself now is because trigger-based partitioning requires it.

I just need to make more use of the catalog lookups throughout the rest of the code.  This could possibly also solve the issue of having a single partition set with different interval sizes as well. I'll also be simplifying the actual suffix values use for time partition so there isn't nearly as much variation that needs to be accounted for (thinking of only having YYYY_MM_DD or YYYY_MM_DD_HHMISS).

**Comment by rezonick** [comment]
Hi guys, I got this issue too, can you suggest any workaround for this one? do I have to rename all the tables and partitions that contain '_p'?

**Comment by keithf4** [comment]
At this time, yes, you will have to rename the partition set. I'd rather try and solve this in version 5.x with direct partition range lookups vs trying to parse it out of the suffix. Apologies for the delay on that.

**Comment by keithf4** [comment]
Version 5.0.0 has been released and should be using catalog lookups in all cases instead of parsing the child table name. Let me know if things are working better for you now.
