### ISSUE TITLE
EXTENSION UPDATE failed on ERROR:  procedure partman.partition_data_proc does not exist

### ISSUE THREAD

**Issue by kong1man** [pgpartman/pg_partman#488]
```sql
psql (14.3 (Ubuntu 14.3-1.pgdg20.04+1))
\dx pg_partman
                             List of installed extensions
    Name    │ Version │ Schema  │                     Description                      
────────────┼─────────┼─────────┼──────────────────────────────────────────────────────
 pg_partman │ 4.4.0   │ partman │ Extension to manage partitioned tables by time or ID
(1 row)

ALTER EXTENSION "pg_partman" UPDATE;
psql:update_extensions.sql:10: ERROR:  procedure partman.partition_data_proc(text, text, integer, integer, text, text, integer, integer, boolean) does not exist
CONTEXT:  SQL statement "DROP PROCEDURE partman.partition_data_proc (text, text, int, int, text, text, int, int, boolean)"
PL/pgSQL function inline_code_block line 33 at SQL statement
```
How do I resolve this error to get it upgraded to 4.6.2?

**Comment by keithf4** [comment]
This can happen if pg_partman was originally installed when PostgreSQL itself was a version earlier than 11, which doesn't support procedures. The best fix for this is to get the procedures restored and then update to the latest version of pg_partman.

I just recently wrote up a document for how to do this. You will have to re-install the current version you have installed first before you can upgrade.

https://github.com/pgpartman/pg_partman/blob/master/doc/fix_missing_procedures.md

**Comment by kong1man** [comment]
We will plan an upgrade according to the document.
