### ISSUE TITLE
Drop trigger-based partitioning support

### ISSUE THREAD

**Issue by keithf4** [pgpartman/pg_partman#490]
Drop all trigger-based support from pg_partman. As of version 5.x, all partition sets must be migrated to using native partitioning to continue usage of pg_partman.

See howto documentation here for guidance on migration - https://github.com/pgpartman/pg_partman/blob/master/doc/migrate_to_native.md

TODO - Review the above documentation once 5.x is out to account for any differences

**Comment by vitaly-burovoy** [comment]
I am afraid there is a call to already deleted [1] function left in current 5.0.0-beta:

https://github.com/pgpartman/pg_partman/blob/8e94bf3df7112e818a8471cfda9ba01438c71aec/sql/functions/partition_data_id.sql#L254

[1] f18040180d756e4be5fe977b6da036662d37e472

**Comment by keithf4** [comment]
> I am afraid there is a call to already deleted [1] function left in current 5.0.0-beta:
> 
> https://github.com/pgpartman/pg_partman/blob/8e94bf3df7112e818a8471cfda9ba01438c71aec/sql/functions/partition_data_id.sql#L254
> 
> [1] [f180401](https://github.com/pgpartman/pg_partman/commit/f18040180d756e4be5fe977b6da036662d37e472)

I have not applied any of the changes for 5.0.0-beta to any of the individual query files. All changes are only contained in the update file. You can see the new code for `partition_data_id()` here - https://github.com/pgpartman/pg_partman/blob/5.0.0-beta/updates/pg_partman--4.7.3--5.0.0-beta.sql#L3429

**Comment by vitaly-burovoy** [comment]
Ough. It is VERY confusing.

I really thought the current state is in the `sql/*/*.sql` files which are used by Makefile.

Do you have any tool to sync `updates/pg_partman--<prev>--<latest>.sql` and `sql/*/*.sql` files to be sure new install and upgrade gives the same state?

**Comment by keithf4** [comment]
This is only temporary while pg_partman 5.0.0 is in beta so I don't have go to back and re-apply those changes again if any issues crop up during the beta.

If you want to install the beta, you first have to install the current stable, then upgrade. When 5.0.0 final is out, I will update the files accordingly.

**Comment by keithf4** [comment]
Version 5.0.0 has been released with trigger-based partitioning being dropped.
