### ISSUE TITLE
Cannot create partition job_log and job_detail

### ISSUE THREAD

**Issue by phuonghuynguyen** [pgpartman/pg_partman#491]
Hi, I have installed jobmon extension and it works properly.
However, when I try to partition table job_log and job_detail with this execution:

`postgres=# SELECT partman.create_parent(p_parent_table := 'jobmon.job_log', p_control := 'start_time', p_type := 'native', p_interval := 'monthly', p_jobmon := 'false');`

I get:

        ERROR:  When using native partitioning, you must have created the given parent table as ranged (not list) partitioned already. Ex: CREATE TABLE ... PARTITION BY RANGE ...)
        CONTEXT: PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,text[],boolean,text,boolean,text) line 131 at RAISE 
        DETAIL:
        HINT:
        CONTEXT:  PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,text[],boolean,text,boolean,text) line 807 at RAISE

It's an expected behaviour since that type of those table is `table`, not `partitoned table` as output below:

        postgres=# \dt jobmon.*
                      List of relations 
        Schema |         Name          | Type  |  Owner
        --------+-----------------------+-------+----------
        jobmon | dblink_mapping_jobmon | table | postgres
        jobmon | job_check_config      | table | postgres
        jobmon | job_check_log         | table | postgres
        jobmon | job_detail            | table | postgres
        jobmon | job_log               | table | postgres
        jobmon | job_status_text       | table | postgres
        (6 rows)

So my question is how can I partition those tables? Tks in advance.

**Comment by keithf4** [comment]
The table has to be set up as a partitioned table from the beginning. Since pg_jobmon is itself an extension that manages its own object creation, it can be a challenge to try partitioning it with pg_partman. Also because the partition functions will themselves be calling pg_jobmon, this may cause some circular dependencies when it tries to do maintenance and not work as expected.

So unfortunately, I haven't been able to find a great way to manage partitioning in pg_jobmon by pg_partman itself.

**Comment by phuonghuynguyen** [comment]
Can you show me how to set it up from the start (like a config file, etc) since these tables are created right after excuting: 
`CREATE EXTENSION pg_jobmon SCHEMA jobmon;`
I can create and maintain these tables manually but I don't know when and where to set them.

**Comment by keithf4** [comment]
You would either have to modify the extension code that creates the tables to make them partitioned during creation

https://github.com/pgpartman/pg_partman/blob/master/sql/tables/tables.sql

Or, if you're doing it afterwards, you'd have to remove the table from the extension, migrate it to a partitioned table using one of the methods outlined in the pg_partman howto's, and then re-add it back. These would use the ALTER EXTENSION commands

https://www.postgresql.org/docs/15/sql-alterextension.html

The main caveat to this would then be, if there was some change in pg_jobmon in the future, your partitioned setup may not allow that update to run depending on what it is. Not a likely scenario, but it is one I have to mention.

**Comment by phuonghuynguyen** [comment]
Noted! Thanks for your fast response!
