### ISSUE TITLE
extension "pg_partman" has no installation script nor update path for version "4.7.1"

### ISSUE THREAD

**Issue by abdoulayedrame** [pgpartman/pg_partman#492]
Hi,
 I have postgresql version 14.6 installed. Now I have installed partman extension  but when I try to run  **CREATE EXTENSION pg_partman SCHEMA partman;** it fails with the error message below

 **_"ERROR:  extension "pg_partman" has no installation script nor update path for version "4.7.1""_**

Do you have a hint what the cause may be?

Thanks.

**Comment by keithf4** [comment]
How did you install pg_partman? Via package or manually building? I've tested the latter and it worked fine. If the first, that sounds like either the wrong version of the package was installed for PG14 or the package is broken.

**Comment by abdoulayedrame** [comment]
I got it running. Seems like my user needed to be superuser in order to be able to create the extension.

**Comment by keithf4** [comment]
Glad to hear. Most extensions do require super user to install. There is a new feature to allow non-superusers to do so, but I'll have to investigate whether this one can do that.
