### ISSUE TITLE
I don't think the SELECT... FOR UPDATE in partition_data_time.sql is locking any rows

### ISSUE THREAD

**Issue by nicwolff** [pgpartman/pg_partman#496]
At https://github.com/pgpartman/pg_partman/blob/master/sql/functions/partition_data_time.sql#L249-L255 you have
```
EXECUTE format('SELECT %s FROM ONLY %I.%I WHERE %s >= %L AND %4$s < %5$L FOR UPDATE NOWAIT'
    , v_column_list
    , v_source_schemaname
    , v_source_tablename
    , v_partition_expression
    , v_min_partition_timestamp
    , v_max_partition_timestamp);
```
which I assume is meant to select the rows with `v_partition_expression` between `v_min_partition_timestamp` and `v_max_partition_timestamp`.

However, `%4$s < %5$L` evaluates to `v_partition_expression < v_min_partition_timestamp`, so I don't think that is selecting or locking any rows. It should be `%4$s < %6$L`, right?

I opened https://github.com/pgpartman/pg_partman/pull/495 to make that change.

**Comment by keithf4** [comment]
Released version 4.7.2 with this fix. Thanks very much for reporting and fixing it!
