### ISSUE TITLE
partition_gap_fill() fails for a table partitioned on timestamp

### ISSUE THREAD

**Issue by xin-hedera** [pgpartman/pg_partman#503]
The table is configured with timestamp partition and an interval of `quarterly`. The following error is reported when doing `partition_gap_fill`:

```
ERROR:  invalid input syntax for type bigint: "3 mons"
CONTEXT:  PL/pgSQL function partman.partition_gap_fill(text) line 127 at assignment
```

Note the string `"3 mons"` comes from `partman.part_config`

More context:

- partman version 4.7.1 
- the table is partitioned on a `bigint` nanosecond precision timestamp column
- partition set is created with `select partman.create_parent('schema.table', 'timestamp', 'native', 'quarterly', p_epoch := 'nanoseconds' , p_premake := 1);`

**Comment by keithf4** [comment]
Thanks for reporting this. I'll try and look into it my next development round.

**Comment by keithf4** [comment]
Apologies for delay. Looks like epoch wasn't accounted for in the gap fill function. Will work on a fix.

**Comment by keithf4** [comment]
I have a branch with a fix for this available here. If you're able to give it a test, let me know if this fixes it for you as well

https://github.com/pgpartman/pg_partman/tree/gap_fill_epoch

**Comment by keithf4** [comment]
Also, just wanted to let you know that I'll be getting rid of the explicit `quarterly` partitioning option with 5.x. It will still be possible to partition by 3 month intervals, it's just that the special `YYYYq#` suffix is going away. It was always a weird one to handle since the quarterly interval isn't recognized consistently across all time related functions.

**Comment by xin-hedera** [comment]
sure. let me test the branch. will get back asap. thanks!

**Comment by keithf4** [comment]
Have you been able to test this? Would like to try and get this release done by end of next week if possible. Thanks!

**Comment by xin-hedera** [comment]
just verified and it works as expected, thanks!

**Comment by keithf4** [comment]
Version 4.7.3 has been released with this fix. Thanks for reporting and testing!
