### ISSUE TITLE
can list-based partitions be automatically created?

### ISSUE THREAD

**Issue by bsislow** [pgpartman/pg_partman#504]
i see that pg_partman automatically creates _range-based_ partitions, but can it create new partitions for _list-based_?

if so, i did not see this in documentation, my apologies.

if not, are there any plans for functionality like this?

thank you.

**Comment by keithf4** [comment]
Not at this time. I'll be investigating it in the future, but more specifically for integer based partitioning.

**Comment by bsislow** [comment]
understood, thank you.

do you know of any other tools that support what we're looking for by any chance?

**Comment by keithf4** [comment]
I'm not aware of any others at this time.

**Comment by bsislow** [comment]
i'd like to reopen this to ask a similar question...

our structure for a new application will be:
- partitioned by list (integer)
- subpartitioned by range (date)

if we _manually_ create the list values, can we specify a single value for the list bucket?

for example, col1 is the list integer - and we want to create a new partition _just_ for the value 1234 and create a corresponding subpartition for the current week.

i can't see any way to do this with the current `create_parent` function. i tried the following:

```
SELECT partman.create_parent('adl.id_taptest_table', 'col1', 'native', '10', p_premake=>1, p_start_partition=>'1234');
```
... but it creates two partitions, one with a start value of 1230, and another of value 1240 because the minimum interval is 10 (not 1).

then, we may create another value of 5678 and want a single partition for that as well, but of course it will create 5670 and 5680.

basically, we're trying create **buckets** to hold a single value with weekly subpartitions under each "bucket:"

- partition 1234
-- subpartition 23jan2023
-- subpartition 30jan2023 
-- etc.
- partition 5678
-- subpartition 23jan2023
-- subpartition 30jan2023 
-- etc.

below is a code demo of what i'm trying to do. perhaps this is a feature request?

```
xxxx=> CREATE TABLE id_taptest_table (
xxxx(>     col1 bigint
xxxx(>     , col2 text not null
xxxx(>     , col3 timestamptz DEFAULT now()
xxxx(>     , col4 text) PARTITION BY RANGE (col1);
CREATE TABLE
xxxx=> CREATE INDEX ON id_taptest_table (col1);
CREATE INDEX
xxxx=> SELECT partman.create_parent('xxxx.id_taptest_table', 'col1', 'native', '10', p_premake=>1, p_start_partition=>'1234');
 create_parent
---------------
 t
(1 row)

xxxx=> \d
                            List of relations
 Schema |                Name                 |       Type        | Owner
--------+-------------------------------------+-------------------+-------
 xxxx    | api_debug_logs                      | partitioned table | xxxx
 xxxx    | api_debug_logs_id_seq               | sequence          | xxxx
 xxxx    | api_debug_logs_p5237260000000000021 | partitioned table | xxxx
 xxxx    | id_taptest_table                    | partitioned table | xxxx
 xxxx    | id_taptest_table_default            | table             | xxxx
 xxxx    | id_taptest_table_p1230              | table             | xxxx
 xxxx    | id_taptest_table_p1240              | table             | xxxx
(7 rows)
```

i don't understand this; shouldn't a new partition be created based on the new col1 list value that doesn't fit into the existing buckets?

```
xxxx=> insert into id_taptest_table values (5678,'test',now(),'test');
INSERT 0 1
xxxx=> select count(*) from id_taptest_table_default;
 count
-------
     1
(1 row)

xxxx=> select partman.run_maintenance();
 run_maintenance
-----------------

(1 row)

xxxx=> select count(*) from id_taptest_table_default;
 count
-------
     1
(1 row)

xxxx=> select * from id_taptest_table_default;
 col1 | col2 |             col3              | col4
------+------+-------------------------------+------
 5678 | test | 2023-01-23 11:05:28.981399-06 | test
(1 row)
```

thank you.

**Comment by keithf4** [comment]
A single value integer partition is not supported in pg_partman at this time. And yes, list would be ideal for that. I have it in my feature list to investigate either as part of version 5.0 or a patch after that point.

Any particular reason you're sub-partitioning? There is no performance benefit to get out of it unless you start getting into massive data sizes (high-terabyte/petabyte levels). And actually it could hurt performance depending on your situation since there's more tuple routing and conditionals to check. Also, the indexes and data always live at the lowest levels.
If it's for an organizational reason or for making data retention at different levels possible, that can work. Just want to set expectations for what you're trying to get out of it.

**Comment by bsislow** [comment]
the current database that we're trying to convert to declarative is using inheritance for starters. current size is ~110TB, so we are in the range that may benefit from this.

additionally, we need to purge old data that is older than a given retention.

the current structure is simply list-based inheritance. old data is purged using `DELETE` statements. you can see the problem here; slow trigger-based performance for the application (which is `INSERT`-_only_) and manual vacuums required to keep the purging in check, otherwise we risk excessive dead tuples.

does our strategy moving forward still make sense to pursue to you?

**Comment by keithf4** [comment]
What level are you doing the retention at? Time or the ID value as well? If it's just time, you may not need the ID level of partitioning. You can always partition at a lower interval than your retention level as well, to avoid individual tables getting too large. Like if you're retention is month or week-based, there's nothing stopping you from partitioning by day. Smaller indexes and tables there help vacuum run more efficiently as well.

And just for clarification, that data size I'm talking about is for the individual table, not the entire database.

**Comment by bsislow** [comment]
weekly subpartitioning. IDs are essentially clients and they may need to be dropped as they are off-boarded.

it's important to mention that some _queries_ will use both the ID and time value for lookups. this is also where the extra layer of partitioning could be needed.

the entire database in question at the size mentioned only has one (very large) parent table; including children (indexes, toast) = 110TB or so.

**Comment by bsislow** [comment]
can i email you a few more details that i'd rather not publicly post?

**Comment by keithf4** [comment]
I was going to say that if there was no retention based around the ID, then you'd really want to test if you actually get any benefit out of partitioning by that value. It could've been needless complexity. But at this size, if you need to easily be able to drop a userid, then there could definitely be a benefit to the subpartitioning here if you need to do retention based on both ID and time.

I don't think there's a need for more details at this time. I have plans for supporting something like this in the future, but I don't have any ETA at this time. However, if you still have questions I'm happy to help.

**Comment by bsislow** [comment]
IDs will _rarely_ be dropped so we will strongly consider simply partitioning by date.

thanks so much for your extended assistance here.

**Comment by bsislow** [comment]
One more question...

If _we_ maintain the top-level partitioning based on list (for a single value), we can use `pg_partman` to maintain range-based (date) subpartitions under the top level manually-managed list-based?

**Comment by keithf4** [comment]
Yes, I believe that should be possible. They'll just all be individual partition sets inside pg_partman.

**Comment by bsislow** [comment]
Does the _first_ range-based subpartition need to be manually created then attached then?

Here is an example structure; can you show me how to attach the manually created one, then show me how to create new range-based? Apologies for the need for an example; this is my first time doing this. **Thank you!**

```
CREATE SEQUENCE testtable_id_seq;

CREATE TABLE testtable (
    ID BIGINT NOT NULL DEFAULT NEXTVAL('testtable_id_seq'),
    the_list_id BIGINT NOT NULL,
    EVENT_TIME TIMESTAMP (6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (the_list_id, EVENT_TIME, ID)
) PARTITION BY LIST (the_list_id);

ALTER SEQUENCE testtable_ID_SEQ OWNED BY testtable.ID;

CREATE TABLE testtable_p1234 PARTITION OF testtable FOR VALUES IN (1234)
PARTITION BY RANGE (EVENT_TIME);

CREATE TABLE testtable_p1234_sp20230109 PARTITION OF testtable_p1234
FOR VALUES FROM ('2023-01-09'::timestamptz) TO ('2023-01-16'::timestamptz);
```

**Comment by keithf4** [comment]
Apologies, but I'm a bit short on time to provide the full support you may need on this. But essentially you will have to create the child table that will in turn be partitioned by time. Use pg_partman on that child table to partition it, then ATTACH it to the LIST partitioned parent appropriately. You will have to do this manually for all the range-partitioned child tables, so it may not be what you're looking to do ideally.

**Comment by bsislow** [comment]
No worries, we don't want to get down the rabbit hole too far. I'll play with options on my end - appreciate the help!

Please keep us posted on when you may implement single value integer partitioning for list-based support...
