### ISSUE TITLE
Create parent without template table using pg_partman

### ISSUE THREAD

**Issue by kovalensue** [pgpartman/pg_partman#505]
Is there any way how to force the function `create_parent` to not create a template table? I really don't need it to be created, so it would be great to have the option to skip it.

**Comment by keithf4** [comment]
Not at this time. It had been a pretty critical part of supporting a lot of features in the past, so I hadn't considered making it optional. I'll revisit that as part of my refactor for 5.0.

**Comment by kovalensue** [comment]
Thanks for the quick response. So right now I will just drop the template and set it to null in `part_config` table, guess. I could try to prepare a pull request if you don't mind :-)

**Comment by keithf4** [comment]
I appreciate the offer, but not at this time. I'm not going to be doing anymore features for the 4.x version of pg_partman, just bug fixes at this time.

**Comment by kovalensue** [comment]
Hi there, also would be nice to skip the creation of the default partition if already exists. It will make it possible to use `create_parent()` for already partitioned tables without direct insert into configuration :-) What do you think?

**Comment by keithf4** [comment]
Already have an issue open for that one. Thanks!

https://github.com/pgpartman/pg_partman/issues/489

**Comment by keithf4** [comment]
So at this time I'm not going to be allowing the skipping of the template table. Would be a bit challenging having it be an optional feature to be able to turn off and on as needed, which would be required if it was optional.

If there ever comes a time that core PG supports all the features that the template table provides, at that time I'll consider removing it.

The default table being optional will be a feature in 5.0

**Comment by keithf4** [comment]
Apologies! So it looks like I was actually able to get the template table to be optional. Was over complicating things :)

This should be in 5.0 along with the optional default as well.

**Comment by kovalensue** [comment]
Nice, glad to hear that :-)
