### ISSUE TITLE
change p_control column for native partitioned table

### ISSUE THREAD

**Issue by rodrigoparis** [pgpartman/pg_partman#507]
I've a table that was partitioned with the following steps:

SELECT partman.CREATE_parent( p_parent_TABLE => 'public.table_name',
 p_control => 'modifydate',
 p_type => 'native',
 p_interval=> 'daily',
 p_premake => 4
);

UPDATE partman.part_config
SET infinite_time_partitions = true,
    retention = '1 year',
    retention_keep_table = FALSE
WHERE parent_TABLE = 'public.table_name';

The buissness changed the requirement and I need to change the column that controls the partitioning to **actiontime**. I've tried in several ways but was impossible.

1) I've tied deleting the table and recreating it with the new p_control  in the create_parent() function, but It answers with the following error:

`SQL Error [P0001]: ERROR: Control column and type given in arguments (**actiontime**, timestamp) does not match the control column and type of the given native partition set (**modifydate**, timestamp)`

Somehow, even after deleting the table it's still related with the old p_control setting and control column.

2) I've also tried with the : **CALL partman.undo_partition_proc('public.table_name', null, p_keep_table := false, p_target_table := ''public.table_name_bis');
** But didn't work, even if the configuration from partman.part_config wasn't there after calling this procedure, I still got the same error as before.

Could you please help me?

**Comment by keithf4** [comment]
That error you got in `1.` only occurs if the column you designated with `p_control` does not match the column you declared in the original `CREATE TABLE` statement when the parent table was created. You cannot simply change the column you're partitioning by by giving a different name during create parent. You have to recreate the parent table completely and re-declare which are the partitioning columns. Can you share the structure of the parent table that is being partitioned? 

Now you've said you've deleted the table and tried again with the same result. Can you share the CREATE TABLE statement and subsequent `create_parent()` call after that?

`undo_partition_proc()` is not going to work if the table you're trying to undo does not exist in the `part_config` table.

**Comment by keithf4** [comment]
Still looking for feedback on this to be able to diagnose any issues here. Will close this issue during my next review session if there has been no response.

**Comment by keithf4** [comment]
Closing this issue for now. Please feel free to re-open if you still need assistance.

**Comment by rodrigoparis** [comment]
Sorry for not answering before, the response you provided  was exactly what it was happening!
No further assistance is needed, thanks again.
