### ISSUE TITLE
Doc error: publication inheritance was added in PG 13, not PG 14

### ISSUE THREAD

**Issue by james-johnston-thumbtack** [pgpartman/pg_partman#520]
The documentation suggests that publication inheritance was added in PG 14.  Examples where PG 14 is referenced:

https://github.com/pgpartman/pg_partman/blob/285e80962274f1d4af3d30ef6683baf416253a47/doc/pg_partman.md?plain=1#L32
https://github.com/pgpartman/pg_partman/blob/285e80962274f1d4af3d30ef6683baf416253a47/sql/functions/create_parent.sql#L757
https://github.com/pgpartman/pg_partman/blob/285e80962274f1d4af3d30ef6683baf416253a47/sql/functions/create_partition_id.sql#L337
https://github.com/pgpartman/pg_partman/blob/285e80962274f1d4af3d30ef6683baf416253a47/sql/functions/create_partition_time.sql#L460
https://github.com/pgpartman/pg_partman/blob/ca212077f66af19c0ca317c206091cd31d3108b8/CHANGELOG.txt#L49

Actually, this was introduced in PG 13, not PG 14:  https://www.postgresql.org/docs/release/13.0/

> Allow partitioned tables to be logically replicated via [publications](https://www.postgresql.org/docs/13/sql-createpublication.html) (Amit Langote)
> 
> Previously, partitions had to be replicated individually. Now a partitioned table can be published explicitly, causing all its partitions to be published automatically. Addition/removal of a partition causes it to be likewise added to or removed from the publication. The [CREATE PUBLICATION](https://www.postgresql.org/docs/13/sql-createpublication.html) option publish_via_partition_root controls whether changes to partitions are published as their own changes or their parent's.

I tested something like this on a PG 13 instance, just to be sure.  It seems to work, so I think the pg_partman documentation is mistaken in identifying the feature as PG 14 only.

```
BEGIN;
CREATE TABLE native_inheritance (
    row_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (current_timestamp),
    name text default '1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ'
) PARTITION BY RANGE (row_time);
CREATE PUBLICATION native_inheritance_pub FOR TABLE native_inheritance WITH (publish = 'insert');
SELECT partman.create_parent(
    p_parent_table => 'public.native_inheritance',
    p_control => 'row_time',
    p_type => 'native',
    p_interval => 'daily',
    p_premake => 7
    -- NOTE:  Not setting p_publications here!!!
);
COMMIT;
```

And then to check replication, I run on one psql instance:
```
select pg_create_logical_replication_slot('native_inheritance_slot', 'pgoutput');
```
Then, on a different psql instance, insert a row:
```
insert into native_inheritance values (current_timestamp);
```
Read the logs:
```
SELECT * FROM pg_logical_slot_get_binary_changes('native_inheritance_slot', NULL, NULL, 'proto_version', '1', 'publication_names', 'native_inheritance_pub');
```
If you do a quick decoding of the result from hex to ASCII you'll see the inserted row as expected.  I also tried `publish_via_partition_root = true` on the publication and it also works as expected: the logs show insertions into the root partition table.

**One more thing:** my example avoids setting the `p_publications` parameter because I didn't see that it would actually create a publication on the root table and take advantage of this new PG 13 feature.  Instead it still seems to add individual partitions to the publication.  However, the [documentation](https://github.com/pgpartman/pg_partman/blob/285e80962274f1d4af3d30ef6683baf416253a47/doc/pg_partman.md?plain=1#L184) doesn't really make any mention of these aspects.  If I was a new pg_partman user starting out on PG 15, I'd probably do the wrong thing here and not take advantage of this new PG 13 feature (or at least get confused without specific guidance here).

I think the documentation should point out that the parameter should not be used with native partitions on PG 13+.  Alternatively, pg_partman itself could have some added special logic here.

**Comment by keithf4** [comment]
Thanks for the update. For pg_partman 5.x that I'm working on right now, the minimum version requirement is now PG14 and I've also completely removed the p_publications parameter, so anything publication related is all handled natively now. There still is a need to run a subscription refresh on the subscriber side, so that is still part of maintenance.

If you want to double-check the new docs to see if things look correct, I'd appreciate it - https://github.com/pgpartman/pg_partman/tree/5.0.0-beta

If I was still keeping the 4.x series maintained outside of critical bug fixes, I'd definitely go back and update the docs as you've suggested, but I think since things are moving forward with a new minimum PG version required, I'll let things be as they are for 4.x for now.

Thanks again!

**Comment by keithf4** [comment]
Just noting that version 5.0.0 has been released and that I also had to remove the subscription refresh feature unfortunately. Seems some changes that were also in PG13 do not allow that to be done in an explicit transaction anymore. Will see if there some other possibility, maybe with a background worker.
