### ISSUE TITLE
dependency issues with python

### ISSUE THREAD

**Issue by Tiago-Anastacio** [pgpartman/pg_partman#522]
Hi, I have an issue installing pg_patman
pg_partman_13-4.7.0-1.sles15.x86_64 with the python dependency => Problem: nothing provides '/usr/bin/python2' needed by the to be installed pg_partman_13-4.7.0-1.sles15.x86_64

I'm using community RPMS and I  know you are not the packager. But could you please tell me if this version 4.7.0 onwards  supports python3 natively ?

Thank you

**Comment by keithf4** [comment]
Please send this question to the rpm mailing list ([pgsql-pkg-yum](https://www.postgresql.org/list/pgsql-pkg-yum/)). I'm not sure what the dependency chain may be for the package that could be causing this issue.

https://www.postgresql.org/list/

**Comment by keithf4** [comment]
The python scripts for pg_partman are not tied to either python 2 or 3 and should work for either version. I would hope that they have a dependency for python 3 for the packages at this point, though.

**Comment by keithf4** [comment]
Did you have any further questions here? This would be something that needs to be resolved upstream if you're seeing a package  dependency issue.
