### ISSUE TITLE
unable to run partman.run_maintenance_proc(0,true,true)

### ISSUE THREAD

**Issue by mattbunter** [pgpartman/pg_partman#531]
PG 13.10
Partman 4.7.2
8 tables partitioned
Unable to run partman.run_maintenance_proc(0,true,true), lots of locks, seems that partman cannot drop an old table

When we run it, we get loads of locks, but on tables that have nothing to do with the partitioned tables.
And the blocking PID isn't even the session running the partman.run_maintenance_proc.

This is a very new issue, unfortunately the version tested was 4.6.2 with no issue but we have 4.7.2 that ius blocking us.

**Comment by mattbunter** [comment]
Tested after running analyse on all tables. Locks when attaching an empty partition.

**Comment by mattbunter** [comment]
mobility=# call partman.run_maintenance_proc(0,NULL,false);
NOTICE:  Partman maintenance already running or another session has not released its advisory lock.
CALL

**Comment by mattbunter** [comment]
mobility=# call partman.run_maintenance_proc(0,NULL,false);
^CCancel request sent
ERROR:  canceling statement due to user request
CONTEXT:  SQL statement "ALTER TABLE mobility.t_mesure ATTACH PARTITION mobility.t_mesure_p2023_06_07 FOR VALUES FROM ('2023-06-07 00:00:00+00') TO ('2023-06-08 00:00:00+00')"
PL/pgSQL function create_partition_time(text,timestamp with time zone[],boolean,text) line 249 at EXECUTE
PL/pgSQL function partman.run_maintenance(text,boolean,boolean) line 284 at assignment
SQL statement "SELECT partman.run_maintenance('mobility.t_mesure', p_jobmon := 'f')"
PL/pgSQL function partman.run_maintenance_proc(integer,boolean,boolean) line 42 at EXECUTE

**Comment by keithf4** [comment]
> mobility=# call partman.run_maintenance_proc(0,NULL,false); NOTICE: Partman maintenance already running or another session has not released its advisory lock. CALL

This looks like you have another session opened somewhere that has started a partman maintenance run and was either cancelled or is stuck in another lock somehow. 

https://github.com/pgpartman/pg_partman/blob/master/sql/procedures/reapply_constraints_proc.sql#L34

The last response you gave shows calling the maintenance function then cancelling it. Note that this MAY leave the transactional advisory lock open for the maintenance all. Please make sure all sessions that have ever called maintenance are closed to ensure that advisory lock has been released.

As for dropping the table, are there any foreign keys to this partition set or going out from it to other tables? That would be the only reason that comes to mind that would cause locks on tables unrelated to the partition set itself.

**Comment by keithf4** [comment]
Just checking to see if you're still having any issues
