### ISSUE TITLE
how to validate a non-partition primary key is being inherited by child tables

### ISSUE THREAD

**Issue by rsquaretrade** [pgpartman/pg_partman#533]
Hello, 

We are currently in PG14 and migrating Table Inheritance to Native Partitioning.  I am doing testing on a migrated (to native partitioning) table and noticed that pre-made child tables (when doing a \d+ ) do not show the non-partition pkey (pkey" PRIMARY KEY, btree (id), that I added in a template table).  FYI, I set the template_table in partman.create_parent().  I also manually created a child table and still no pkey.

I did a different test and set up a new table configured for native partitioning, created a template table and added the pkey there then lastly, I ran the create_parent() in order for pg_partman to pre-make the child tables, and still, no pkey in the child tables.  partman.part_config inherit_privileges=true.

What am I doing wrong or is this to be expected or is there another way to validate?  Here is the content of part_config from one of my tests:
─[ RECORD 1 ]
parent_table               │ public.audit_log_native_daily_test1
partition_type             │ native
partition_interval         │ 1 day
control                    │ change_time
constraint_cols            │
premake                    │ 10
inherit_fk                 │ t
retention                  │
retention_schema           │
retention_keep_table       │ t
retention_keep_index       │ t
datetime_string            │ YYYY_MM_DD
automatic_maintenance      │ on
jobmon                     │ t
undo_in_progress           │ f
sub_partition_set_full     │ f
epoch                      │ none
optimize_trigger           │ 4
optimize_constraint        │ 30
infinite_time_partitions   │ f
trigger_exception_handling │ f
upsert                     │
trigger_return_null        │ t
template_table             │ public.audit_log_native_daily_test1_template
publications               │
inherit_privileges         │ t
constraint_valid           │ t
subscription_refresh       │

Thanks in advance.

Cheers,
Rachel

**Comment by rsquaretrade** [comment]
I resolved the issue, you can close this request.

**Comment by keithf4** [comment]
Glad you were able to resolve it. Feel free to re-open if you still have any issues.
