### ISSUE TITLE
The partitions are not generated as expected.

### ISSUE THREAD

**Issue by PQMISSCMP** [pgpartman/pg_partman#538]
Sorry if this is something basic but I have created a new table partitioned by a timestamp-type key field.
In short I run this:

```
CREATE TABLE backoffice.flatt_intentions (
id varchar NOT NULL,
state varchar NULL,
intention_createtime timestamptz NOT NULL,
)
PARTITION BY RANGE(intention_createtime);
```

`CREATE INDEX ON backoffice.flatt_intentions(intention_createtime);`

`SELECT partman.create_parent( 'backoffice.flatt_intentions', 'intention_createtime', 'native', 'daily', 0);
`

but here comes the problem, when I run my script that fills this table with mostly historical data it generates partitions according to today's date but the date I'm processing (intention_createtime) is from the past (some days in March).

So I would expect that since intention_createtime corresponds to the first 3 days of March, that partam creates partitions for the days 1, 2 and 3 of March and not with the date of these last days.

**partitions:**
<img width="1354" alt="image" src="https://github.com/pgpartman/pg_partman/assets/24899851/e9f3c766-520b-421c-ab46-aa2aaa22c7bc">

**part_config**
<img width="829" alt="image" src="https://github.com/pgpartman/pg_partman/assets/24899851/68a8c578-a99e-4418-8f09-58e9d901e8cc">

**real data**
<img width="255" alt="image" src="https://github.com/pgpartman/pg_partman/assets/24899851/d0330f42-8775-4503-aa48-d9a56ff60f5c">

did I do something wrong?

Greetings to everybody and thanks

**Comment by keithf4** [comment]
Creation of a new partition set for time is always based on the current datetime for creating the initial children. You can provide a value for the `p_partition_start` column if you'd like it to initially create earlier partitions than the default. pg_partman does not create child tables on demand if there is no child table for them. If there is no matching child table for the data it goes into the default table (if there is one) or throws an error (if there's isn't).

You can partition that data out of the default afterwards using the `partition_data_proc()` procedure.

Also curious what your intention with the final parameter value of 0 to `create_parent()` is there? The 5th parameter is the constraint columns and typically needs a column list, but can just be left NULL. Also I do not recommend reducing the premake value below the default of 4 unless you have a specific need to. pg_partman precreates child tables ahead of when they are needed to avoid contention during new child table creation.

**Comment by PQMISSCMP** [comment]
Thanks @keithf4  for answering, it really strikes me that Partman creates the partitions according to today's date and not according to the date of the key field (in this case _intention_createtime_) that is, according to the real data as one might expect it to be. Sorry to insist, is there a way to configure it to work that way?

**Comment by keithf4** [comment]
What child table is the data in that pg_partman would know at the time you call `create_parent()`? A partitioned table is empty when first created and the top level can contain no data. And pg_partman is typically run against that top level table to create the initial children. So unless you already have a child table attached to it, how would it know when your intended starting point is?

As I said, you can use the `p_start_partition` parameter to `create_parent()` to tell it which child table you want it to start at. It will then start with that child table, then also create all child tables up to the current date + the premake.

**Comment by keithf4** [comment]
Just checking if you still need any assistance with this issue

**Comment by PQMISSCMP** [comment]
sorry my friend, we decided to temporarily use mongoDb. I was not able to test the proposal you gave me, and I don't know if the partitioning worked by filling a table with data backwards in time

**Comment by keithf4** [comment]
No problem! Glad you found a solution that works for you.
