### ISSUE TITLE
Link to Docker image

### ISSUE THREAD

**Issue by Morl99** [pgpartman/pg_partman#539]
Hello @keithf4 et. al,

thank you for providing and maintaining this helpful postgres extension.

We were in the need for a docker image with postgres and pg_partman preinstalled. Since we could not find one, we created one based on the famous bitnami postgres container image.

Would you care to include a link to it in the documentation? If so, I will be happy to create a PR for the docs.

https://github.com/dbsystel/postgresql-partman-container

Currently it is based on Postgres 13 only, but if there is demand, we could offer different versions.

Greetings from DB Systel (a subsidiary of Deutsche Bahn, the German Railway Company)

Carsten Hoffmann

**Comment by keithf4** [comment]
Apologies, but since this is not a container that I'm maintaining, nor have a means to test at the moment, I cannot include it in the docs since that would invite questions to support it. If you'd like to maintain a Discussion Q&A about this, I would not object

https://github.com/pgpartman/pg_partman/discussions

**Comment by andyatkinson** [comment]
Hi @Morl99 I read through your comment and the response from @keithf4 

I think the distinction to put this in Discussions is a good starting point. Perhaps if there is engagement there, @keithf4 may include "Community Blog Posts" or something as a guide page that links out to community posts with a  a clear explanation that the project does not offer any sort of support for that content.

On the other hand, I do want to suggest that for new people coming to the GitHub project, having some links to blog posts that show things like docker containers running Postgres and partman, could really help with adoption of the project. It lowers the bar to getting started and "social proof" that a project is active. So I'm a fan. 

My unsolicited feedback for the discussion. Thanks!

**Comment by Morl99** [comment]
Okay, I wrote up a quick Q&A Discussion and answered it myself, so that people can find it, if they search for Docker or container or kubernetes. I hope that is fine with you. Since I do not have a Blog post about this at the moment, that is all we can achieve at the moment (I meant to write up on it, but it is somewhere at the bottom of my personal ToDo list at the moment ;)).

https://github.com/pgpartman/pg_partman/discussions/582

**Comment by keithf4** [comment]
Thank you! I appreciate it.
