### ISSUE TITLE
ERROR Child table given does not exist

### ISSUE THREAD

**Issue by jw1u1** [pgpartman/pg_partman#542]
It's hard to track down the affected Table, if p_child_table is null.
Please add the parent table

```
partman.show_partition_info
<  RAISE EXCEPTION 'Child table given does not exist (%)', p_child_table;
>  RAISE EXCEPTION 'Child table given does not exist (%) parent (%)', p_child_table, p_parent_table;
```

**Comment by keithf4** [comment]
I did go ahead and make this clearer, but only if the parent table parameter is actually given
```
IF v_child_tablename IS NULL THEN
    IF p_parent_table IS NOT NULL THEN
        RAISE EXCEPTION 'Child table given does not exist (%) for given parent table (%)', p_child_table, p_parent_table;
    ELSE
        RAISE EXCEPTION 'Child table given does not exist (%)', p_child_table;
    END IF;
END IF;
```
The `p_child_table` parameter is required for this function so this should be throwing errors well before reaching this point if that's so.

If you're just trying to get a more helpful error when the child table doesn't exist, that's understandable. However, the check for the child table's existence is the first step in the function and the lookup for the parent cannot be done at all if that child table doesn't exist. Also, pg_partman keeps the child table name consistent with the parent, so the name of the child table itself should hopefully give a clue to the parent involved.

**Comment by jw1u1** [comment]
What i got was ERROR:  Child table given does not exist (<NULL>) due to a misconfiguration and i had no idea, which table was causing the error.
Thank's for patching.

**Comment by keithf4** [comment]
Hmm... any idea what that misconfiguration was? Might be able to provide better error handling around that situation

**Comment by jw1u1** [comment]
Not exactly,
they renamed and re-created the parent table

**Comment by keithf4** [comment]
Version 5.0.0 has been released with this fix
