### ISSUE TITLE
Avoid the use of template table

### ISSUE THREAD

**Issue by axellpadilla** [pgpartman/pg_partman#556]
I was using it just to program maintenance on postgresql 14, but there is a template table that is used for new childs, any way to avoid that and to just use the native capabilities?

Wanted to add a field to main table for example, but that will cause template to be wrong.

**Comment by keithf4** [comment]
The template table is only used for features that are not supported in built-in declarative partitioning. There is a table in the docs that show you want it is used for. For PG14, the only thing it's used for is unique indexes that don't include the partition column and unlogged tables.

https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman.md#child-table-property-inheritance

If you're not using any of these features, I believe you should be able to set the template table column to null in the `part_config` table. Or you should just not have to worry about keeping those columns in sync either.

**Comment by axellpadilla** [comment]
Thanks for clarifying,

**Comment by keithf4** [comment]
If you have any issues with leaving the template table column null, let me know. Admittedly it's not a code path I've tested extensively.

**Comment by axellpadilla** [comment]
Ok, will test it, run maintenance test and report it back

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
