### ISSUE TITLE
creating partitions fails if one partition table data goes in to default partition

### ISSUE THREAD

**Issue by vasista** [pgpartman/pg_partman#564]
Hi, 
Hope you are doing well!
we have multiple partition tables and for any of the tables, data is present in the default partition partman.run_maintenance_proc() throws an error and will not go to the next table to create any new partitions.  Please let us know if there is any possibility to skip the issue table and move to the next one or if can we separate the partman.run_maintenance_proc() function for each table. 

Thanks
Vasista

**Comment by keithf4** [comment]
In the `part_config` table there is an `automatic_maintenance` flag that defaults to true. Any partition set with that set to true will be touched by `run_maintenance_proc()`. So if you want the general call to maintenance to skip a partition set, set that partition's flag column to false.
```
UPDATE partman.part_config SET automatic_maintenance = false WHERE parent_table = 'myschema.mytable';
```
You can set it back to true when the default table has been cleaned up and it will resume normal maintenance.

If you want to run maintenance on that specific partition set again, even when the above flag is still false, you can pass it as a parameter to the `run_maintenance()` function (not the procedure).
```
SELECT partman.run_maintenance('myschema.mytable');
```
If you want another metric to watch for when any partition set's default table gets data in it, you can use the `check_default()` function.

**Comment by vasista** [comment]
Thanks for the quick reply, this is beneficial info. Please let us know when we can expect the final version of 5.0. 

Thanks
Vasista
