### ISSUE TITLE
pg_partman 4.4.0

### ISSUE THREAD

**Issue by rsquaretrade** [pgpartman/pg_partman#575]
Hello.  I'm testing the existing pg_partman version 4.4.0 in production, so I'm installing it in our staging env but I cannot find the download pg_partman 4.4.0 (I can only install 4.7.2) , perchance can you give me the path to the download?  Thank you.

**Comment by keithf4** [comment]
You can find all past releases here, but you will have to compile them yourself

https://github.com/pgpartman/pg_partman/tags

If you're trying to find operating system packages, I do not maintain those so whatever is provided in your repository is what is available there.
