### ISSUE TITLE
partman.run_maintenance_proc() not maintaining new partitions for a id based partitioned table when data is in default table.

### ISSUE THREAD

**Issue by asranand7** [pgpartman/pg_partman#579]
**Following is the DDL for main_table:**
CREATE TABLE tis.my_table (
	id varchar(50) NOT NULL,
	payment_account_id varchar(50) NOT NULL,
	tenant_id int8 NOT NULL,
	status varchar(50) NOT NULL,
	action varchar(50) NOT NULL,
	created_at int8 NOT NULL,
	CONSTRAINT my_table_pkey PRIMARY KEY (id, created_at)
)
PARTITION BY RANGE (created_at);

Following are the **current_paritions**:
my_table_default
my_table_p1695810180000
my_table_p1695810240000
my_table_p1695810300000
my_table_p1695810360000

<img width="948" alt="image" src="https://github.com/pgpartman/pg_partman/assets/26341895/512f1305-37f4-436f-84ec-397d2a33965f">

**Partman_config** values -> 
{
"part_config": [
	{
		"parent_table" : "tis.my_table",
		"control" : "created_at",
		"partition_type" : "native",
		"partition_interval" : "60000",
		"constraint_cols" : null,
		"premake" : 1,
		"optimize_trigger" : 4,
		"optimize_constraint" : 30,
		"epoch" : "none",
		"inherit_fk" : true,
		"retention" : "600000",
		"retention_schema" : null,
		"retention_keep_table" : true,
		"retention_keep_index" : true,
		"infinite_time_partitions" : true,
		"datetime_string" : null,
		"automatic_maintenance" : "on",
		"jobmon" : true,
		"sub_partition_set_full" : false,
		"undo_in_progress" : false,
		"trigger_exception_handling" : false,
		"upsert" : "",
		"trigger_return_null" : true,
		"template_table" : "partman.template_my_table",
		"publications" : null,
		"inherit_privileges" : false,
		"constraint_valid" : true,
		"subscription_refresh" : null,
		"drop_cascade_fk" : false,
		"ignore_default_data" : false
	}
]}

**Scenario 1:**
In the table only entry is present and that too in default partition,  data is only present in default partition, **there is only one entry** (all other partitions are empty).

Result of select max(created_at) from my_table  -> 1695814154323

When I run run_maintenance_proc() with ignore_default_data being false, then it doesn't attempt to create any new partitions. I get (Updated Rows 0 ).

**Scenario 2:**
But if I insert a entry in my_table_p1695810180000 with created_at value 1695810180001 and then run run_maintenance_proc()  I get : 
<img width="1038" alt="image" src="https://github.com/pgpartman/pg_partman/assets/26341895/882bf311-a48e-4677-b939-27e38ba37bcc">

"SQL Error [P0001]: ERROR: updated partition constraint for default partition "my_table_default" would be violated by some row
CONTEXT: SQL statement "ALTER TABLE tis.my_table ATTACH PARTITION tis.my_table_p1695814140000 FOR VALUES FROM ('1695814140000') TO ('1695814200000')"
PL/pgSQL function create_partition_id(text,bigint[],boolean,text) line 198 at EXECUTE
PL/pgSQL function partman.run_maintenance(text,boolean,boolean) line 358 at assignment
SQL statement "SELECT partman.run_maintenance('tis.my_table', p_jobmon := 't')"
PL/pgSQL function partman.run_maintenance_proc(integer,boolean,boolean) line 42 at EXECUTE
DETAIL: 
HINT: 
" 

Why is it having different behaviour ? It should have thrown error in both the scenarios;

https://github.com/pgpartman/pg_partman/blob/a570c0e74809c23e1f70f0c54d39e5f2f2973f13/sql/functions/run_maintenance.sql#L312  When I went to the source code  if ignore_default_data = false, then it should show same behaviour for both the case right ? But here it is not

**Comment by keithf4** [comment]
So, the problem here is that it looks like `ignore_default_data` was only set to be honored with time-based partitioning. So since you're doing integer based here it's never checking for values in the default, only values in the non-default children.

This has been fixed in version 5.0.0. Looks like when I was changing he default of `ignore_default_data` to true, I inadvertently fixed this. Not really a critical bug at this point I don't think, since it only occurs when there is only data in the default and no other children (an unlikely realistic scenario).

Thank you for reporting the issue!
