### ISSUE TITLE
ERROR:  function partman.undo_partition_time  does not exis

### ISSUE THREAD

**Issue by seadba** [pgpartman/pg_partman#595]
Hello, running rds v14.7 partman v 4.6.2
partman seems to be functioning as expected - intial create and maintenance works both manually and through cron - 
select * from partman.part_config;

-[ RECORD 1 ]--------------+-------------------------------------------------------------
parent_table               | cp.lvap
control                    | time_stamp
partition_type             | native
partition_interval         | 1 day

however, i need to drop the current partitioned table and am encountering the following error

select partman.undo_partition_time(p_parent_table := 'cp.lvap',p_batch_count := 20, p_batch_interval :=NULL, p_keep_table := false);
ERROR:  function partman.undo_partition_time(p_parent_table => unknown, p_keep_table => boolean) does not exist
LINE 1: select partman.undo_partition_time(p_parent_table := 'cp.lvap...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

**Comment by keithf4** [comment]
There is no function `undo_partition_time()`. It's just `undo_partition()` if you're using the function or `undo_partition_proc()` if you want to use the procedure.

**Comment by seadba** [comment]
this thread   https://github.com/pgpartman/pg_partman/issues/165

**Comment by seadba** [comment]
but i didnt notice this til now    NOTE: This script is only installed for PostgreSQL 10 and lower. It has been replaced by undo_partition_proc().   -

**Comment by keithf4** [comment]
Yeah be sure to check the docs for the version you are running since the API changes over time. It's changed quite a bit in 5.0, so if you look at the current docs it's not going to match the API you have in any 4.x version.

**Comment by seadba** [comment]
thanks for the assistance
