### ISSUE TITLE
Encountered a Fatal Error During PostgreSQL Server Restart:

### ISSUE THREAD

**Issue by bigil** [pgpartman/pg_partman#601]
FATAL: Incompatible library "/usr/pgsql-16/lib/pg_partman_bgw.so" due to ABI mismatch.
DETAIL: The server has an ABI of "PostgreSQL," while the library has an ABI of "EnterpriseDB Advanced Server."
LOG: The database system is now shut down.

Any guidance on resolving this ABI mismatch issue would be greatly appreciated. Thank you!

**Comment by keithf4** [comment]
Looks like pg_partman may have been compiled with community PG, but you're running EDB? Or vice versa? Did you get partman from PGDG and are trying to run it on EDB server?

Either way, you'd be best contacting EDB support about this.

**Comment by keithf4** [comment]
Closing this issue for now. If are still having issues, feel free to re-open, but you're best bet is going to be contacting EDB support for this issue.
