### ISSUE TITLE
Trying to use ignore_default_data for running maintenance

### ISSUE THREAD

**Issue by rezonick** [pgpartman/pg_partman#623]
Hi,

Setup:
- I'm running Postgres v15 (pg_partman 4.7.3).

Issue:

`CALL partman.run_maintenance_proc();` 

- Not working as I got some data in my default partition.
- After upgrading the `pg_partman` extension I updated the `ignore_default_data` to `true` for all the partitioned tables in my database.
I tried to run again the maintenance and received the same error (I thought the maintenance should work)

```
SQL Error [P0001]: ERROR: updated partition constraint for default partition "partitioned_table_default" would be violated by some row 
CONTEXT: SQL statement "ALTER TABLE public.partitioned_table ATTACH PARTITION public.partitioned_table_p2023w19 FOR VALUES FROM ('2023-05-08 03:00:00+03') TO ('2023-05-15 03:00:00+03')"
PL/pgSQL function create_partition_time(text,timestamp with time zone[],boolean,text) line 249 at EXECUTE
PL/pgSQL function partman.run_maintenance(text,boolean,boolean) line 284 at assignment
DETAIL: 
HINT: 
CONTEXT: PL/pgSQL function create_partition_time(text,timestamp with time zone[],boolean,text) line 511 at RAISE
PL/pgSQL function partman.run_maintenance(text,boolean,boolean) line 284 at assignment
DETAIL: 
HINT: 
  Where: PL/pgSQL function partman.run_maintenance(text,boolean,boolean) line 413 at RAISE

Error position:
...
```

Am I doing something wrong? 

Thanks,

- References:
 https://github.com/pgpartman/pg_partman/issues/462

**Comment by keithf4** [comment]
Going to close this issue for now. Please feel free to respond or re-open if you have any further questions
