### ISSUE TITLE
 run_maintenance_proc() Not Working as Expected

### ISSUE THREAD

**Issue by Davide3i** [pgpartman/pg_partman#627]
Hello. I've set up a test environment with _pg_partman_ (with BGW enabled) and _pg_cron_ in a Docker container.
At the moment I'm trying to understand why _partman.run_maintenance_proc()_ is not creating new partitions even if I've set `infinite_time_partitions = true`.

This is my partition:
```
SELECT partman.create_parent(
    p_parent_table => 'public.variables_values',
    p_control => 'opc_timestamp',
    p_type => 'range',
    p_interval => '1 minute',
    p_premake => 10
);
```
This is my maintenance policy setup:
```
UPDATE partman.part_config
SET infinite_time_partitions = true,
    retention='1 minute',
    retention_keep_table = false
WHERE parent_table = 'public.variables_values';

SELECT cron.schedule('* * * * *', \$\$CALL partman.run_maintenance_proc()\$\$);

SELECT cron.schedule('0 0 * * *', \$\$DELETE 
FROM cron.job_run_details
WHERE end_time < now() - interval '7 days'\$\$);`
```

The partitions are correctly set up and they're being dropped as expected as well, but when the BGW gets to the last one, I keep seeing this message in my log:
`WARNING:  Attempt to drop final partition in partition set public.variables_values as part of retention policy. If you see this message multiple times for the same table, advise reviewing retention policy and/or data entry into the partition set. Also consider setting "infinite_time_partitions = true" if there are large gaps in data insertion.).`

No new partitions are being created, but I don't expect to have to insert new data considering how I set `infinite_time_partitions`. What am I doing wrong?
Thank you!

**Comment by Davide3i** [comment]
> Do you have any data in the partition set? This is a known issue and will be fixed in the next release. #585
> 
> The warning is there because you have an extremely small retention window and pg_partman cannot function without at least one child table. In a production environment, getting that warning repeatedly would be an indication that something is likely wrong if you're down to the final child table.

Hey @keithf4, thanks for your reply.
At the moment I don't have any data in the partition set. Actually, I've read about the issue you linked after posting my question: I'm sorry about that. Any ETA for the next release, if I may ask?
Thanks for the insight on the warning message as well!

**Comment by keithf4** [comment]
Waiting for some feedback on beta testing and I need some time to work on some more unit tests. I've set myself a deadline for March 31 and am hoping to meet or beat it.
