### ISSUE TITLE
is it safe to truncate default table

### ISSUE THREAD

**Issue by seadba** [pgpartman/pg_partman#631]
hello, running 14.9 partman 4.6.2 - partitions were not created for required slots ( a sequence between existing partitions) and now have 61M rows in default - partition_data_time spins and eventually db crashed - default stil has same # of rows and the partition in question was not created

so is it possible to run 
1 partition_gap_full
2 truncate default
3 reload data from source 

thanks

**Comment by seadba** [comment]
thanks very much for the fast response - i did not try the proc - but that sounds helpful - the crash was due to insufficient rds sizing - i will attempt the truncate and gap_full at eod - thanks - will update asap

**Comment by seadba** [comment]
ok, truncate was fine - partition_gap_fill is running but is essentally waiting on filediskread - - this table has 3years worth of daily partitions ( each day approx 60M records) - my rds class is very small, but im a bit curious why the high wait on disk i/o - i wonder if better to run create_partition_time  rather than letting gap_fill continue

**Comment by keithf4** [comment]
Gap fill isn't doing any actual lookups on the table itself, it just calculates child tables names based on general catalog information. However, adding the new child tables could be getting held up by something. Do you still have any data in the default? Any time any new child table is added, it has to compare all of the data in the default to the new child table's constraints. That can be very expensive if the default has a lot of data. This would be true for adding an new child tables, not just what gap fill is doing.

**Comment by seadba** [comment]
its interesting - i truncated the default table prior to gap_fill - the process eventually finished

select partman.partition_gap_fill('extan.track_post_log');
 partition_gap_fill
--------------------
                  5
(1 row)

Time: 60222567.219 ms (16:43:42.567)
