### ISSUE TITLE
CLUSTER under the Offline portion?

### ISSUE THREAD

**Issue by andyatkinson** [pgpartman/pg_partman#632]
Hi @keithf4 

The CLUSTER tip is good, although since this command acquires a AccessExclusiveLock on the table [1], do you think it makes sense to locate this information under the OFFLINE portion of the documentation only, as opposed to above the section that separates offline from online?

[1] https://pglocks.org/?pgcommand=CLUSTER

> One tip that may possibly help with the speed/load of partitioning a table would be to run a CLUSTER on the original source table using the partition key's index shortly before the partitioning is done. Since the data will be read sequentially from the source table, having it be in order could potentially help with IO efficiency on very large tables. See the PostgreSQL documentation - https://www.postgresql.org/docs/current/sql-cluster.html

Perhaps pg_repack could be mentioned for an "online" alternative to running CLUSTER [2]

[2] Online CLUSTER (ordered by cluster index) https://reorg.github.io/pg_repack/

**Comment by keithf4** [comment]
I'll just add a note about it being an exclusive lock. Thanks!

**Comment by keithf4** [comment]
Version 5.1 has been released with this update
