### ISSUE TITLE
unknown argument: '-no-opaque-pointers'

### ISSUE THREAD

**Issue by kbiba3** [pgpartman/pg_partman#642]
Hi,

I get this error when trying to install with make install:

"""
error: unknown argument: '-no-opaque-pointers'
make: *** [/usr/pgsql-14/lib/pgxs/src/makefiles/../../src/Makefile.global:1084: src/pg_partman_bgw.bc] Error 1
"""

Postgresql version: 14
Server: RHEL8

**Comment by keithf4** [comment]
Hmmm... never seen this one before. What compiler are you using? Only thing I've really found in reference to fixing this is when using clang. I typically use GNU make when building myself

https://forums.gentoo.org/viewtopic-p-8803936.html?sid=1822d9549c7cb622a82fe6c8543f700a

**Comment by keithf4** [comment]
Did also find this in reference to pg_repack. No solutions here, but maybe point in the right direction?

https://forums.gentoo.org/viewtopic-p-8803936.html?sid=1822d9549c7cb622a82fe6c8543f700a

**Comment by kbiba3** [comment]
Thanks for the quick response. I removed -no-opaque-pointers from /usr/pgsql-14/lib/pgxs/src/Makefile.global and it worked, but Im not still sure why this happened.

**Comment by keithf4** [comment]
I'd recommend sending this email to the bugs or hackers mailing list since this doesn't seem to be an issue in pg_partman itself.

**Comment by keithf4** [comment]
Closing this issue for now. Please feel free to reopen or if you found an answer on the lists, please share here as well.
