### ISSUE TITLE
Can't install pg_partman on Heroku Postgresql

### ISSUE THREAD

**Issue by jeremyhaile** [pgpartman/pg_partman#645]
Heroku has [documentation](https://devcenter.heroku.com/articles/increasing-performance-of-large-tables-using-partitioning) on using pg_partman.

However, when we run `CREATE EXTENSION pg_partman;` we receive the following error:

```
> CREATE EXTENSION pg_partman;
ERROR:  relation "public.custom_time_partitions" does not exist
CONTEXT:  SQL statement "GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE public.custom_time_partitions TO <role>"
PL/pgSQL function inline_code_block line 9 at SQL statement
```

I ran all of the `GRANT` commands specified in the readme for our DB user (which is a full permission user). 

I also tried creating a `partman` schema, running all of the `GRANT` commands and installing on that schema but receive the same error:

```
> CREATE EXTENSION pg_partman SCHEMA partman;
ERROR:  relation "partman.custom_time_partitions" does not exist
CONTEXT:  SQL statement "GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE partman.custom_time_partitions TO <role>"
PL/pgSQL function inline_code_block line 9 at SQL statement
```

Is this a known issue with Heroku? I assume it worked at one point in time because Heroku has documentation suggesting to use pg_partman. I also opened a ticket with Heroku Support, but was hoping you might know a workaround.

Any ideas for workarounds or fixes?

**Comment by keithf4** [comment]
This table (`custom_time_partitions`) was dropped in version 5.x of pg_partman. There's nothing in partman itself that is granting permissions to its own objects, so this must be some additional code Heroku is adding to the extension creation code and it looks like they didn't account for this object no longer existing in whatever customization they may have done. 

That is if they're trying to install version 5. Any idea what version they have?

**Comment by jeremyhaile** [comment]
Hi @keithf4 - I'm not sure what version they have. Is there any way to check from the psql console? I'm happy to run anything to help debug or find a workaround. Thanks!

**Comment by jeremyhaile** [comment]
Actually the Heroku team responded to me with this response. So it does sound like it was bug on their end. Thanks for getting back to me quickly here.

Here is the Heroku support team response:
Thanks for reaching out to Heroku Support.

There was a bug with pg_partman on Postgres 15. Looking at the error it's trying to find a particular table custom_time_partitions that no longer exists as you can see [here on GitHub](https://github.com/pgpartman/pg_partman/blob/f1c75838652487bcfdbdacf2631bf43eb318320a/updates/pg_partman--4.7.4--5.0.0.sql#L42).

Our Data Engineering team released a fix for this, however you will need to manually schedule a maintenance window then run the maintenance to take advantage of this fix. You can follow the steps to schedule a maintenance in our [How to schedule maintenance for a Heroku Postgres database?](https://help.heroku.com/TO2NALFQ/how-to-schedule-maintenance-for-a-heroku-postgres-database) help article.

**Comment by keithf4** [comment]
Thanks for letting me know!

**Comment by jeremyhaile** [comment]
OK, so Heroku did not say any maintenance was required (or available). But, apparently there was a newer version that fixed this bug. I was able to apply those updates by running `heroku data:maintenances:run` (requires the maintenance add-on to be installed first...linked to in the docs above)

After the maintenance completed, the `CREATE EXTENSION pg_partman` command works!
