### ISSUE TITLE
Installation on windows 

### ISSUE THREAD

**Issue by Mohammad-Safaie-1999** [pgpartman/pg_partman#646]
Hi i am a newby in postgresql and also programming world . can you guide me how to install this extension on my postgresql ?? 
i am using windows operating system . thanks

**Comment by keithf4** [comment]
I do not do any development on windows, but there have been several closed issues discussing that. Please review those to see if they can help.

https://github.com/pgpartman/pg_partman/issues?q=is%3Aissue+is%3Aclosed+windows

Or if you can find any guidance for any other extension installation on Windows, pg_partman should not be much different than those.
