### ISSUE TITLE
ERROR:  updated partition constraint for default partition "int_taptest_table_default" would be violated by some row.

### ISSUE THREAD

**Issue by tranicus** [pgpartman/pg_partman#652]
Ran to the following problems:  The retention not removing old partition and run_maintenance_proc() generated error. 

partmandb=# call partman.run_maintenance_proc();
ERROR:  updated partition constraint for default partition "int_taptest_table_default" would be violated by some row
CONTEXT: SQL statement "ALTER TABLE partman_test.int_taptest_table ATTACH PARTITION partman_test.int_taptest_table_p150 FOR VALUES FROM ('150') TO ('160')"
PL/pgSQL function create_partition_id(text,bigint[],text) line 151 at EXECUTE
PL/pgSQL function partman.run_maintenance(text,boolean,boolean) line 383 at assignment
SQL statement "SELECT partman.run_maintenance('partman_test.int_taptest_table', p_jobmon := 't', p_analyze := 'f')"
PL/pgSQL function partman.run_maintenance_proc(integer,boolean,boolean) line 42 at EXECUTE
DETAIL: 
HINT: 
CONTEXT: PL/pgSQL function create_partition_id(text,bigint[],text) line 300 at RAISE
PL/pgSQL function partman.run_maintenance(text,boolean,boolean) line 383 at assignment
SQL statement "SELECT partman.run_maintenance('partman_test.int_taptest_table', p_jobmon := 't', p_analyze := 'f')"
PL/pgSQL function partman.run_maintenance_proc(integer,boolean,boolean) line 42 at EXECUTE
DETAIL: 
HINT: 
CONTEXT:  PL/pgSQL function partman.run_maintenance(text,boolean,boolean) line 437 at RAISE
SQL statement "SELECT partman.run_maintenance('partman_test.int_taptest_table', p_jobmon := 't', p_analyze := 'f')"
PL/pgSQL function partman.run_maintenance_proc(integer,boolean,boolean) line 42 at EXECUTE
partmandb=# \d+ partman_test.int_taptest_table;
                                    Partitioned table "partman_test.int_taptest_table"
 Column |           Type           | Collation | Nullable | Default | Storage  | Compression | Stats target | Description 
--------+--------------------------+-----------+----------+---------+----------+-------------+--------------+-------------
 col1   | bigint                   |           | not null |         | plain    |             |              | 
 col2   | text                     |           |          |         | extended |             |              | 
 col3   | timestamp with time zone |           | not null | now()   | plain    |             |              | 
 col4   | text                     |           |          |         | extended |             |              | 
Partition key: RANGE (col1)
Indexes:
    "int_taptest_table_col1_idx" btree (col1)
Partitions: partman_test.int_taptest_table_p0 FOR VALUES FROM ('0') TO ('10'),
            partman_test.int_taptest_table_p10 FOR VALUES FROM ('10') TO ('20'),
            partman_test.int_taptest_table_p100 FOR VALUES FROM ('100') TO ('110'),
            partman_test.int_taptest_table_p110 FOR VALUES FROM ('110') TO ('120'),
            partman_test.int_taptest_table_p120 FOR VALUES FROM ('120') TO ('130'),
            partman_test.int_taptest_table_p130 FOR VALUES FROM ('130') TO ('140'),
            partman_test.int_taptest_table_p140 FOR VALUES FROM ('140') TO ('150'),
            partman_test.int_taptest_table_p20 FOR VALUES FROM ('20') TO ('30'),
            partman_test.int_taptest_table_p30 FOR VALUES FROM ('30') TO ('40'),
            partman_test.int_taptest_table_p40 FOR VALUES FROM ('40') TO ('50'),
            partman_test.int_taptest_table_p50 FOR VALUES FROM ('50') TO ('60'),
            partman_test.int_taptest_table_p60 FOR VALUES FROM ('60') TO ('70'),
            partman_test.int_taptest_table_p70 FOR VALUES FROM ('70') TO ('80'),

**Comment by keithf4** [comment]
The error is actually at new child table creation and it looks like you have data inserted into the default partition that would conflict with that. 
```
 updated partition constraint for default partition "int_taptest_table_default" would be violated by some row
 ```
Please review the contents of the default and if you don't need it, feel free to simply delete it and maintenance will resume as normal. 

If you'd like to keep it, run the `partition_data_proc()` procedure and it will move the table to the proper child table(s), creating them as needed. If it's a lot of data, you'll probably want to plan an outage for this since it can cause locks on the data for extended periods of time while the data is moved around. Also be aware that if this data is far into the future of "now", you'll likely have a gap in the child tables. You can use the `partition_gap_fill()` function to fix this. Once normal maintenance catches up to that period, it will resume creating new tables as normal.

**Comment by tranicus** [comment]
That works, thank you Keith!
