### ISSUE TITLE
Missing Records while trasfer data from old table to new table

### ISSUE THREAD

**Issue by Thavarajan** [pgpartman/pg_partman#665]
### Discussed in https://github.com/pgpartman/pg_partman/discussions/663

<div type='discussions-op-text'>

<sup>Originally posted by **Thavarajan** June  6, 2024</sup>
Good evening Team, 
   it's a wonderful extension, when I try to implement this in our existing DB,parent table have  approximately 4900000 records,

`CALL partman.partition_data_proc(
    p_parent_table := 'public.tickets'
    , p_loop_count := 2000
    , p_interval := '1000'
    , p_source_table := 'public.old_tickets'
);`

During the migration some of the records are missing, I don't know, when I try to do a count diff there are merely 6 or 7 records missing

am I missing something am I giving too many loops?</div>

**Comment by keithf4** [comment]
We already have Discussion #663 open concerning this. Please continue working on the issue there so the conversation isn't split
