### ISSUE TITLE
Possible to perform ACCESS EXCLUSIVE actions at the end of maintenance?

### ISSUE THREAD

**Issue by mplanchard** [pgpartman/pg_partman#678]
We have several very large partitioned tables where I work. When we first partitioned our tables and enabled partman, at the point where we hit our retention limit, the maintenance job ran for nearly 20 minutes, during which entire time it was holding an ACCESS EXCLUSIVE lock on the table in question. It's possible this was caused by something like #604, but I'm unsure.

It seems like the fact that DROP statements occur at the start of partition maintenance (https://github.com/pgpartman/pg_partman/blob/master/sql/functions/run_maintenance.sql#L203), prior to premaking of future partitions and so on, means that any bugs causing the latter operations to take a long time means that maintenance will cause maintenance to maintain ACCESS EXCLUSIVE locks for an unacceptably long time.

Internally, we have resolved this by writing our own logic to detach and drop old child tables, and configured partman to only be in charge of premaking future partitions.

My question is that I assume there's a reason why the drop happens first, but I wonder if you might consider moving the drop logic to the end of maintenance to minimize lock time in the event anything else takes longer than intended.

Other than this, partman has been excellent and a huge time saver. Thank you for the project!

**Comment by keithf4** [comment]
It's been quite a while since that logic was written, so I'll have to go back and revisit if there was a reason why it was being done earlier. May have had something to do with the old trigger-based methods.

If I can't find a reason, I'll certainly see about re-arranging it. Thank you!

**Comment by Durgamahesh671** [comment]
> We have several very large partitioned tables where I work. When we first partitioned our tables and enabled partman, at the point where we hit our retention limit, the maintenance job ran for nearly 20 minutes, during which entire time it was holding an ACCESS EXCLUSIVE lock on the table in question. It's possible this was caused by something like #604, but I'm unsure.
> 
> It seems like the fact that DROP statements occur at the start of partition maintenance (https://github.com/pgpartman/pg_partman/blob/master/sql/functions/run_maintenance.sql#L203), prior to premaking of future partitions and so on, means that any bugs causing the latter operations to take a long time means that maintenance will cause maintenance to maintain ACCESS EXCLUSIVE locks for an unacceptably long time.
> 
> Internally, we have resolved this by writing our own logic to detach and drop old child tables, and configured partman to only be in charge of premaking future partitions.
> 
> My question is that I assume there's a reason why the drop happens first, but I wonder if you might consider moving the drop logic to the end of maintenance to minimize lock time in the event anything else takes longer than intended.
> 
> Other than this, partman has been excellent and a huge time saver. Thank you for the project!



(**> Internally, we have resolved this by writing our own logic to detach and drop old child tables, and configured partman to only be in charge of premaking future partitions**.)

How did we achive this please let me know so this does help me

**Comment by mplanchard** [comment]
> How did you achieve this please let me know so this does help me

It was not trivial, and it's in our internal code so I can't paste all of it in here due to copyright and such. The general algorithm is:

For a given table under partman management (which you could either do as a manually maintained list or by querying `partman.part_config`):

First, Retrieve the child partitions and their bounds with this query:

```sql
SELECT c.relname as "table_name",
       n.nspname,
       pg_get_expr(c.relpartbound, c.oid) as "bounds"
FROM pg_partition_tree($1::text::regclass) p
     JOIN pg_catalog.pg_class c ON c.oid = p.relid
     JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE p.isleaf IS TRUE
```

Then for each row, parse the bounds column. We use this regex to extract the bounds.

```
"FROM \('(?<lower_bound>.+)'\) TO \('(?<upper_bound>.+)'\)"
```

We then parse parse them as datetime objects with this format:  `%Y-%m-%d %H:%M:%S%#z`.

We collect this into an array of child partition table names with their associated bounds, and then iterate over the array. For anything older than our desired retention time, we create a sql string like:

```sql
ALTER TABLE {parent_table} DETACH PARTITION {child_table};
```

Substituting in the parent and child table names, and then running the sql.

then, we also drop, but this step is not needed if you want to keep the table around:

```sql
DROP table {child_table}
```

We run this logic on a daily cron job. We do this in Rust, but you could theoretically do the same thing in declarative sql (e.g. pl/pgsql). We are just more comfortable writing and testing such complex logic in our primary language than in sql.

**Comment by keithf4** [comment]
@mplanchard 

Just some FYI, there are utility functions that pg_partman comes with that could possibly help simplify your logic

`show_partitions()` provides a list of child tables in the expected logical order (based on time or int values, not ASCII name ordering). You can ask for the order in ascending or descending order. By default it does not include the default table, but that can also be included if desired.

https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman.md#show_partitions

`show_partition_info()` provides the boundary information for a given child table. For native partitioning (and 5.x) this does the boundary lookup in the catalogs

https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman.md#show_partition_info

So you could combine these two functions to get the boundary values for the child tables of a given partition set out. Not quite sure how to do it in a single query off the top of my head, but could certainly be done more easily by feeding one's set of data to another in plgpsql or rust
```
keith=# select partition_schemaname||'.'||partition_tablename as child from partman.show_partitions('partman_test.time_taptest_table', 'ASC');
                   child                   
-------------------------------------------
 partman_test.time_taptest_table_p20240823
 partman_test.time_taptest_table_p20240824
 partman_test.time_taptest_table_p20240825
 partman_test.time_taptest_table_p20240826
 partman_test.time_taptest_table_p20240827
 partman_test.time_taptest_table_p20240828
 partman_test.time_taptest_table_p20240829
 partman_test.time_taptest_table_p20240830
 partman_test.time_taptest_table_p20240831
 partman_test.time_taptest_table_p20240901
 partman_test.time_taptest_table_p20240902
 partman_test.time_taptest_table_p20240903
 partman_test.time_taptest_table_p20240904
 partman_test.time_taptest_table_p20240905
(14 rows)

keith=# select child_start_time, child_end_time from partman.show_partition_info('partman_test.time_taptest_table_p20240823');
    child_start_time    |     child_end_time     
------------------------+------------------------
 2024-08-23 00:00:00-04 | 2024-08-24 00:00:00-04
```

Not saying there's anything wrong with your method, but I ended up having to do this so many times myself both within partman's logic and with external tools like you have here, I figured I'd try and make a consistent interface for it.

**Comment by mplanchard** [comment]
Oh that's great, thank you! Next time I wind up touching that logic, I'll replace our custom stuff with these functions.

**Comment by Durgamahesh671** [comment]
Thanks a lot

**Comment by Durgamahesh671** [comment]
Hi 

 archiving | changelog_selection_p20240830 | table             | postgres  | permanent   | heap          | 64 GB      |
 archiving | changelog_selection_p20240906 | table             | postgres  | permanent   | heap          | 78 GB      |
 archiving | changelog_selection_p20240913 | table             | postgres  | permanent   | heap          | 78 GB      |

Here we have 3 child tables 
Agenda is to remove changelog_selection_p20240830 this table as retention policy on patent table was about 7 days 
But Wrote own logic to detach tables older than 7 days  as per mplanchard and run_maintenance_proc only for creating future partitions 

I could not able to detach this  table changelog_selection_p20240830 that is being used by an update with our own logic which leads to dead lock detection 

I need to detach unnecessary partions forcibly even they are using rowexclusive lock with our own procedure invloved in run maintenance proc 

I hope you guys understand 

Regards
Durga Mahesh

**Comment by Durgamahesh671** [comment]
> @mplanchard
> 
> Just some FYI, there are utility functions that pg_partman comes with that could possibly help simplify your logic
> 
> `show_partitions()` provides a list of child tables in the expected logical order (based on time or int values, not ASCII name ordering). You can ask for the order in ascending or descending order. By default it does not include the default table, but that can also be included if desired.
> 
> https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman.md#show_partitions
> 
> `show_partition_info()` provides the boundary information for a given child table. For native partitioning (and 5.x) this does the boundary lookup in the catalogs
> 
> https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman.md#show_partition_info
> 
> So you could combine these two functions to get the boundary values for the child tables of a given partition set out. Not quite sure how to do it in a single query off the top of my head, but could certainly be done more easily by feeding one's set of data to another in plgpsql or rust
> 
> ```
> keith=# select partition_schemaname||'.'||partition_tablename as child from partman.show_partitions('partman_test.time_taptest_table', 'ASC');
>                    child                   
> -------------------------------------------
>  partman_test.time_taptest_table_p20240823
>  partman_test.time_taptest_table_p20240824
>  partman_test.time_taptest_table_p20240825
>  partman_test.time_taptest_table_p20240826
>  partman_test.time_taptest_table_p20240827
>  partman_test.time_taptest_table_p20240828
>  partman_test.time_taptest_table_p20240829
>  partman_test.time_taptest_table_p20240830
>  partman_test.time_taptest_table_p20240831
>  partman_test.time_taptest_table_p20240901
>  partman_test.time_taptest_table_p20240902
>  partman_test.time_taptest_table_p20240903
>  partman_test.time_taptest_table_p20240904
>  partman_test.time_taptest_table_p20240905
> (14 rows)
> 
> keith=# select child_start_time, child_end_time from partman.show_partition_info('partman_test.time_taptest_table_p20240823');
>     child_start_time    |     child_end_time     
> ------------------------+------------------------
>  2024-08-23 00:00:00-04 | 2024-08-24 00:00:00-04
> ```
> 
> Not saying there's anything wrong with your method, but I ended up having to do this so many times myself both within partman's logic and with external tools like you have here, I figured I'd try and make a consistent interface for it.

Hi Team 



Hi
@mplanchard @keithf4
archiving | changelog_selection_p20240830 | table | postgres | permanent | heap | 64 GB |
archiving | changelog_selection_p20240906 | table | postgres | permanent | heap | 78 GB |
archiving | changelog_selection_p20240913 | table | postgres | permanent | heap | 78 GB |

Here we have 3 child tables
Agenda is to remove changelog_selection_p20240830 this table as retention policy on parent table was about 7 days
But Wrote own logic to detach tables older than 7 days as per mplanchard and run_maintenance_proc only for creating future partitions

I could not able to detach this table changelog_selection_p20240830 that is being used by an update with our own logic which leads to dead lock detection

I need to detach unnecessary partions forcibly even they are using rowexclusive lock with our own procedure invloved in run maintenance proc

I hope you guys understand

Regards
Durga Mahesh

**Comment by keithf4** [comment]
@mplanchard 

I couldn't find any reason to not do the retention drops after table creation, so I moved that logic later in that function. Thanks for the suggestion! Will be in the next release.

@Durgamahesh671 
If you have transactions holding locks and preventing tables from being dropped, then there's not much that partman itself can do since it has no logic for overriding locking like that and I don't think it ever will right now.
You'd probably need to write some sort of wrapper function or other script external to partman that first checks for locks against the tables targetted for retention and kills any sessions touching them. Otherwise, perhaps revisit your application logic so that it doesn't take such heavy locks on data for periods of time that extend into the retention periods for the data that needs to be cleaned up.

**Comment by mplanchard** [comment]
Thank you, @keithf4, that's great news!

**Comment by keithf4** [comment]
Version 5.2.0 has been released with this change to retention timing in maintenance. Thanks again for reporting the issue!

**Comment by Durgamahesh671** [comment]
Hi @keithf4  

"Does run_maintenance_proc cleanly detach tables beyond the retention policy on newer versions even running selects on tables beyond retention policy, so we don't need custom logic?
(expecting queue based detach) 
Does 5.2.0 work well by detach tables on queue based approach?
