### ISSUE TITLE
Is There a Solution to Reattach Multiple Partitions for a Date Range Once detached?

### ISSUE THREAD

**Issue by aamish-DMS** [pgpartman/pg_partman#681]
I'm using pg_partman to manage my partitions. When I update the retention policy, it doesn't reattach partitions that were detached earlier. For example, if I set the retention period to 30 days, and then set it to 40 days, I'd like to reattach the previous 10 partitions for the same date range. This would let me keep data for the whole date range, not just the last 30 days. If there's a way to do this, can you please tell me how? If not, is there a workaround that would allow me to achieve the same result?

**Comment by keithf4** [comment]
There is no mechanism in pg_partman for this if you're trying to reattach existing partitions. You'll just have to use the ALTER TABLE [...] ATTACH PARTITION commands in PostgreSQL itself

https://www.postgresql.org/docs/16/sql-altertable.html
