### ISSUE TITLE
Range-Hash Subpartioning support in pg_partman

### ISSUE THREAD

**Issue by hrawulwa** [pgpartman/pg_partman#685]
We have use cases that require us to create Range-Hash Partitioned tables.
I'm assuming pg_partman supports this, as I have seen create_subparent function in the documentation.
I'm looking for example how to create Partitioned table by Range, and then sub-partition by Hash, using pg_partman.

Here is an example of the table DDL.
create table sales( id serial, sale_date DATE, amount NUMERIC) partition by range(sale_date);
alter table sales add primary key(id, sale_date);

create table sales_2024 partition of sales for values from ('2024-01-01') to ('2024-09-01') partition by
hash(id);
create table sales_2024_1 partition of sales_2024 for values with(modulus 4, remainder 0);
create table sales_2024_2 partition of sales_2024 for values with(modulus 4, remainder 1);
create table sales_2024_3 partition of sales_2024 for values with(modulus 4, remainder 2);
create table sales_2024_4 partition of sales_2024 for values with(modulus 4, remainder 3);

I would also like to know if the Partition maintenance function "run_maintenance()" will automatically take care of sub-partition allocation and de-allocation.

Thanks
Hari

**Comment by keithf4** [comment]
This is currently not supported, but I do already have a feature request open for it

https://github.com/pgpartman/pg_partman/issues/346

**Comment by hrawulwa** [comment]
I see. So, what type of partitions can be created using create_sub_parent function? I'm specifically looking for available sub-partition types under Range Partition.

**Comment by keithf4** [comment]
You can do the time->time, time->int, int->int, int->time. And each level can have different intervals. So for time->time, you could have yearly subpartitioned by day.

Just FYI for PostgreSQL, unless you have a defined business logic case for sub-partitioning, it is not recommended. You will not gain performance from it unless you start getting into super high data sizes in a single table (billions of rows, terabytes of data). Otherwise, you're likely to see a drop in query performance. If you're looking to optimize things for maintenance (vacuum, indexing, etc), it may be better to just adjust your single level partition interval.

**Comment by hrawulwa** [comment]
I got it. The application team is planning to migrate system from Oracle to Postgres. and wanted to retain the same functionality of partition by range, sub-partition by Hash.

**Comment by keithf4** [comment]
I do plan on adding that support at some point, but I do not have an ETA at this time.

**Comment by keithf4** [comment]
One difference between Oracle and PG is that partitioning is not primarily done for query performance. Often it actually hinders until you start getting into REALLY large data sizes as I mentioned before. What it's more often used for is making retention easier and more efficient (drop the table vs large deletes) or trying to help make maintenance jobs better (vacuuming, reindexing, etc). That benefit for retention and maintenance often comes at the cost of query performance, but it can often be well worth it, especially for retention.

So I would recommend looking to why you were partitioning on Oracle. It may not be necessary in PostgreSQL.

**Comment by keithf4** [comment]
Closing this issue for now. Please keep an eye on the other issue for development of this feature. Thank you!
