### ISSUE TITLE
Is it possible to create older version of pg_partman rather than new version 

### ISSUE THREAD

**Issue by Durgamahesh671** [pgpartman/pg_partman#690]
Current version of 5.1.0 in rds postgres . How to create older version (4.6.2)of pg_partman with create extension syntax in rds postgres

**Comment by keithf4** [comment]
To create a specific version of any extension (if different versions are available) use the syntax
```
CREATE EXTENSION ... VERSION ...
```
so
```
CREATE EXTENSION pg_partman VERSION '4.6.2' SCHEMA partman;
```
For RDS, you'd have to ask AWS support if that's possible. I don't know how if they allow access to older versions. 

Outside of RDS, you'd just have to install an older version of the extension either via packages or compiling yourself.
